/**
 * Dummy-run DB standup — creates an ISOLATED, throwaway database
 * (`gun_galore_dummyrun`) on the same local Postgres as dev, applies all
 * migrations and seeds base data (categories / dealers / admin).
 *
 * Safety:
 *  - Reuses the local dev credentials from backend/.env — never prints them.
 *  - Refuses to run unless the dev DATABASE_URL host is localhost.
 *  - Only ever touches the `gun_galore_dummyrun` database; never the dev DB,
 *    never anything remote.
 *  - Writes a neutralised backend/.env.dummyrun (only DATABASE_URL +
 *    PAYMENT_MODE=manual + VERIFYNOW_MODE=sandbox + a dummy JWT secret are
 *    defined; every external credential stays UNDEFINED so each client
 *    becomes a graceful no-op/stub at boot).
 *
 * Run:  npx tsx scripts/dummy-run-setup.ts   (or `npm run dummy-run:setup`)
 */
import { Client } from 'pg';
import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';

const BACKEND = path.resolve(__dirname, '..');
const ENV_PATH = path.join(BACKEND, '.env');
const DUMMY_ENV_PATH = path.join(BACKEND, '.env.dummyrun');
const DUMMY_DB = 'gun_galore_dummyrun';

function readDevDatabaseUrl(): string {
  const txt = fs.readFileSync(ENV_PATH, 'utf8');
  const line = txt
    .split(/\r?\n/)
    .find((l) => l.trim().startsWith('DATABASE_URL='));
  if (!line) throw new Error('DATABASE_URL not found in backend/.env');
  return line
    .slice('DATABASE_URL='.length)
    .trim()
    .replace(/^["']|["']$/g, '');
}

async function main() {
  const devUrl = readDevDatabaseUrl();
  const parsed = new URL(devUrl);
  if (parsed.hostname !== 'localhost' && parsed.hostname !== '127.0.0.1') {
    throw new Error(
      `Refusing to run: dev DATABASE_URL host is '${parsed.hostname}', not localhost. ` +
        `The dummy run only ever operates on a local throwaway DB.`,
    );
  }
  if (parsed.pathname.replace(/^\//, '') === DUMMY_DB) {
    throw new Error(`Dev DATABASE_URL already points at ${DUMMY_DB}; expected the dev DB.`);
  }

  const adminUrl = new URL(devUrl);
  adminUrl.pathname = '/postgres';
  const dummyUrl = new URL(devUrl);
  dummyUrl.pathname = '/' + DUMMY_DB;

  const host = `${parsed.hostname}:${parsed.port || '5432'}`;

  // 1) Drop + recreate the throwaway DB (FORCE closes any stray sessions).
  console.log(`[setup] recreating database "${DUMMY_DB}" on ${host} ...`);
  const admin = new Client({ connectionString: adminUrl.toString() });
  await admin.connect();
  try {
    await admin.query(`DROP DATABASE IF EXISTS ${DUMMY_DB} WITH (FORCE)`);
    await admin.query(`CREATE DATABASE ${DUMMY_DB}`);
  } finally {
    await admin.end();
  }

  // 2) Write the neutralised .env.dummyrun. Only the keys below are defined;
  //    everything else (ANTHROPIC/RESEND/SMSPORTAL/PUDO/TCG/STITCH/CLOUDINARY/
  //    ZOHO/MEILI/VAPID/CLERK) stays undefined -> no-op clients.
  // Every sensitive key is set to EMPTY (not omitted). The harness preloads this
  // file first; the app also loads backend/.env at runtime, and dotenv/config is
  // no-override — so a key already present here (even empty) can NEVER be clobbered
  // by the real .env. Empty string is falsy, so each `key ? new Client() : null`
  // guard resolves to a no-op stub. This is the belt-and-braces neutralisation.
  const BLANK_KEYS = [
    'ANTHROPIC_API_KEY',
    'ANTHROPIC_ADMIN_API_KEY',
    'RESEND_API_KEY',
    'SMSPORTAL_CLIENT_ID',
    'SMSPORTAL_API_SECRET',
    'PUDO_API_KEY',
    'PUDO_BASE_URL',
    'TCG_API_KEY',
    'TCG_BASE_URL',
    'STITCH_CLIENT_ID',
    'STITCH_CLIENT_SECRET',
    'CLOUDINARY_CLOUD_NAME',
    'CLOUDINARY_API_KEY',
    'CLOUDINARY_API_SECRET',
    'MEILISEARCH_HOST',
    'MEILISEARCH_API_KEY',
    'VAPID_PUBLIC_KEY',
    'VAPID_PRIVATE_KEY',
    'IMAP_USER',
    'IMAP_PASSWORD',
    'CLERK_SECRET_KEY',
    'CLERK_WEBHOOK_SECRET',
    'ZOHO_CLIENT_ID',
    'ZOHO_CLIENT_SECRET',
    'ZOHO_REFRESH_TOKEN',
    'ZOHO_ORGANIZATION_ID',
  ];
  const dummyEnv =
    [
      '# AUTO-GENERATED by scripts/dummy-run-setup.ts — isolated + offline + safe.',
      '# Gitignored. Every external credential is intentionally BLANK so each client',
      '# degrades to a no-op/stub. Do not add real keys here.',
      `DATABASE_URL=${dummyUrl.toString()}`,
      'NODE_ENV=development',
      'PAYMENT_MODE=manual',
      'VERIFYNOW_MODE=sandbox',
      'ZOHO_BOOKS_ENABLED=false',
      'JWT_ADMIN_SECRET=dummy-run-admin-secret-not-real',
      'PORT=3999',
      ...BLANK_KEYS.map((k) => `${k}=`),
      '',
    ].join('\n');
  fs.writeFileSync(DUMMY_ENV_PATH, dummyEnv);
  console.log('[setup] wrote backend/.env.dummyrun (neutralised)');

  // 3) Apply all migrations + seed base data against the throwaway DB.
  //    DATABASE_URL is forced via env; dotenv (no-override) will not clobber it.
  const childEnv = { ...process.env, DATABASE_URL: dummyUrl.toString() };
  // NOTE: `prisma migrate deploy` does NOT work on a fresh DB — the migration
  // chain is not self-consistent (migration 20260625130000_reloading_ocr_flag
  // ALTERs `ReloadingManual`, a table created at runtime via onModuleInit, not
  // by any migration; tasks BC-SCHEMA-DRIFT / FIX-9). For a throwaway DB we push
  // the current schema.prisma directly. --accept-data-loss is a no-op here (the
  // DB is empty) and only suppresses the interactive prompt. The runtime tsvector
  // columns are created later, on the harness's first app boot.
  console.log('[setup] prisma db push (schema.prisma -> fresh DB) ...');
  execSync('npx prisma db push --accept-data-loss', {
    cwd: BACKEND,
    env: childEnv,
    stdio: 'inherit',
  });
  console.log('[setup] seeding base data (categories / dealers / admin) ...');
  execSync('npx prisma db seed', {
    cwd: BACKEND,
    env: childEnv,
    stdio: 'inherit',
  });

  // 4) Confirm the DUMMY db (not the dev db) actually got the migrations.
  const check = new Client({ connectionString: dummyUrl.toString() });
  await check.connect();
  try {
    const tbl = await check.query(
      "SELECT count(*)::int AS n FROM information_schema.tables WHERE table_schema='public'",
    );
    const catCount = await check.query('SELECT count(*)::int AS n FROM "Category"');
    console.log(
      `[setup] verified ${DUMMY_DB}: ${tbl.rows[0].n} tables created, ${catCount.rows[0].n} categories seeded.`,
    );
  } finally {
    await check.end();
  }

  console.log(`\n[setup] DONE — isolated DB "${DUMMY_DB}" is ready.`);
  console.log('[setup] next: npm run dummy-run');
}

main().catch((e) => {
  console.error('[setup] FAILED:', e?.message ?? e);
  process.exit(1);
});
