'use client';

import { useCallback, useEffect, useState } from 'react';
import { TokenGetter, motivationsApi } from '@/lib/motivations-api';

// ────────────────────────────────────────────────────────────────────
// WHAT TO TAKE TO THE POLICE STATION.
//
// The list already existed on the server and nothing rendered it — while the
// Motivation Centre's own landing page promised "a checklist of everything to
// take to the police station". This is that promise, kept.
//
// ⚠️ TWO CLASSES OF ITEM, and the distinction is the whole design.
//   OURS   — generated by us or uploaded by the applicant. We know the state,
//            so these tick themselves and cannot be un-ticked by hand.
//   THEIRS — SAPS forms, the certified ID copy, photographs, the fee. We do
//            NOT hold these and must never imply we do. Tickable by hand, and
//            the list says plainly that it is not exhaustive and that stations
//            differ.
//
// The hand ticks live in localStorage, deliberately. They are a packing list
// used once on the morning somebody drives to the station — not an assertion
// about their application, and not something that should look like a record we
// keep. A tick that did not survive changing device would be a small
// annoyance; a tick that read as "All Outdoor says you have this" would be a
// misrepresentation.
//
// ⚖️ NOTHING HERE PREDICTS AN OUTCOME. It says what the pack should contain,
// sourced from the Act and the regulations, and says to confirm it with the
// applicant's own DFO.
// ────────────────────────────────────────────────────────────────────

type Checklist = Awaited<ReturnType<typeof motivationsApi.checklist>>;

const storeKey = (id: string) => `gg-motivation-checklist:${id}`;

export default function MotivationChecklistPanel({
  token,
  motivationId,
}: {
  token: TokenGetter;
  motivationId: string;
}) {
  const [list, setList] = useState<Checklist | null>(null);
  const [ticked, setTicked] = useState<Set<string>>(new Set());
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let alive = true;
    motivationsApi
      .checklist(token, motivationId)
      .then((c) => {
        if (alive) setList(c);
      })
      .catch(() => {
        if (alive) setFailed(true);
      });
    return () => {
      alive = false;
    };
  }, [token, motivationId]);

  // Read once, on mount, on the client only.
  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(storeKey(motivationId));
      if (raw) setTicked(new Set(JSON.parse(raw) as string[]));
    } catch {
      // A corrupt or unavailable store is an empty checklist, not an error.
    }
  }, [motivationId]);

  const toggle = useCallback(
    (key: string) => {
      setTicked((cur) => {
        const next = new Set(cur);
        if (next.has(key)) next.delete(key);
        else next.add(key);
        try {
          window.localStorage.setItem(
            storeKey(motivationId),
            JSON.stringify([...next]),
          );
        } catch {
          // Private browsing, or a full quota. The tick still works for this
          // sitting; it just will not be there tomorrow.
        }
        return next;
      });
    },
    [motivationId],
  );

  if (failed || !list) return null;

  const theirs = list.sections.find((s) => s.key === 'theirs');
  const ours = list.sections.find((s) => s.key === 'ours');
  const handDone = theirs
    ? theirs.items.filter((i) => ticked.has(i.key)).length
    : 0;

  return (
    <section className="mt-6 rounded border border-[var(--border)] bg-[var(--bg-card)] p-4">
      <h2 className="font-medium">Taking it to the police station</h2>
      <p className="mt-1 text-sm text-[var(--text-secondary)]">
        Your motivation and its annexures are only part of the application. This
        is the whole pack, so you can check it before you travel.
      </p>

      {ours && (
        <div className="mt-4">
          <p className="text-sm font-medium">{ours.title}</p>
          {ours.intro && (
            <p className="mt-1 text-xs text-[var(--text-secondary)]">
              {ours.intro}
            </p>
          )}
          <ul className="mt-2 space-y-1.5">
            {ours.items.map((i) => (
              <li key={i.key} className="flex gap-2 text-sm">
                {/* NOT a checkbox: these are not the member's to tick. They
                    report what we hold, and a control that looked clickable
                    but was not would be worse than a mark. */}
                <span
                  aria-hidden
                  style={{
                    color: i.done
                      ? 'var(--success)'
                      : 'var(--text-tertiary-on-card)',
                  }}
                >
                  {i.done ? '✓' : '○'}
                </span>
                <span className="flex-1">
                  <span
                    className={
                      i.done ? 'text-[var(--text-tertiary-on-card)]' : ''
                    }
                  >
                    {i.label}
                  </span>
                  {i.annexure && (
                    <span className="ml-2 text-xs text-[var(--text-tertiary-on-card)]">
                      Annexure {i.annexure}
                    </span>
                  )}
                  {i.note && (
                    <span className="mt-0.5 block text-xs text-[var(--text-tertiary-on-card)]">
                      {i.note}
                    </span>
                  )}
                </span>
                <span className="sr-only">
                  {i.done ? 'attached' : 'not attached yet'}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {theirs && (
        <div className="mt-5">
          <div className="flex flex-wrap items-baseline justify-between gap-2">
            <p className="text-sm font-medium">{theirs.title}</p>
            <p className="text-xs text-[var(--text-tertiary-on-card)]">
              {handDone} of {theirs.items.length} ticked
            </p>
          </div>
          {theirs.intro && (
            <p className="mt-1 text-xs text-[var(--text-secondary)]">
              {theirs.intro}
            </p>
          )}
          <ul className="mt-2 space-y-1">
            {theirs.items.map((i) => {
              const on = ticked.has(i.key);
              return (
                <li key={i.key}>
                  <label className="flex min-h-[44px] cursor-pointer items-start gap-2.5 py-1 text-sm">
                    <input
                      type="checkbox"
                      className="mt-0.5 h-4 w-4 shrink-0 accent-[var(--red)]"
                      checked={on}
                      onChange={() => toggle(i.key)}
                    />
                    <span className="flex-1">
                      <span
                        className={
                          on ? 'text-[var(--text-tertiary-on-card)]' : ''
                        }
                      >
                        {i.label}
                      </span>
                      {i.note && (
                        <span className="mt-0.5 block text-xs text-[var(--text-tertiary-on-card)]">
                          {i.note}
                        </span>
                      )}
                    </span>
                  </label>
                </li>
              );
            })}
          </ul>
          <p className="mt-3 text-xs text-[var(--text-tertiary-on-card)]">
            These ticks are just for you, kept on this device. They are not part
            of your application and we do not check them.
          </p>
        </div>
      )}
    </section>
  );
}
