import { MotivationLicenceType, MotivationUploadKind } from '@prisma/client';
import {
  applicationWarnings,
  type ApplicationWarning,
} from './motivation-warnings';
// ⚠️ ONE DEFINITION OF "HOW MANY SAFE PHOTOGRAPHS", shared with
// documentStatus. Two surfaces disagreeing about it is how a member gets a
// green tick on one screen and an amber row on the next.
import { SAFE_PHOTO_MIN } from './motivation-documents';
// COMPETENCY_RENEWS_KEY is the one spelling of the key the Licence Centre
// writes its 517(g) finding to. FIREARM_SOURCE_KEY / SOURCE_DEALER /
// SOURCE_PRIVATE are read by saps271FormNote below, to say which half of
// SAPS 271 section F — if any — the applicant's own pack leaves for someone
// else to complete.
import {
  COMPETENCY_RENEWS_KEY,
  FIREARM_SOURCE_KEY,
  SOURCE_DEALER,
  SOURCE_PRIVATE,
} from './motivation-fields';

// ────────────────────────────────────────────────────────────────────
// THE SUBMISSION CHECKLIST — a LIVE, TICKABLE SURFACE, not a PDF page.
//
// Operator, 2026-08-18: "The tick boxes must be on the platform and PWA, not a
// PDF document. The whole point of this is to have it all digital until the
// document is ready to be printed."
//
// So this module is DATA. It reports what is done, what is outstanding, and
// what the applicant has to fetch themselves; the platform and the PWA render
// it as a progress list they tick as they go, and it stays live right up to the
// moment they print. Only the ANNEXURE INDEX goes into the printed document —
// a reviewer holding the paper needs to find what the body cross-references.
//
// THE CONTENT IS THE OPERATOR'S OWN LIST ("Neem saam na SAP"), not a generic
// one I invented. It is materially better because it comes from someone who has
// actually lodged these applications: it names the THREE specific safe
// photographs a DFO wants, the fee per firearm, and the warning not to sign the
// SAPS forms in advance. That last one is the kind of detail that costs a
// wasted trip to the station if you get it wrong.
//
// TWO ITEM CLASSES, and the distinction is the whole design:
//   OURS   — generated by us or uploaded by the applicant. We know the state,
//            so these tick themselves.
//   THEIRS — SAPS forms, certified copies, passport photographs, the fee. We
//            do NOT hold these and must never imply we do. They stay tickable
//            by hand, and the list says plainly that it is not exhaustive and
//            that requirements differ by station.
//
// ⚠️ VERIFY BEFORE GO-LIVE: the fee and the SAPS form number are the two things
// most likely to be quietly out of date. They are marked `verifyBeforeUse`.
// ────────────────────────────────────────────────────────────────────

/** Who is responsible for producing the item. */
export type ChecklistOwner = 'us' | 'applicant';

/**
 * Where a row stands, in three states rather than two.
 *
 * ⚠️ 'waiting-on-someone' MUST NOT COLLAPSE INTO 'not-started'. A witness who
 * has been invited and a witness who has never been asked look identical
 * through a boolean, and they are not remotely the same thing: the applicant
 * has already done their part on the first one and has nothing left to do but
 * wait. Telling them it is "not started" is telling them to redo work.
 */
export type ChecklistState = 'done' | 'waiting-on-someone' | 'not-started';

/**
 * The only two ways evidence gets onto a row. Anywhere. On any surface.
 *
 * Operator, 2026-08-28: "we do not use webcams for upload. Only Open scanner
 * with QR, Upload." A third member is not a feature request, it is a bug.
 */
export type CaptureRoute = 'qr' | 'upload';

/**
 * What the pure builder cannot know by itself.
 *
 * ⚠️ THE THIRD-PARTY STATUS HAS TO BE INJECTED, and that is deliberate.
 * buildChecklist is pure — no Prisma, no clock — and whether a seller has
 * opened his link lives in two services. Passing it in keeps the builder
 * testable and keeps every caller honest, because a caller that forgets it
 * gets 'not-started' rather than something plausible and wrong.
 */
export interface ChecklistContext {
  /**
   * Item key → the one sentence to show for a row we are waiting on somebody
   * else for. The sentence names WHO, because "waiting" without a name is
   * indistinguishable from stuck.
   */
  waitingOn?: Record<string, string>;
  /**
   * The application's answers, for the handful of rows that only apply to
   * some applicants.
   *
   * ⚠️ READ, NEVER RENDERED. Nothing here puts an answer's VALUE on the
   * screen: these are somebody's personal details and this list is printed,
   * shared and screenshotted. It is read to decide whether a row exists at
   * all — see COMPETENCY_RENEWS_KEY, which the Licence Centre writes when it
   * can see that renewing this licence also expires the competency behind it.
   *
   * Optional, and an omitted map means "no conditional rows". A caller that
   * has not got the answers to hand shows the unconditional list rather than
   * guessing — the failure mode is a row missing from a list that says at the
   * top it is not exhaustive, not a wrong instruction about a form.
   */
  answers?: Record<string, string>;
}

export interface ChecklistItem {
  /**
   * Stable key so the UI can persist a hand-tick against it.
   *
   * ⚠️ NEVER RENAME ONE. The frontend stores hand-ticks under this key; a
   * rename silently orphans every tick a member has already made, and they
   * see work they did come back undone.
   */
  key: string;
  label: string;
  owner: ChecklistOwner;
  /**
   * True only for `owner: 'us'` items we can actually confirm.
   *
   * ⚠️ ITS MEANING IS UNCHANGED BY `state` BELOW, and must stay that way.
   * `state === 'done'` implies `done`, but not the reverse. Folding a
   * third-party signal into `done` would move `oursDone`/`oursTotal` — the
   * progress ring an existing screen already renders — with no type error to
   * catch it.
   */
  done: boolean;
  /** Richer read of the same row. Derived; never contradicts `done`. */
  state: ChecklistState;
  /**
   * One sentence: who closes this row, and how.
   *
   * ⚠️ DERIVED, NOT AUTHORED PER ROW. The 'theirs' copy in this module
   * carries live regulation citations and operator-verified specifics, some
   * of it flagged verifyBeforeUse. Writing nineteen fresh bespoke sentences
   * beside it is how a legally reviewed list acquires an unreviewed
   * paraphrase that contradicts it. So this is computed from what the row IS,
   * and the section intro keeps carrying the detail.
   */
  closer: string;
  /** Offered when the row expands. Omitted where nothing can be captured. */
  captureRoutes?: CaptureRoute[];
  /** Annexure letter, where this is one of ours. */
  annexure?: string;
  /** Shown smaller under the label. */
  note?: string;
  // subItems lived here: sub-points hanging off one row, and the three safe
  // photographs were the only thing that ever used them. They went with the
  // collapse on 2026-08-23 — the safe is one row now and what the member needs
  // to be told is the `note` above, which names every shot. Nothing wrote the
  // field afterwards and nothing rendered it, so it was a hook advertising a
  // feature that no longer existed. It comes back with sub-items, if they do.
  /** Operator/attorney must confirm this is current before go-live. */
  verifyBeforeUse?: true;
}

export interface ChecklistSection {
  key: string;
  title: string;
  intro?: string;
  items: ChecklistItem[];
}

export interface ChecklistProgress {
  sections: ChecklistSection[];
  /** Items we own that are done, over items we own. Drives the progress ring. */
  oursDone: number;
  oursTotal: number;
  /** Count the applicant still has to gather themselves. */
  theirsTotal: number;
  /**
   * Where the Act is stricter than what the CFR sometimes accepts.
   *
   * ⚠️ ON THE APPLICANT'S OWN PAGE, NEVER IN THE MOTIVATION. See
   * motivation-warnings.ts: a document that argues against its own application
   * hands the Registrar their refusal in the applicant's own words. These
   * print on the sheet that is removed at the counter.
   */
  warnings: ApplicationWarning[];
}

export const UPLOAD_KIND_LABELS: Record<MotivationUploadKind, string> = {
  IDENTITY_DOCUMENT: 'Copy of your ID',
  COMPETENCY_CERTIFICATE: 'SAPS competency certificate or printout',
  PROFICIENCY_CERTIFICATE: 'Proficiency / training certificate',
  CURRENT_LICENCE: 'Existing firearm licence(s)',
  ASSOCIATION_CARD: 'Association membership proof',
  GOOD_STANDING_LETTER: 'Your letter of good standing',
  ASSOCIATION_ENDORSEMENT: "The association's endorsement for this firearm",
  ADDRESS_CONFIRMATION: 'Proof of residential address',
  EMPLOYMENT_CONFIRMATION: 'Confirmation of employment',
  SAFE_PHOTOGRAPHS: 'Photographs of your safe',
  // ── retired 2026-08-23 ───────────────────────────────────────────────
  // Present so a row written before the collapse still labels in the annexure
  // index and in the file list. Never offered anywhere.
  SAFE_PHOTO_CLOSED: 'Safe closed',
  SAFE_PHOTO_AJAR: 'Safe half open, key in the door',
  SAFE_PHOTO_BOLTS: 'Safe fully open, roll bolts visible',
  SAFE_PHOTO: 'Photographs of your safe (earlier upload)',
  SAFE_INSTALLATION: 'Photograph of the safe bolted to the wall',
  CHARACTER_REFERENCE: 'Character reference(s)',
  SHOOTING_ACTIVITY_LOG: 'Your record of shooting activities',
  FIREARM_SOURCE_PROOF: 'Where the firearm is coming from',
  SELLER_LICENCE: "The current owner's licence",
  EXECUTOR_APPOINTMENT: 'Letter of appointment as executor',
  INCIDENT_REPORT: 'Incident report / SAPS case number',
  PREVIOUS_MOTIVATION: 'Previous motivation',
  OTHER: 'Supporting document',
};

// SAFE_PHOTO_SHOTS lived here: the three shots as SUB-ITEMS hanging off one
// checklist row. It was deleted on 2026-08-19 rather than tripled, because it
// never reached a single applicant and could not have enforced anything —
// its `done` flag was never assigned, so the sub-items rendered permanently
// unticked while the parent row ticked green on the first photograph, and the
// only endpoint that served it has no caller in the frontend.
//
// The three shots then became three MotivationUploadKind values, and on
// 2026-08-23 they became one — SAFE_PHOTOGRAPHS, several files under a single
// row. What survives from all three attempts is the INSTRUCTION: the row's
// note below names every shot, and documentStatus will not tick it until
// SAFE_PHOTO_MIN photographs are attached.

/**
 * Annexure lettering order — reading order, not upload order.
 *
 * ⚠️ THIS SEQUENCE IS COPIED FROM A REAL PACK, NOT INVENTED. The operator
 * supplied the annexure list a professional motivation writer actually files
 * (2026-08-20), and it is the order below: identity, then the two
 * certificates, then address and employment, then the safe, then the
 * applicant's record, then the association documents, then where the firearm
 * is coming from.
 *
 * Ours previously put the three association documents at F-H, ahead of the
 * safe photographs. That is not wrong so much as unfamiliar — and on a
 * document a DFO reads dozens of, unfamiliar costs attention that should be
 * going to the argument. Matching the sequence they already read is free.
 */
/**
 * Documents WE produce that take a letter in the annexure sequence.
 *
 * ⚠️ AN ANNEXURE IS NOT THE SAME THING AS AN UPLOAD, and treating them as
 * one is what hid a missing document for weeks. The lettering used to walk a
 * list of upload kinds, so anything the applicant did not upload could not be
 * lettered — which silently excluded every page we generate ourselves. The
 * checklist meanwhile listed the prior-notice request under "Your pack" and
 * ticked it green, so the gap was invisible from both ends.
 */
/**
 * ⚠️ PRESS_CLIPPINGS ADDED 2026-09-07. Also generated by us rather than
 * uploaded, but for a different reason than the prior-notice request: the
 * member CHOSE these from a picker (see `press_clippings` in
 * motivation-fields.ts and NewsService), we fetch and print them, and the
 * applicant never handles a file for this one at all.
 */
export type GeneratedAnnexureId = 'SELLER_CONSENT';

/**
 * ⚠️ EMPTY SINCE 2026-09-09, AND KEPT AS A TYPE RATHER THAN DELETED. Both
 * entries left: the press clippings became body content (see ANNEXURE_ORDER)
 * and the PAJA letter is its own lodged document rather than an annexure. The
 * shape survives because `buildAnnexures` still takes the parameter and older
 * callers still pass an empty array; a future generated annexure — if one is
 * ever right — has somewhere to go without reintroducing the plumbing.
 */
export const GENERATED_ANNEXURE_LABELS: Record<GeneratedAnnexureId, string> = {
  /**
   * The page the previous owner signs, giving the applicant leave to apply for
   * a licence over his firearm.
   *
   * Operator, 2026-09-10, wrote "Annexure" across it on a rendered pack. It had
   * been printing as a sheet of its own with a line in the contents, which is
   * how a document we generate for the APPLICANT is treated — and this one is
   * not that. It is a third party's signed statement about a firearm, which is
   * exactly what an annexure is.
   */
  SELLER_CONSENT: "The previous owner's consent",
};

/** Either an uploaded document or one we generate. */
export type AnnexureKind = MotivationUploadKind | GeneratedAnnexureId;

/**
 * KINDS THAT SHARE ONE ANNEXURE LETTER.
 *
 * ⚠️ THE SAFE IS ONE ANNEXURE, and getting this wrong shifted every letter in
 * the pack. Lettering the shots separately pushed a nineteen-document pack out
 * to S where a professional one ends at O, which is the kind of difference
 * that makes a familiar document read as an unfamiliar one. The operator's
 * reference pack letters it once, as "F. PHOTOS OF SAFE".
 *
 * ⚠️ THE SAFE ENTRIES ARE STILL HERE THOUGH THE KINDS COLLAPSED ON 2026-08-23,
 * and removing them would be a live bug rather than a cleanup: a row written
 * before the collapse still carries SAFE_PHOTO_AJAR, and without a group it
 * would take a letter of its own — the exact letter-shifting this map exists to
 * prevent, on the packs of the members who filed first.
 *
 * Several copies under one letter print as "(1 of 4)", "(2 of 4)" — the same
 * machinery that handles two copies of an ID — so the letter collapses and
 * nothing about the evidence does.
 */
const LETTER_GROUPS: Partial<
  Record<MotivationUploadKind, { id: string; label: string }>
> = {
  SAFE_PHOTOGRAPHS: { id: 'safe', label: 'Photographs of your safe' },
  SAFE_PHOTO_CLOSED: { id: 'safe', label: 'Photographs of your safe' },
  SAFE_PHOTO_AJAR: { id: 'safe', label: 'Photographs of your safe' },
  SAFE_PHOTO_BOLTS: { id: 'safe', label: 'Photographs of your safe' },
  SAFE_PHOTO: { id: 'safe', label: 'Photographs of your safe' },
  SAFE_INSTALLATION: { id: 'safe', label: 'Photographs of your safe' },

  // The reference pack's "K. MEMBERSHIP CERTIFICATES" — plural — covers both
  // the membership certificate and the chairperson's declaration that the
  // member is in good standing. They stay two upload kinds because they are
  // two documents with two expiry dates, and the vault chases them
  // separately; under one letter they read as what they are, which is one
  // question about the applicant's association.
  //
  // ⚠️ THE ENDORSEMENT IS NOT IN THIS GROUP. It is about the FIREARM, not the
  // membership — the association certifying that one specific rifle suits the
  // discipline — and the reference pack letters it separately for that reason.
  ASSOCIATION_CARD: {
    id: 'association',
    label: 'Association membership and good standing',
  },
  GOOD_STANDING_LETTER: {
    id: 'association',
    label: 'Association membership and good standing',
  },
};

/**
 * ⚠️ AN ANNEXURE IS A COPY OF A DOCUMENT THE APPLICANT POSSESSES. Nothing else.
 *
 * Operator, 2026-09-09: "only paperwork required by the dfo are attached as
 * annexures. all other things like the cartridge specs and clippings and those
 * things must be in the body of the document itself and form part of the flow,
 * it must not be just placed there because it has to be there."
 *
 * So the test is possession, not usefulness. A licence card, a competency
 * certificate, a farm letter and a CAS printout are paperwork the applicant
 * holds and a DFO asks to see the original of — they are annexures. Precinct
 * crime figures, press cuttings and a cartridge's dimensions are published
 * material WE assembled; there is no original for the applicant to produce and
 * no counter clerk will ask for one. They are argument, and argument belongs
 * in the body where it is being made.
 *
 * ⚠️ PRESS_CLIPPINGS AND PRIOR_NOTICE_REQUEST BOTH LEFT THIS LIST ON
 * 2026-09-09. The cuttings and the precinct tables now render inside the
 * exposure section they are evidence for. The PAJA letter was never an
 * annexure in the packs this product is modelled on either: it is its own
 * lodged document and sits between the motivation and the annexures
 * (MOTIVATION-GUIDE-BOOK Part 4.1).
 *
 * ⚠️ THE ORDER IS FIXED BY KIND AND THE LETTERS STAY CONTIGUOUS — a kind that
 * is absent takes no letter. A DFO who sees the same order on every pack finds
 * the competency in the same place every time, which is the whole point of
 * lettering them at all. This order is MOTIVATION-GUIDE-BOOK Part 9.1.
 */
const ANNEXURE_ORDER: AnnexureKind[] = [
  // A-D — who the applicant is, what they are qualified to hold, where they
  // live. Address matters twice over: the application is lodged at the DFO for
  // the area where the applicant ordinarily resides.
  'IDENTITY_DOCUMENT',
  'COMPETENCY_CERTIFICATE',
  'PROFICIENCY_CERTIFICATE',
  'ADDRESS_CONFIRMATION',
  // E — the safe. One letter, however many photographs are under it.
  'SAFE_PHOTOGRAPHS',
  // Retired, but still lettered, and still IN THE SAFE'S GROUP — a row written
  // before the collapse must not fall out of the printed index, and must not
  // take a letter of its own either.
  'SAFE_PHOTO_CLOSED',
  'SAFE_PHOTO_AJAR',
  'SAFE_PHOTO_BOLTS',
  'SAFE_PHOTO',
  'SAFE_INSTALLATION',
  // F — every firearm already licensed to the applicant. SAPS 271 item G.2
  // lists them all and a DFO matches each row against a card.
  'CURRENT_LICENCE',
  // G-I — the association. Membership, then good standing (the sworn statement
  // section 16(2) names), then the endorsement for this firearm by serial.
  'ASSOCIATION_CARD',
  'GOOD_STANDING_LETTER',
  'ASSOCIATION_ENDORSEMENT',
  // J — that the applicant actually does the thing: activity reports, verified
  // scores, hunting invitations, permits, club papers.
  'SHOOTING_ACTIVITY_LOG',
  // K — the applicant's OWN evidence of an incident. ⚠️ This is the one
  // crime-evidence item that stays an annexure, and possession is why: a CAS
  // printout or an armed-response report is paperwork the applicant holds and
  // can produce at the counter. The precinct figures and the press cuttings
  // beside it in the argument are ours, and they are in the body.
  'INCIDENT_REPORT',
  // M — where the firearm is coming from, and by what authority.
  'FIREARM_SOURCE_PROOF',
  /**
   * ⚠️ THE SELLER'S LICENCE IS NOT AN ANNEXURE, BECAUSE THE CONSENT PAGE
   * ALREADY CARRIES IT. Operator, 2026-09-10, wrote "Remove" across both
   * sheets of "Annexure H — The current owner's licence" on a rendered pack:
   * the consent the previous owner signs prints the front AND the back of that
   * same card above his signature, so the annexure was the same two images a
   * second time, four pages into a document somebody reads at a counter.
   *
   * ⚠️ THE UPLOAD IS NOT DELETED, ONLY UNLETTERED. It stays in the member's
   * vault and on the consent page; it simply stops printing twice.
   */
  // O — everything the applicant chose to add. ⚠️ EXECUTOR_APPOINTMENT is here
  // rather than gone: the estate route is retired and nothing asks for one, but
  // a row filed before it was retired must still letter rather than vanish.
  'EMPLOYMENT_CONFIRMATION',
  'CHARACTER_REFERENCE',
  'EXECUTOR_APPOINTMENT',
  'PREVIOUS_MOTIVATION',
  'OTHER',
  /**
   * ⚠️ LAST, AND THAT IS A PLACEMENT DECISION RATHER THAN AN ORDERING ONE.
   *
   * Every other annexure is an uploaded IMAGE, laid out by `planAnnexurePages`
   * two to a sheet. This one is a page we RENDER, so it cannot be interleaved
   * into that loop without teaching the planner about something that is not a
   * picture. Lettering it last and printing it last is the one arrangement
   * where the index and the pages cannot disagree — and an index a reviewer
   * cannot follow is worse than an annexure late in the sequence.
   */
  'SELLER_CONSENT',
] as const;

/**
 * WHICH COPIES A COMMISSIONER OF OATHS HAS TO STAMP.
 *
 * ⚠️ ONE OF THESE IS LAW AND THE REST ARE PRACTICE, AND THE DIFFERENCE
 * MATTERS. Regulation 13(4)(b) of the Firearms Control Regulations, 2004
 * requires a CERTIFIED copy of the identity document with an application by
 * an individual — that is the only one the instrument itself demands. Every
 * other 'expected' row below is what stations actually ask for when a copy
 * stands in for an original, and practice differs between them.
 *
 * We print the distinction rather than flattening it, because telling an
 * applicant that six documents are legally required to be certified when one
 * is would be the same kind of confident-sounding wrongness the whole
 * sa-firearms-law discipline exists to prevent — and because a person who
 * knows which single copy is non-negotiable can triage the queue at the
 * police station.
 *
 * 'none' is for documents that are ORIGINALS, not copies: a letter of good
 * standing signed by the association, an endorsement, photographs of a safe.
 * Nobody certifies a photograph of their own safe against an original
 * photograph, and a stamp block beside one would just be noise.
 */
export type CertificationLevel = 'required' | 'expected' | 'none';

export const CERTIFICATION: Record<AnnexureKind, CertificationLevel> = {
  // Ours, signed by the applicant in front of nobody in particular. Not a
  // copy of anything, so there is nothing to certify it against.


  // reg 13(4)(b) — the only one the Regulations themselves require.
  IDENTITY_DOCUMENT: 'required',

  // ⚠️ EXACTLY TWO MORE, AND THE FIRST VERSION OF THIS MAP HAD FIVE.
  //
  // I marked address confirmation, the association card and existing licences
  // as needing a stamp because they are copies of originals and it seemed to
  // follow. The operator's real reference pack settles it: the only annexures
  // marked "(Certified)" are the ID, the proficiency certificate and the
  // competency certificate. Address confirmation is filed uncertified.
  //
  // The difference is not cosmetic — it is three extra documents an applicant
  // would have queued at a police station for, on our say-so, because the
  // reasoning sounded right. Evidence from a pack that is actually filed beats
  // an inference every time.
  COMPETENCY_CERTIFICATE: 'expected',
  PROFICIENCY_CERTIFICATE: 'expected',

  // Filed as they are. Copies, but not ones anybody certifies in practice.
  //
  // ⚠️ ADDRESS CONFIRMATION WENT OUT, BACK IN, AND OUT AGAIN — and the last
  // move is the one with first-hand evidence behind it. I marked it
  // 'expected' by inference; dropped it because the operator's filed pack
  // marks only the ID and the two certificates "(Certified)"; put it back
  // when SAPS's live page turned out to say "Certified proof of residence".
  // Operator, 2026-08-21, asked directly: it needs a name, an address and a
  // date inside three months — certification did not come into it.
  //
  // Practice at the counter beats a line on a page. A stamp block printed
  // under a document nobody stamps is a box the applicant will go and try to
  // fill.
  ADDRESS_CONFIRMATION: 'none',
  CURRENT_LICENCE: 'none',
  ASSOCIATION_CARD: 'none',

  // Originals, signed by their author. Not copies of anything.
  GOOD_STANDING_LETTER: 'none',
  ASSOCIATION_ENDORSEMENT: 'none',
  EMPLOYMENT_CONFIRMATION: 'none',
  CHARACTER_REFERENCE: 'none',
  SHOOTING_ACTIVITY_LOG: 'none',
  INCIDENT_REPORT: 'none',
  PREVIOUS_MOTIVATION: 'none',

  // Where the firearm comes from. The dealer's invoice and the seller's
  // permission letter are originals; the seller's licence is their copy to
  // supply, and certifying somebody else's licence is not the applicant's to
  // arrange. The executor's letter of appointment is issued by the Master.
  FIREARM_SOURCE_PROOF: 'none',
  SELLER_LICENCE: 'none',
  /**
   * ⚠️ NO COMMISSIONER OF OATHS. It is already signed by the person whose
   * firearm it is, in front of the applicant, with his own licence reproduced
   * above the signature. Asking him to swear it as well is a second trip for
   * somebody who is not even the applicant.
   */
  SELLER_CONSENT: 'none',
  EXECUTOR_APPOINTMENT: 'none',

  // Photographs.
  SAFE_PHOTOGRAPHS: 'none',
  SAFE_PHOTO_CLOSED: 'none',
  SAFE_PHOTO_AJAR: 'none',
  SAFE_PHOTO_BOLTS: 'none',
  SAFE_PHOTO: 'none',
  SAFE_INSTALLATION: 'none',

  OTHER: 'none',
};

/**
 * Every upload kind, mapped to the annexure entry that letters it.
 *
 * ⚠️ A GROUPED KIND IS NOT ITS OWN ENTRY, AND LOOKING IT UP DIRECTLY RETURNS
 * NOTHING. buildAnnexures collapses the safe kinds onto one letter and the two
 * association documents onto another, so the returned list is keyed by each
 * group's REPRESENTATIVE kind. A caller that does
 * `entries.find(e => e.kind === upload.kind)` therefore finds the group's
 * representative and misses every other member of it.
 *
 * ⚠️ STILL NEEDED AFTER 2026-08-23. The safe is one kind now, but the
 * association group is not, and neither are the retired safe kinds a member's
 * older application still carries.
 *
 * That is not hypothetical: it shipped. A live pack printed
 * "Annexure ? — SAFE_PHOTO_AJAR" and "Annexure ? — GOOD_STANDING_LETTER" as
 * captions on the reprinted copies, with the raw enum name showing, because
 * the map was built from the entry list and read by member kind.
 *
 * Use this rather than building a map by hand.
 */
export function annexureByKind(
  entries: AnnexureEntry[],
): Map<MotivationUploadKind, AnnexureEntry> {
  const out = new Map<MotivationUploadKind, AnnexureEntry>();
  for (const entry of entries) {
    if (entry.generated) continue;
    const kind = entry.kind as MotivationUploadKind;
    const group = LETTER_GROUPS[kind];
    if (!group) {
      out.set(kind, entry);
      continue;
    }
    // Every member of the group answers to the group's entry.
    for (const k of Object.keys(LETTER_GROUPS) as MotivationUploadKind[]) {
      if (LETTER_GROUPS[k]?.id === group.id) out.set(k, entry);
    }
  }
  return out;
}

export interface AnnexureEntry {
  letter: string;
  kind: AnnexureKind;
  label: string;
  count: number;
  /** Whether this annexure needs a commissioner's stamp, and how firmly. */
  certification: CertificationLevel;
  /** True for documents we produce rather than ones the applicant uploaded. */
  generated?: true;
}

/**
 * Assign annexure letters to what was actually uploaded.
 *
 * Letters go to KINDS, not files, so two copies of one ID share a letter — and
 * since 2026-08-23 so do every photograph of the safe, which is one kind. The
 * copies stay individually citable through the "(2 of 4)" captions
 * motivation-annexure-layout.ts prints above each one.
 */
/**
 * Second-person labels rewritten for a first-person document.
 *
 * ⚠️ THE ANNEXURE INDEX IS NOT THE MEMBER'S SCREEN. "Photographs of your safe"
 * is exactly right on the document shelf, where the product is talking to the
 * member. Inside the motivation it becomes "Refer to Annexure E: Photographs
 * of your safe" — a first-person letter to the Registrar suddenly addressing
 * the reader about THEIR safe. Same for "Copy of your ID" and "Your letter of
 * good standing".
 *
 * ⚠️ AN OVERRIDE MAP RATHER THAN A REWRITE OF UPLOAD_KIND_LABELS, because the
 * shelf, the checklist and the picker all read that table and all of them are
 * addressed to the member. Only the annexure index changes register.
 */
const ANNEXURE_TITLES: Partial<Record<MotivationUploadKind, string>> = {
  IDENTITY_DOCUMENT: 'Copy of the applicant’s identity document',
  GOOD_STANDING_LETTER: 'Letter of good standing',
  SAFE_PHOTOGRAPHS: 'Photographs of the safe',
  SAFE_PHOTO: 'Photographs of the safe (earlier upload)',
  SHOOTING_ACTIVITY_LOG: 'Record of shooting activities',
};

/** How an annexure is titled inside the document itself. */
export function annexureTitle(kind: MotivationUploadKind): string {
  return ANNEXURE_TITLES[kind] ?? UPLOAD_KIND_LABELS[kind];
}

export function buildAnnexures(
  kinds: MotivationUploadKind[],
  /**
   * Documents we generate that are ready to go into this pack.
   *
   * Passed in rather than assumed, because a pack whose motivation has not
   * been written yet has no prior-notice request either — and lettering a
   * document that does not exist would put a gap in the index a reviewer
   * would go looking for.
   */
  generated: GeneratedAnnexureId[] = [],
): AnnexureEntry[] {
  const counts = new Map<MotivationUploadKind, number>();
  for (const k of kinds) counts.set(k, (counts.get(k) ?? 0) + 1);
  const made = new Set(generated);

  const out: AnnexureEntry[] = [];
  let i = 0;
  /** Letters already spent, so a grouped kind reuses its group's letter. */
  const groupLetter = new Map<string, string>();

  for (const kind of ANNEXURE_ORDER) {
    const isGenerated = kind in GENERATED_ANNEXURE_LABELS;
    if (isGenerated) {
      if (!made.has(kind as GeneratedAnnexureId)) continue;
      out.push({
        letter: String.fromCharCode(65 + i),
        kind,
        label: GENERATED_ANNEXURE_LABELS[kind as GeneratedAnnexureId],
        count: 1,
        certification: CERTIFICATION[kind] ?? 'none',
        generated: true,
      });
      i++;
      continue;
    }
    const uploadKind = kind as MotivationUploadKind;
    const count = counts.get(uploadKind);
    if (!count) continue;

    const group = LETTER_GROUPS[uploadKind];
    if (group) {
      const existing = groupLetter.get(group.id);
      if (existing) {
        // Same letter, one more document under it. The entry's count is what
        // drives "(2 of 4)" on the printed copy, so it has to accumulate.
        const row = out.find((e) => e.letter === existing);
        if (row) row.count += count;
        continue;
      }
      const letter = String.fromCharCode(65 + i);
      groupLetter.set(group.id, letter);
      out.push({
        letter,
        kind: uploadKind,
        // The safe group's own label is second person too — it IS
        // "Photographs of your safe" — so the same override applies.
        label: annexureTitle(uploadKind) ?? group.label,
        count,
        certification: CERTIFICATION[uploadKind] ?? 'none',
      });
      i++;
      continue;
    }

    out.push({
      letter: String.fromCharCode(65 + i),
      kind: uploadKind,
      // ⚠️ THE DOCUMENT'S OWN REGISTER, NOT THE SHELF'S. See annexureTitle:
      // "Refer to Annexure E: Photographs of your safe" has a first-person
      // letter to the Registrar addressing the reader about their safe.
      label: annexureTitle(uploadKind),
      count,
      certification: CERTIFICATION[uploadKind] ?? 'none',
    });
    i++;
  }
  return out;
}

/** Uploads that materially strengthen each licence type. */
const RECOMMENDED: Record<MotivationLicenceType, MotivationUploadKind[]> = {
  // Section 14 asks everything section 13 asks and two things more; the
  // paperwork is the same paperwork.
  S14_RESTRICTED_SELF_DEFENCE: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'SAFE_PHOTOGRAPHS',
    'INCIDENT_REPORT',
    'FIREARM_SOURCE_PROOF',
  ],
  S13_SELF_DEFENCE: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'SAFE_PHOTOGRAPHS',
    'INCIDENT_REPORT',
    // \u26a0\ufe0f WHERE THE FIREARM IS COMING FROM, ON EVERY LICENCE TYPE. This was
    // missing entirely and it is annexure M in the operator's reference pack.
    // A DFO cannot process an application for a firearm whose provenance is
    // unstated \u2014 either it is coming out of a dealer's stock, or a named
    // licence holder has agreed to transfer it. Nothing else is possible.
    'FIREARM_SOURCE_PROOF',
  ],
  S15_OCCASIONAL_HUNTER: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'PROFICIENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'SAFE_PHOTOGRAPHS',
    'CURRENT_LICENCE',
    'FIREARM_SOURCE_PROOF',
    // The evidence that they hunt, rather than the assertion that they do.
    'SHOOTING_ACTIVITY_LOG',
  ],
  S16_DEDICATED_HUNTER: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'PROFICIENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'ASSOCIATION_CARD',
    'GOOD_STANDING_LETTER',
    'ASSOCIATION_ENDORSEMENT',
    'SAFE_PHOTOGRAPHS',
    'CURRENT_LICENCE',
    'FIREARM_SOURCE_PROOF',
    'SHOOTING_ACTIVITY_LOG',
  ],
  S16_DEDICATED_SPORT: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'PROFICIENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'ASSOCIATION_CARD',
    // \u26a0\ufe0f THE ONE SECTION 16(2) ACTUALLY NAMES, and it was not on this list
    // for either section 16 type. The Act requires "a sworn statement or
    // solemn declaration from the chairperson of an accredited hunting
    // association or sports-shooting organisation ... stating that the
    // applicant is a registered member" \u2014 so a section 16 pack without it is
    // missing the document the section is built on, and the checklist was
    // quietly not asking for it.
    'GOOD_STANDING_LETTER',
    'ASSOCIATION_ENDORSEMENT',
    'SAFE_PHOTOGRAPHS',
    'CURRENT_LICENCE',
    'FIREARM_SOURCE_PROOF',
    'SHOOTING_ACTIVITY_LOG',
  ],
  // \u26a0\ufe0f A RENEWAL HAS NO SOURCE DOCUMENT. The applicant already holds the
  // firearm \u2014 asking where it is coming from would be asking them to prove a
  // transfer that is not happening.
  S24_RENEWAL: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'SAFE_PHOTOGRAPHS',
    'CURRENT_LICENCE',
  ],
};

/**
 * What the applicant must bring themselves — from the operator's own list.
 *
 * ⚠️ Items marked verifyBeforeUse carry a number or a form reference that can
 * go stale without notice. Confirm before the flag is flipped.
 */
const APPLICANT_MUST_BRING: Omit<ChecklistItem, 'done' | 'owner' | 'state' | 'closer'>[] = [
  {
    key: 'saps_form',
    label: 'The SAPS application form for this licence',
    // ⚠️ THE REAL NOTE IS COMPUTED PER APPLICATION, NOT HERE — see
    // saps271FormNote below, applied in buildChecklist where the licence type
    // and firearm_source are both in hand. Which form it even is (271 or
    // 518(a)) and which half of it is somebody else's to fill depend on both,
    // and a static sentence here would go stale the moment either changed.
    // This default is only what shows if buildChecklist is ever called
    // without a licence type reaching this far, which should not happen.
    note: 'Do NOT sign it beforehand — it must be signed in front of the DFO.',
    verifyBeforeUse: true,
  },
  {
    /**
     * Part 10.1 item 1. It is first because it is the only row that is about
     * the pack itself rather than about something to carry, and because two of
     * its three instructions are things that cannot be fixed at the counter.
     *
     * ⚠️ SINGLE-SIDED, AND THE FORM UNSIGNED ON TOP. A double-sided pack
     * has to be taken apart to certify or stamp a page, and a SAPS form signed
     * at home is a form signed out of the DFO's sight, which is the one thing
     * regulation 13 does not allow.
     */
    key: 'printed_pack',
    label: 'The pack itself, printed single-sided',
    note: 'Print it single-sided — pages get certified, stamped and copied at the counter. The SAPS form goes on top, UNSIGNED. Sign the motivation and the PAJA letter at home, after reading them, and initial every page of the motivation in the space at the foot — that is what stops a page being swapped after you signed.',
  },
  {
    key: 'id_copies',
    // ⚠️ THE ONE CERTIFICATION THE REGULATIONS ACTUALLY IMPOSE on an
    // individual applicant: regulation 13(4)(b) requires a certified copy of
    // the identity document. Everything else on this list is certified at the
    // counter against the original, or not at all — which is why this entry
    // says "certified" and the others no longer do.
    label: 'A certified copy of your ID (the page with your photograph)',
    note: 'This is the one copy the regulations require to be certified. Any police station or Commissioner of Oaths does it free. Bring the original as well — most DFOs certify the rest of your copies against the originals at the counter.',
  },
  {
    // ⚠️ SETTLED BY THE OPERATOR, AGAINST THE SAPS PAGE. I moved this row to
    // "get it certified" because SAPS's live list reads "Certified proof of
    // residence". Operator, 2026-08-21: "The proof of address just needs to
    // have your name on it, not older than three months and obviously your
    // address."
    //
    // That is two pieces of first-hand evidence — what they are told at the
    // counter, and their own filed pack, which carries this one uncertified —
    // against one line on a web page. The three THINGS IT MUST CONTAIN are
    // what actually gets people sent home, and they were not stated anywhere
    // before: a bill in a spouse's name is the common failure.
    //
    // The SAPS wording is left in the note rather than deleted, because it is
    // still what their page says and a station that follows it is not wrong.
    key: 'proof_of_residence',
    label: 'Proof of your residential address, not older than 3 months',
    note: 'It has to carry your NAME, your ADDRESS, and a date inside the last three months. A municipal bill or a bank letter is the cleanest choice — a lease or a rental statement proves the address too, and also shows what you pay and anything outstanding, and the whole page goes into your pack. A bill in your spouse’s or your landlord’s name does not prove your address. No certification needed. (SAPS’s website does say "certified proof of residence"; certifying is free at any police station if your DFO asks for it.) This is also what settles which DFO your application goes to: the one for the area where you ordinarily live.',
  },
  {
    // ⚠️ "TWO" WAS OURS, NOT SAPS'S, AND SO WAS THE TWO-YEAR RULE. Neither
    // SAPS list for a NEW licence mentions references at all. Two testimonials
    // appear only on the SAPS 517(g) competency RENEWAL, which is a different
    // application, and regulation 23(3)(c)'s "two written testimonials" is for
    // a non-resident seeking a temporary authorisation. No two-year threshold
    // exists in the Act, in the Regulations, or on any SAPS page.
    //
    // What the Regulations DO prescribe is the CONTENT: regulation 13(7)
    // requires a person recommending an applicant's character to state that
    // they are a fit and proper person, of stable mental condition and not
    // inclined to violence, and not dependent on any intoxicating or narcotic
    // substance. That is worth far more to an applicant than an invented
    // number, because it is what their referee has to actually write.
    key: 'character_references',
    label: 'Character references, if you have them',
    note: 'Not on SAPS’s list for a new licence, but a strong pack usually carries one or two. Regulation 13(7) says anyone who recommends your character must also state that you are a fit and proper person, of stable mental condition and not inclined to violence, and not dependent on any intoxicating or narcotic substance — so give whoever writes yours those three points.',
  },
  {
    // ⚠️ THERE IS NO SAPS 541. This row named one for months and told the
    // applicant to ask their DFO which form they use. The SAPS forms index
    // runs 517 to 540 with no 541 in it, and forms/english/e541.pdf returns
    // 404 while e539.pdf returns 200. We were sending people to a counter to
    // ask for a form that does not exist.
    //
    // What actually happens, per SAPS's own application page, is not
    // paperwork at all: the DFO asks you to install a safe within 14 days of
    // applying, then INSPECTS YOUR PREMISES, and no licence issues until that
    // report is in.
    //
    // ⚠️ THE NOTE SAYS "NO LICENCE IS ISSUED UNTIL", NOT "THE LICENCE
    // FOLLOWS". The first draft used SAPS's own phrase, "the licence follows
    // the successful inspection report", and the outcome-language test caught
    // it on the word "successful" — correctly. Read by an applicant it says
    // pass the inspection and the licence comes, which is a promise about an
    // outcome we do not control. Stating the gate is true; stating what
    // follows it is not ours to say.
    //
    // Careful drafting note: do NOT write that the Regulations contain no
    // safe-storage declaration. Regulations 20(1)(b), 23(1)(b) and 33(1)(b)
    // do prescribe written safe-custody declarations — for section 21
    // temporary authorisations and dealer temporary trading, not for a
    // section 13/15/16/24 licence. Hence "there is no form for this", scoped
    // to this application.
    key: 'safe_inspection',
    label:
      'A safe that meets the SABS standard, and a premises inspection by your DFO',
    note: 'There is no form for this. Regulation 86 requires a safe built to SABS 953-1 or 953-2, and regulation 13(12) lets the Registrar issue your licence only once you comply. SAPS says the DFO asks you to install the safe within 14 days of applying and then inspects your premises, and no licence is issued until that inspection report is in. Some stations use a local undertaking of their own — ask yours which they do.',
    verifyBeforeUse: true,
  },
  {
    key: 'safe_invoice',
    label: 'The invoice or receipt for your safe',
  },
  {
    key: 'tax_invoice',
    label: "The dealer's tax invoice for the firearm",
    note: 'Proof of purchase. If you bought it on All Outdoor, your invoice is in your orders.',
  },
  {
    // ⚠️ SAPS ASKS FOR THE ORIGINAL, AND WE SAID "A COPY". Their licence-stage
    // list reads "Your original competency certificate" — an applicant who
    // brings only a photocopy is sent home.
    //
    // This is also where the TWO-STAGE structure belongs. Competency is a
    // separate, EARLIER application to the same DFO with its own training,
    // its own form, its own fingerprints, its own fee and a wait measured in
    // months, and section 6(2) means no licence can be issued until it has
    // been granted. The row had no note at all, so a first-time applicant had
    // nowhere to learn that.
    key: 'competency_copy',
    label:
      'Your SAPS competency card or printout — the original, plus a copy',
    note: 'SAPS’s own list asks for your original competency certificate, so take it — the plastic card or the CFR printout, whichever you were issued; a club checklist from a real submitted pack names both. The copy in your pack is what gets certified against it at the counter. If you have not applied for competency yet, that is a separate, earlier application with its own training, fingerprints, fee and waiting period — section 6(2) means no licence can be issued until it has been granted.',
  },
  {
    /**
     * Part 10.1 item 4. Separate from the competency row above because they
     * are two different documents from two different steps: the proficiency
     * Statement of Results comes from the training provider and proves the
     * unit standards, and the competency certificate comes from SAPS on the
     * strength of it. An applicant who brings one and not the other is sent
     * home, and "your competency papers" is what makes that happen.
     */
    key: 'proficiency_copy',
    label: 'Your proficiency Statement of Results — the original, plus a copy',
    note: 'The training provider’s Statement of Results for the unit standards you passed, for the type of firearm you are applying for. The copy in your pack is certified against it at the counter. It is a different document from your SAPS competency certificate and the DFO wants both.',
  },
  {
    key: 'passport_photos',
    label: 'Two passport photographs',
    // ⚠️ FOUR QUALIFIERS, AND WE WERE STATING TWO. SAPS's own application
    // guidance asks for "two unobscured passport-size colour photographs (with
    // a neutral background) that are not older than three months" — at the
    // competency stage and again at the licence stage.
    //
    // The one that catches people is the AGE. Nobody expects a photograph to
    // expire, so the drawer photos from the last application come along, and
    // the applicant finds out at the counter. "Unobscured" is the other:
    // glasses, a hat, a fringe over an eyebrow.
    //
    // PLAIN vs NEUTRAL: the SAPS 271 form says plain, the website says
    // neutral. Both rule out a patterned or busy background and neither says
    // white, so the note says what they agree on rather than picking one.
    note: 'Two, in colour, taken in the last three months, against a plain, neutral background, with your face unobscured — no hat, no sunglasses, nothing across your face. The age is the one that catches people: photographs from your last application will be sent back.',
  },
  {
    key: 'fee',
    label: 'The application fee, per firearm',
    // The AMOUNT changes and is marked for checking; the SEQUENCE does not,
    // and knowing it stops a wasted queue.
    // The AMOUNTS are SAPS's own published figures and stay marked for
    // checking; the SEQUENCE does not change, and knowing it stops a wasted
    // queue. Reg 13(6) requires documentary proof of payment to be attached
    // where the fee was paid at a police station under reg 96.
    //
    // "Per firearm, not per application" appears in neither instrument and on
    // no SAPS page. It is the operator's, and they confirmed it directly on
    // 2026-08-21 when asked: R175 is per firearm. Stated plainly on that
    // basis; the AMOUNT still carries verifyBeforeUse, because published fees
    // are the thing on this list most likely to go quietly out of date.
    note: 'Per firearm, not per application. SAPS currently publishes R175 for a firearm licence and R88 for a competency certificate. The DFO gives you a remittance advice (SAPS 523a), you pay at the station’s own finance office — cash or a bank-guaranteed cheque, not every station takes cards — and the Z263 receipt goes back to the DFO to be attached. Confirm the amount before you go.',
    verifyBeforeUse: true,
  },
  {
    key: 'originals',
    label: 'All your original documents',
    // "Keep the originals; hand over copies" read as a universal rule and
    // contradicted the row above it, where SAPS asks for the original
    // competency certificate by name. Do NOT assert that SAPS retains it:
    // sections 6(2), 10(2), 11(1) and 145(2)(h) all point the other way and
    // nothing in either instrument provides for surrendering it.
    note: 'ID, competency, existing licences, certificates — the DFO checks your copies against them. SAPS’s list singles out your original competency certificate, so that is the one not to leave at home. Ask the DFO what they keep and what you take back.',
  },
  {
    key: 'own_copy',
    label: 'A copy of the whole application, for yourself',
    note: 'You will want it if anything has to be followed up later.',
  },
  {
    key: 'acknowledgement',
    // ⚠️ "DO NOT LEAVE THE STATION WITHOUT IT" WAS BAD ADVICE, and it came
    // from reading regulation 13(10) without knowing what the counter does.
    // Operator, 2026-08-21, from having lodged these: "the SAPS 523 is filled
    // in by the DFO so we won't get it."
    //
    // So the sheet is theirs, not the applicant's, and an applicant told to
    // refuse to leave without a document the officer keeps is an applicant
    // sent to argue with the person deciding their application. The need
    // underneath it is real — proof of WHEN you lodged, which regulation
    // 13(13) makes matter on a renewal — so the row now asks for the thing
    // rather than for the form.
    label: 'Before you leave: proof of the date you lodged',
    note: 'The acknowledgement of receipt (SAPS 523) is completed by the DFO and usually stays with them, so do not expect to walk out holding it. What you want is the record: ask for your reference number and the date your application was received, and write down which officer took it. On a renewal that date is the one that matters.',
    verifyBeforeUse: true,
  },
  {
    key: 'dfo_extras',
    label: 'Anything else your DFO asks for',
    note: 'Requirements differ between stations and provinces. Phone ahead — it is the cheapest thing you can do.',
  },
];

/**
 * WHAT THE ROUTE ADDS — dealer or private sale.
 *
 * MOTIVATION-GUIDE-BOOK Part 10.2. These are the documents that belong to
 * somebody ELSE and travel with the applicant, which is why they are the ones
 * most often missing: the applicant has done everything on their own list and
 * the counter turns them away over a page the seller was supposed to sign.
 *
 * ⚠️ THE ESTATE ROUTE IS DELIBERATELY ABSENT. Operator, 2026-09-09: apply
 * the whole book "apart from the estate". An inherited firearm needs the
 * executor's papers and a section F completed as type E, and none of that is
 * built — offering half of it would send somebody to a counter with a pack
 * that cannot be accepted.
 */
const ROUTE_MUST_BRING: Record<
  string,
  Omit<ChecklistItem, 'done' | 'owner' | 'state' | 'closer'>[]
> = {
  [SOURCE_DEALER]: [
    {
      key: 'dealer_350a',
      label: "The dealer's SAPS 350(a) stock return, stamped",
      note: 'Your dealer completes it and stamps it, together with sections E and F of the SAPS 271 — that half of the form is theirs, not yours. Bring their invoice with it. The firearm stays with the dealer until the licence is issued; do not take it home.',
      verifyBeforeUse: true,
    },
  ],
  [SOURCE_PRIVATE]: [
    {
      key: 'seller_papers',
      label: "The seller's papers: consent, licence and ID",
      // ⚠️ BOTH SIDES OF THE LICENCE. The back carries the endorsement and
      // the expiry, and a copy of the front alone is the commonest reason a
      // private-sale pack goes back over the counter.
      note: 'The consent your seller signed is in your pack. Take copies of BOTH SIDES of their licence for this firearm and of their identity document, and make sure they have completed their half of section F on the SAPS 271. The firearm stays with the seller until your licence is issued.',
    },
  ],
};

/**
 * WHAT THE SECTION ADDS, for the types that have no list of their own above.
 *
 * MOTIVATION-GUIDE-BOOK Part 10.3. Section 13 asks for no extra paperwork at
 * all — what it asks for is that the applicant can ANSWER, which is a
 * different kind of preparation and one nothing else on the sheet covers.
 */
const SECTION_MUST_BRING: Partial<
  Record<
    MotivationLicenceType,
    Omit<ChecklistItem, 'done' | 'owner' | 'state' | 'closer'>[]
  >
> = {
  S13_SELF_DEFENCE: [
    {
      key: 's13_be_ready_to_answer',
      label: 'Be ready to answer questions about where you live and work',
      note: 'No extra paperwork. But the DFO may go through section K of the form with you even though it is written for section 14 — how far you are from the nearest police station and from your nearest neighbours, whether your area is crime-rated, and what your daily routine is. Know those answers before you get to the counter; they are in your motivation.',
    },
  ],
  S14_RESTRICTED_SELF_DEFENCE: [
    {
      key: 's14_section_k',
      label: 'Expect section K to be completed with you',
      note: 'Section K of the SAPS 271 is filled in for a section 14 and for no other section: urban, rural, farm or smallholding; the distance in kilometres to your nearest neighbour and to your nearest police station; whether the area is crime-rated; whether your home or your work is high-risk; and how many firearms you hold. Every one of those is in your motivation — read it before you go.',
    },
    {
      key: 's14_premises_visit',
      label: 'Expect the DFO to come and look at the premises',
      note: 'A section 14 application is about a place as much as a person. Expect an inspection of the property and of the safe, and expect it to be arranged rather than announced.',
    },
  ],
  S15_OCCASIONAL_HUNTER: [
    {
      key: 's15_papers',
      label: 'Your hunting or shooting papers',
      note: 'Whatever you have that shows you actually hunt or shoot: the farm letter or invitation, past permits, club membership and shoot results. If you belong to an accredited association, bring the membership card as well — and note that your motivation describes you as a MEMBER and never claims dedicated status, which is what section 15 requires.',
    },
  ],
};

/**
 * What a section 16 applicant must bring ON TOP of the common list.
 *
 * Section 16 is the one type where a third party — the accredited association
 * — has to have signed something, and the pack is not a pack without it.
 */
const S16_MUST_BRING: Omit<ChecklistItem, 'done' | 'owner' | 'state' | 'closer'>[] = [
  {
    key: 's16_good_standing',
    label: "Your association's letter of good standing",
    // ⚠️ THE ONE THE ACT ACTUALLY NAMES. Section 16(2) requires a sworn
    // statement or solemn declaration from the chairperson of the accredited
    // association, or their written delegate, that the applicant is a
    // registered member.
    note: 'Section 16 asks for a sworn declaration from your association that you are a registered member in good standing. Check the validity dates before you go — an expired letter sends you home.',
  },
  {
    key: 's16_status',
    label: 'Your dedicated hunter or dedicated sport shooter certificate',
    note: 'The certificate with your dedicated number on it. Bring the original as well as the copy.',
  },
  {
    /**
     * Part 10.3. Not a document the DFO asks for by name — it is what the
     * ASSOCIATION asks for before it will endorse anything, and an applicant
     * whose report is outstanding finds that out when the endorsement is
     * refused, weeks after they thought the pack was ready.
     */
    key: 's16_activity_report',
    label: 'Your annual activity report to the association',
    note: 'Submit it before you ask for the endorsement. An association will not endorse a firearm for a member whose activity reporting is behind, and the DFO may ask to see the latest one.',
  },
  {
    key: 's16_endorsement',
    label: "Your association's endorsement for this firearm",
    // ⚠️ NOT IN THE ACT — it comes from the Hunters Forum guidelines of
    // 2 September 2005. It is on this list because a DFO will ask for it, and
    // that is a different reason from the law requiring it. The note says
    // which, because a member who is told the law demands something will
    // repeat that to the DFO.
    note: 'It names the exact firearm — type, calibre, make, action and serial. The Act does not list it, but a DFO will ask for it, so do not travel without it.',
  },
];

/**
 * WHAT ONLY A RENEWAL NEEDS.
 *
 * ⚠️ THE 90-DAY DEADLINE REACHED THE APPLICANT NOWHERE. The Licence Centre
 * knows the number — licence-dates.ts sets EXPIRING_WITHIN_DAYS = 90 and
 * cites section 24(1) for it — but a person who came straight to a renewal
 * motivation without ever opening the vault was never told, and buildChecklist
 * had no S24 branch at all. We collect the expiry date and then said nothing
 * about the one date that governs it.
 *
 * ⚠️ NEVER STATE A CONSEQUENCE FOR LATENESS. Say what protection is lost,
 * not what happens: sections 24 and 28 are amendment-sensitive and are the
 * subject of a suspended declaration of unconstitutionality pending
 * confirmation. "Lodged in time and the licence stays valid while SAPS
 * decides" is a statement about section 24(4). Anything about what befalls a
 * lapsed licence is not ours to make.
 *
 * ⚠️ DO NOT IMPORT THE CONSTANT FROM licence-centre.
 * licence-centre.module.spec.ts asserts the dependency runs one way only.
 */
const S24_MUST_BRING: Omit<ChecklistItem, 'done' | 'owner' | 'state' | 'closer'>[] = [
  {
    // Part 10.3. The obvious one, and the one nothing on the sheet said: a
    // renewal is a renewal OF something, and the DFO checks the original.
    key: 's24_original_licence',
    label: 'The original licence you are renewing',
    note: 'Bring the licence itself — the card or the certificate, front and back — not only the copy in your pack. The DFO checks the copy against it.',
  },
  {
    key: 's24_ninety_days',
    label: 'Lodge at least 90 days before the expiry date',
    note: 'SAPS asks for the renewal application at least 90 days before your licence expires, and a licence lodged in time stays valid until the application is decided. If you are already inside 90 days, lodge as soon as your pack is ready — the SAPS 518(a) asks you to give the reason in writing. Confirm the timing with your DFO.',
    verifyBeforeUse: true,
  },
  {
    // Same correction as the acknowledgement row above: the applicant does not
    // get to keep the 523, so "keep it somewhere safe" was advice about a
    // document they will never hold. Regulation 13(13) still makes the date
    // the thing that matters — so record it.
    key: 's24_keep_acknowledgement',
    label: 'Write down the date your renewal was received',
    note: 'Regulation 13(13) makes the acknowledgement of receipt, on production in court, sufficient proof that you complied with section 24 — but the DFO completes and keeps that sheet. Ask for your reference number and the date it was received, and keep your own note of both.',
    verifyBeforeUse: true,
  },
];

/**
 * THE SECOND FORM, FOR THE APPLICANTS WHO ACTUALLY NEED IT.
 *
 * ⚠️ CONDITIONAL, AND THAT IS THE WHOLE VALUE OF IT. A competency has no
 * lifespan of its own — s10(2) as amended ties it to the latest-dated licence
 * in its firearm category — so renewing an ordinary licence usually changes
 * nothing about it. But when the licence being renewed is the LAST one in that
 * category the competency expires on the same day, and s10A(1) requires the
 * competency renewal to be lodged TOGETHER WITH the licence renewal. Miss it
 * and the licence renewal can be accepted while the competency behind it
 * lapses, and the whole chain has to be rebuilt.
 *
 * ⚠️ SO IT MUST NOT APPEAR FOR EVERYONE. "You may also need a 517(g)" hedged
 * onto every renewal is noise, and noise is what trains somebody to skim the
 * one row that mattered. The finding is made in the Licence Centre, where the
 * member's own licences and certificates are — competencyRenewalNote owns the
 * rule and is silent unless it is sure of both halves — and arrives here as a
 * single answer. See COMPETENCY_RENEWS_KEY.
 *
 * ⚠️ THE ROW SAYS WHAT TO DO, NOT WHAT WE WORKED OUT. The member is not shown
 * arithmetic about their portfolio at a counter; they are shown the form to
 * bring. The Licence Centre's card carries the reasoning.
 */
const S24_COMPETENCY_RENEWAL: Omit<
  ChecklistItem,
  'done' | 'owner' | 'state' | 'closer'
> = {
  // ⚠️ NEVER RENAME. Hand-ticks are stored against this key.
  key: 's24_competency_517g',
  label: 'SAPS 517(g) competency renewal',
  note: 'Your competency in this category runs to this licence, so lodge its renewal together with this one. They are two separate forms with two separate fees, handed in on the same visit. Confirm the form number with your DFO.',
  verifyBeforeUse: true,
};

/**
 * The renewal rows, with the 517(g) in place if this applicant needs it.
 *
 * ⚠️ INSERTED BY ANCHOR KEY, NOT BY POSITION. It belongs directly after the
 * 90-day row — both are about what you lodge and when, while the
 * acknowledgement row is about what happens afterwards — and destructuring
 * S24_MUST_BRING by index would reorder itself silently the day a third row is
 * added there. If the anchor ever goes, the row still lands (at the end)
 * rather than disappearing: a slightly misplaced instruction beats a missing
 * one when the thing being missed is a lapsing competency.
 */
function s24Bring(
  answers: Record<string, string>,
): Omit<ChecklistItem, 'done' | 'owner' | 'state' | 'closer'>[] {
  // ⚠️ CASE-INSENSITIVE, DELIBERATELY. The registry's `yesno` fields store
  // 'Yes'; the value is written by another module and read by this one, and a
  // capital letter is not a thing anybody should be able to break a
  // counter-day instruction with. Anything that is not a yes is silence —
  // absent and "no" are the same answer here, because the finding is only
  // ever written when we are sure of it.
  const due = (answers[COMPETENCY_RENEWS_KEY] ?? '').trim().toLowerCase() === 'yes';
  if (!due) return [...S24_MUST_BRING];

  const out: Omit<ChecklistItem, 'done' | 'owner' | 'state' | 'closer'>[] = [];
  let placed = false;
  for (const row of S24_MUST_BRING) {
    out.push(row);
    if (row.key === 's24_ninety_days') {
      out.push(S24_COMPETENCY_RENEWAL);
      placed = true;
    }
  }
  if (!placed) out.push(S24_COMPETENCY_RENEWAL);
  return out;
}

/**
 * The one line telling the applicant who fills in the SAPS form, and how
 * much of it is theirs.
 *
 * ⚠️ NOT ALWAYS THE 271. A section 24 renewal is lodged on the SAPS 518(a) —
 * motivation-render.service.ts refuses to produce a 271 for one, by licence
 * type, and this product does not fill the 518(a) in at all (out of scope,
 * brief §9.4). A renewal's row must say so rather than describe a pre-filled
 * section this pack never produces.
 *
 * ⚠️ EVERY OTHER LICENCE TYPE'S 271 STOPPED BEING AN OPT-IN EXTRA ON
 * 2026-09-08 (brief §2.5, `MOTIVATION-INTAKE-PLAN.md` §1). We now complete
 * sections D, G and H unconditionally; section F is filled, ticked or left
 * blank by `firearm_source` alone (saps271.service.ts draws it,
 * saps271-map.ts decides it) — never by a choice made on this checklist. This
 * function only puts that outcome into plain words for the applicant in
 * front of them, and it must never claim more than the map actually draws:
 * see saps271-map.ts's own section-F comments before changing either route's
 * wording here.
 */
function saps271FormNote(
  licenceType: MotivationLicenceType,
  answers: Record<string, string>,
): string {
  if (licenceType === MotivationLicenceType.S24_RENEWAL) {
    return 'A renewal is lodged on the SAPS 518(a), not the 271 — get it from your DFO. Do NOT sign it beforehand — it must be signed in front of the DFO.';
  }

  const base =
    'We fill in your half of the SAPS 271 application form — sections D, G and H — from your answers and documents, and it is in your pack. Do NOT sign it beforehand — it must be signed in front of the DFO.';

  const source = (answers[FIREARM_SOURCE_KEY] ?? '').trim();
  if (source === SOURCE_DEALER) {
    // ⚠️ NAMES WHO FILLS THE REST, RATHER THAN LEAVING AN UNEXPLAINED GAP.
    // saps271-map.ts leaves section F blank on this route on purpose —
    // operator, 2026-08-28: "F. Type B and SAP 350 can be left alone, a
    // dealer needs to fill in those" — and the form itself carries the same
    // explanation as a `leftBlank` entry. Said again here so the applicant
    // knows before they get to the counter, not at it.
    return `${base} Section F is left blank for your dealer — they complete it along with their own SAPS 350(a); that half is theirs, not yours.`;
  }
  if (source === SOURCE_PRIVATE) {
    // ⚠️ NOT A PROMISE THAT F IS ALREADY DONE. It is filled once the seller
    // has actually completed and signed his consent (sectionF() in
    // motivation-seller-consent.service.ts returns nothing before that), so
    // this only says what the finished route looks like, not that it has
    // finished — the coverage panel's own 'F' row carries the live status.
    return `${base} Section F — the current owner's half — is filled from your seller's signed consent and printed as the page he signs.`;
  }
  // Unstated, or the estate route (which the 271 does not process at all —
  // see the "Type A and B only" ruling in saps271-map.ts): say only what is
  // certain, which is our own half.
  return base;
}

/**
 * Build the live checklist.
 *
 * `haveKinds` is what has actually been uploaded and `documentReady` whether the
 * motivation has passed the quality gate, so the "ours" items reflect real
 * state rather than intent.
 *
 * ⚠️ ONE ENTRY PER FILE, NOT A SET. The safe is one row holding several
 * photographs since 2026-08-23, so it is ticked by COUNT — and both callers
 * already pass a per-upload list. Deduplicating here would tick the safe row on
 * the first photograph, which is the failure the three separate kinds existed
 * to prevent.
 */
/**
 * Rows that only apply on some routes.
 *
 * ⚠️ THE LIST WENT TO EVERY APPLICANT WHATEVER THEY ANSWERED. MO000071 was a
 * private-owner purchase and its take-to-the-station pages told the applicant
 * to bring "the dealer's tax invoice for the firearm" — there is no dealer and
 * there will be no tax invoice, so the list sent somebody to a counter looking
 * for a document that does not exist. Every row here is a row that is right
 * for one route and wrong for another; a row with no entry applies to
 * everybody, which is the safe default for anything added later.
 */
const BRING_ONLY_WHEN: Record<
  string,
  (answers: Record<string, string>) => boolean
> = {
  /**
   * A tax invoice comes from a dealer. On a private sale the proof of purchase
   * is the seller's own paperwork and the signed consent, which are elsewhere
   * in the pack; on an inherited firearm there is no purchase at all.
   */
  tax_invoice: (a) =>
    !/private|inherit|estate|deceased/i.test(a[FIREARM_SOURCE_KEY] ?? ''),
  /**
   * ⚠️ AND CHARACTER REFERENCES WERE OFFERED WITH NOWHERE TO PUT THEM. The row
   * says "if you have them" while the sheet has no character-reference slot,
   * so an applicant who took the advice arrived holding a letter the pack
   * could not carry. CHARACTER_REFERENCE exists as an upload kind and the
   * witness flow collects signed statements — the row belongs where those are
   * gathered, and until it is offered there it is not offered at all.
   */
  character_references: () => false,
};

function bringApplies(key: string, answers: Record<string, string>): boolean {
  const rule = BRING_ONLY_WHEN[key];
  return rule ? rule(answers) : true;
}

export function buildChecklist(
  licenceType: MotivationLicenceType,
  haveKinds: MotivationUploadKind[],
  documentReady = false,
  context: ChecklistContext = {},
): ChecklistProgress {
  const waitingOn = context.waitingOn ?? {};

  /**
   * The three states, derived from `done` and who we are waiting on — never
   * decided independently, so `state` cannot drift from `done`.
   */
  const stateOf = (key: string, done: boolean): ChecklistState =>
    done ? 'done' : waitingOn[key] ? 'waiting-on-someone' : 'not-started';

  const annexures = buildAnnexures(haveKinds);
  const counts = new Map<MotivationUploadKind, number>();
  for (const k of haveKinds) counts.set(k, (counts.get(k) ?? 0) + 1);
  const enough = (kind: MotivationUploadKind) =>
    (counts.get(kind) ?? 0) >= (kind === 'SAFE_PHOTOGRAPHS' ? SAFE_PHOTO_MIN : 1);
  const byKind = new Map(annexures.map((a) => [a.kind, a]));

  const ours: ChecklistItem[] = [
    {
      key: 'motivation',
      label: 'Your motivation',
      owner: 'us',
      done: documentReady,
      state: stateOf('motivation', documentReady),
      closer: documentReady
        ? 'We have written this from your answers.'
        : 'We write this for you, once the questions are answered.',
      note: documentReady ? undefined : 'Finish the questions and we will prepare it.',
    },
    {
      key: 'paja',
      label: 'Request for prior notice before refusal (PAJA)',
      owner: 'us',
      done: documentReady,
      state: stateOf('paja', documentReady),
      closer: 'We prepare this and it is lodged with the application.',
      note: 'Lodged together with the application.',
    },
  ];

  // Everything recommended for this licence type, done or not — so a missing
  // item is visible rather than silently absent.
  for (const kind of RECOMMENDED[licenceType]) {
    const entry = byKind.get(kind);
    const key = `upload_${kind.toLowerCase()}`;
    const have = enough(kind);
    const item: ChecklistItem = {
      key,
      label: UPLOAD_KIND_LABELS[kind],
      owner: 'us',
      done: have,
      state: stateOf(key, have),
      // A row somebody else is finishing says so, in their words. Otherwise
      // it names the two doors — and only ever those two.
      closer:
        waitingOn[key] ??
        (have
          ? 'We hold this. Send another and it replaces it.'
          : 'Scan it with your phone, or upload it.'),
      // ⚠️ OFFERED EVEN WHEN THE ROW IS DONE. A member who photographed the
      // wrong page needs a way to replace it without deleting first.
      captureRoutes: ['qr', 'upload'],
      annexure: entry?.letter,
    };
    // ⚠️ THE ROW COLLAPSED; THE INSTRUCTION MUST NOT. One line now takes every
    // photograph of the safe, so this note is the only place a member is told
    // which pictures to take.
    //
    // ⚠️ THE THIRD SHOT IS THE WALL, NOT THE DOOR. Operator, 2026-08-23:
    // "no bolts needs be in the door. They need to be roll bolts in the wall.
    // Get rid of the bolts in the door." We used to ask for the safe fully
    // open so the locking bolts in the door were visible, and to treat the
    // anchoring as an optional fourth. That is backwards: a photograph of the
    // door proves the lock works on a box that can be carried out of the
    // house, and it is the bolts into the WALL that a DFO is actually looking
    // for. The club checklist a real S16 pack was submitted with asks for
    // exactly three, and its third is "bolts that hold the safe against the
    // wall".
    if (kind === 'SAFE_PHOTOGRAPHS') {
      item.note =
        'Add them all on this one line: the safe closed with the key out, half open with the key in the door, and the roll bolts that hold the safe to the wall. A DFO looks for all three.';
    }
    if (kind === 'INCIDENT_REPORT') {
      item.note =
        'Any SAPS case number or armed-response report from an incident that affected you. Far stronger than general crime figures.';
    }
    ours.push(item);
  }

  // ⚠️ THE COMMON LIST WAS THE WHOLE LIST for every licence type, so a
  // section 16 applicant walked to the counter with no mention of the three
  // association documents their application rests on.
  /**
   * ⚠️ ROUTE-AWARE AND SECTION-AWARE, WHICH IS THE WHOLE POINT OF THE
   * SHEET. MOTIVATION-GUIDE-BOOK Part 10.2 and 10.3. The rows that get people
   * turned away are almost never on the common list — they are the dealer's
   * stamped 350(a), the seller's licence copied on one side only, the
   * association endorsement that was never issued because an activity report
   * was outstanding. Each of those belongs to exactly one route or one
   * section, and printed on everybody's sheet they are noise that trains a
   * reader to skim.
   */
  const bring = [
    ...APPLICANT_MUST_BRING,
    ...(ROUTE_MUST_BRING[
      (context.answers?.[FIREARM_SOURCE_KEY] ?? '').trim()
    ] ?? []),
    ...(SECTION_MUST_BRING[licenceType] ?? []),
    ...(licenceType === 'S16_DEDICATED_HUNTER' ||
    licenceType === 'S16_DEDICATED_SPORT'
      ? S16_MUST_BRING
      : []),
    ...(licenceType === 'S24_RENEWAL' ? s24Bring(context.answers ?? {}) : []),
  ].filter((i) => bringApplies(i.key, context.answers ?? {}));
  const theirs: ChecklistItem[] = bring.map((i) => ({
    ...i,
    owner: 'applicant' as const,
    done: false,
    state: stateOf(i.key, false),
    // ⚠️ ONE UNIFORM SENTENCE, AND NO captureRoutes. These are certified
    // copies, passport photographs, fingerprints and a fee — things we do not
    // hold and must never imply we could take an upload of. The section intro
    // carries the regulation detail; this line only answers "so what do I do".
    closer: waitingOn[i.key] ?? 'You bring this with you to the counter.',
    // ⚠️ THE ONE ROW WHOSE NOTE DEPENDS ON MORE THAN ITSELF. Which form this
    // even is, and who fills which half of it, turns on the licence type and
    // `firearm_source` — see saps271FormNote. `context.answers ?? {}` rather
    // than skipping the override when answers are absent: a caller with no
    // answers to hand should see the honest "our half, form TBC by route"
    // sentence, not the stale placeholder above.
    ...(i.key === 'saps_form'
      ? { note: saps271FormNote(licenceType, context.answers ?? {}) }
      : {}),
  }));

  const warnings = applicationWarnings(licenceType, context.answers ?? {});
  const oursDone = ours.filter((i) => i.done).length;

  return {
    sections: [
      {
        key: 'ours',
        title: 'Your pack',
        intro:
          'We prepare these, and you upload the supporting documents here. Everything stays digital until you print.',
        items: ours,
      },
      {
        key: 'theirs',
        title: 'Take these to your Designated Firearms Officer',
        // ⚠️ WHY THIS LIST EXISTS, in one sentence the applicant can act on.
        // Regulation 13(10): the DFO does not have to accept an incomplete
        // application, and the acknowledgement is withheld until the pack IS
        // complete. A pack checked before you travel is the difference between
        // walking out with a receipt and walking out with nothing.
        // ⚠️ WHICH DFO, AND WHO HANDS IT IN. Neither was stated anywhere.
        // Reg 13(4)(a): "An application must, unless otherwise specifically
        // stated, be submitted by the applicant in person to the relevant
        // Designated Firearms Officer", and reg 1(xix) defines "relevant" as
        // the officer for the area where the applicant ordinarily resides.
        // Reg 13(9)(a) and 13(10) independently need the applicant in the
        // flesh — the DFO takes their fingerprints at the counter and checks
        // them against their identity before any acknowledgement issues,
        // which is the sharp answer to "can my wife drop it off".
        //
        // Two drafting cautions kept in the wording: reg 1(xix) has a
        // business limb, and reg 13(4)(a) opens "unless otherwise
        // specifically stated" — so this must not be phrased as admitting no
        // exception ever.
        intro:
          'The application goes to the Designated Firearms Officer for the area where you ordinarily live — not to whichever station is nearest or quietest — and you normally have to hand it in yourself. Your spouse, your dealer or a friend cannot lodge it for you: the DFO takes your fingerprints at the counter and checks them against your identity before anything is accepted. A DFO does not have to accept an incomplete application and will not issue the acknowledgement until it is complete, so it is worth checking every line before you travel. Requirements differ between stations and this list is not exhaustive: confirm it with your own DFO.',
        items: theirs,
      },
    ],
    warnings,
    oursDone,
    oursTotal: ours.length,
    theirsTotal: theirs.length,
  };
}
