import { MotivationLicenceType, MotivationUploadKind } from '@prisma/client';

// ────────────────────────────────────────────────────────────────────
// THE SUBMISSION CHECKLIST — a LIVE, TICKABLE SURFACE, not a PDF page.
//
// Operator, 2026-08-18: "The tick boxes must be on the platform and PWA, not a
// PDF document. The whole point of this is to have it all digital until the
// document is ready to be printed."
//
// So this module is DATA. It reports what is done, what is outstanding, and
// what the applicant has to fetch themselves; the platform and the PWA render
// it as a progress list they tick as they go, and it stays live right up to the
// moment they print. Only the ANNEXURE INDEX goes into the printed document —
// a reviewer holding the paper needs to find what the body cross-references.
//
// THE CONTENT IS THE OPERATOR'S OWN LIST ("Neem saam na SAP"), not a generic
// one I invented. It is materially better because it comes from someone who has
// actually lodged these applications: it names the THREE specific safe
// photographs a DFO wants, the fee per firearm, and the warning not to sign the
// SAPS forms in advance. That last one is the kind of detail that costs a
// wasted trip to the station if you get it wrong.
//
// TWO ITEM CLASSES, and the distinction is the whole design:
//   OURS   — generated by us or uploaded by the applicant. We know the state,
//            so these tick themselves.
//   THEIRS — SAPS forms, certified copies, passport photographs, the fee. We
//            do NOT hold these and must never imply we do. They stay tickable
//            by hand, and the list says plainly that it is not exhaustive and
//            that requirements differ by station.
//
// ⚠️ VERIFY BEFORE GO-LIVE: the fee and the SAPS form number are the two things
// most likely to be quietly out of date. They are marked `verifyBeforeUse`.
// ────────────────────────────────────────────────────────────────────

/** Who is responsible for producing the item. */
export type ChecklistOwner = 'us' | 'applicant';

export interface ChecklistItem {
  /** Stable key so the UI can persist a hand-tick against it. */
  key: string;
  label: string;
  owner: ChecklistOwner;
  /** True only for `owner: 'us'` items we can actually confirm. */
  done: boolean;
  /** Annexure letter, where this is one of ours. */
  annexure?: string;
  /** Shown smaller under the label. */
  note?: string;
  /** Sub-points — e.g. the three safe photographs. */
  subItems?: { key: string; label: string; done?: boolean }[];
  /** Operator/attorney must confirm this is current before go-live. */
  verifyBeforeUse?: true;
}

export interface ChecklistSection {
  key: string;
  title: string;
  intro?: string;
  items: ChecklistItem[];
}

export interface ChecklistProgress {
  sections: ChecklistSection[];
  /** Items we own that are done, over items we own. Drives the progress ring. */
  oursDone: number;
  oursTotal: number;
  /** Count the applicant still has to gather themselves. */
  theirsTotal: number;
}

export const UPLOAD_KIND_LABELS: Record<MotivationUploadKind, string> = {
  IDENTITY_DOCUMENT: 'Copy of your ID',
  COMPETENCY_CERTIFICATE: 'SAPS competency certificate',
  PROFICIENCY_CERTIFICATE: 'Proficiency / training certificate',
  CURRENT_LICENCE: 'Existing firearm licence(s)',
  ASSOCIATION_CARD: 'Association membership proof',
  ADDRESS_CONFIRMATION: 'Proof of residential address',
  EMPLOYMENT_CONFIRMATION: 'Confirmation of employment',
  SAFE_PHOTO: 'Photographs of your safe',
  SAFE_INSTALLATION: 'Photograph of the safe bolted to the wall',
  CHARACTER_REFERENCE: 'Character reference(s)',
  INCIDENT_REPORT: 'Incident report / SAPS case number',
  PREVIOUS_MOTIVATION: 'Previous motivation',
  OTHER: 'Supporting document',
};

/**
 * THE THREE SAFE PHOTOGRAPHS, verbatim from the operator's list.
 *
 * Not "a photo of your safe" — three specific shots, because that is what the
 * DFO is actually looking for: that it locks, that the key is not left in it,
 * and that it is physically anchored. Guessing at this would have produced one
 * vague instruction and a rejected application.
 */
export const SAFE_PHOTO_SHOTS = [
  {
    key: 'safe_locked',
    label: 'The safe closed and locked, with no key in it',
  },
  {
    key: 'safe_open',
    label: 'The safe door half open with the key in the lock',
  },
  {
    key: 'safe_bolts',
    label: 'Inside the safe, showing the bolts fixing it to the wall',
  },
] as const;

/** Annexure lettering order — reading order, not upload order. */
const ANNEXURE_ORDER: MotivationUploadKind[] = [
  'IDENTITY_DOCUMENT',
  'PROFICIENCY_CERTIFICATE',
  'COMPETENCY_CERTIFICATE',
  'ADDRESS_CONFIRMATION',
  'EMPLOYMENT_CONFIRMATION',
  'ASSOCIATION_CARD',
  'SAFE_PHOTO',
  'SAFE_INSTALLATION',
  'CURRENT_LICENCE',
  'INCIDENT_REPORT',
  'CHARACTER_REFERENCE',
  'PREVIOUS_MOTIVATION',
  'OTHER',
] as const;

export interface AnnexureEntry {
  letter: string;
  kind: MotivationUploadKind;
  label: string;
  count: number;
}

/**
 * Assign annexure letters to what was actually uploaded.
 *
 * Letters go to KINDS, not files: three photographs of one safe are all
 * "Annexure G", which is how the real samples do it and how a reviewer expects
 * to find them.
 */
export function buildAnnexures(kinds: MotivationUploadKind[]): AnnexureEntry[] {
  const counts = new Map<MotivationUploadKind, number>();
  for (const k of kinds) counts.set(k, (counts.get(k) ?? 0) + 1);

  const out: AnnexureEntry[] = [];
  let i = 0;
  for (const kind of ANNEXURE_ORDER) {
    const count = counts.get(kind);
    if (!count) continue;
    out.push({
      letter: String.fromCharCode(65 + i),
      kind,
      label: UPLOAD_KIND_LABELS[kind],
      count,
    });
    i++;
  }
  return out;
}

/** Uploads that materially strengthen each licence type. */
const RECOMMENDED: Record<MotivationLicenceType, MotivationUploadKind[]> = {
  S13_SELF_DEFENCE: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'SAFE_PHOTO',
    'SAFE_INSTALLATION',
    'INCIDENT_REPORT',
  ],
  S15_OCCASIONAL_HUNTER: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'PROFICIENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'SAFE_PHOTO',
    'SAFE_INSTALLATION',
    'CURRENT_LICENCE',
  ],
  S16_DEDICATED_HUNTER: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'PROFICIENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'ASSOCIATION_CARD',
    'SAFE_PHOTO',
    'SAFE_INSTALLATION',
    'CURRENT_LICENCE',
  ],
  S16_DEDICATED_SPORT: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'PROFICIENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'ASSOCIATION_CARD',
    'SAFE_PHOTO',
    'SAFE_INSTALLATION',
    'CURRENT_LICENCE',
  ],
  S24_RENEWAL: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'SAFE_PHOTO',
    'CURRENT_LICENCE',
  ],
};

/**
 * What the applicant must bring themselves — from the operator's own list.
 *
 * ⚠️ Items marked verifyBeforeUse carry a number or a form reference that can
 * go stale without notice. Confirm before the flag is flipped.
 */
const APPLICANT_MUST_BRING: Omit<ChecklistItem, 'done' | 'owner'>[] = [
  {
    key: 'saps_form',
    label: 'The SAPS application form for this licence',
    // Most dealers complete the 271 with the buyer, which is why filling it is
    // an opt-in extra rather than part of the pack.
    note: 'Your dealer will usually complete this with you — otherwise get it from your DFO, or ask us to pre-fill it in your application. Do NOT sign it beforehand — it must be signed in front of the DFO.',
    verifyBeforeUse: true,
  },
  {
    key: 'id_copies',
    label: 'Two CERTIFIED copies of your ID, not older than 3 months',
    note: 'Any police station or attorney certifies them free. DFOs reject uncertified or stale copies.',
  },
  {
    key: 'proof_of_residence',
    label: 'Certified proof of residence, not older than 3 months',
  },
  {
    key: 'character_references',
    label: 'Two character references',
    note: 'People who have known you for two years or more. Most DFOs prefer non-family: a colleague, neighbour, or community leader.',
  },
  {
    key: 'saps_541',
    label: 'SAPS 541 safe-storage undertaking, or a DFO safe inspection',
    note: 'Ask your DFO which they use — stations differ.',
    verifyBeforeUse: true,
  },
  {
    key: 'safe_invoice',
    label: 'The invoice or receipt for your safe',
  },
  {
    key: 'tax_invoice',
    label: "The dealer's tax invoice for the firearm",
    note: 'Proof of purchase. If you bought it on All Outdoor, your invoice is in your orders.',
  },
  {
    key: 'competency_copy',
    label: 'A copy of your SAPS competency certificate',
  },
  {
    key: 'passport_photos',
    label: 'Two passport photographs',
  },
  {
    key: 'fee',
    label: 'The application fee, per firearm',
    note: 'Confirm the current amount and how the station accepts payment.',
    verifyBeforeUse: true,
  },
  {
    key: 'originals',
    label: 'All your original documents',
    note: 'ID, competency, existing licences, certificates — in case the DFO wants to see them. Keep the originals; hand over copies.',
  },
  {
    key: 'own_copy',
    label: 'A copy of the whole application, for yourself',
    note: 'You will want it if anything has to be followed up later.',
  },
  {
    key: 'dfo_extras',
    label: 'Anything else your DFO asks for',
    note: 'Requirements differ between stations and provinces. Phone ahead — it is the cheapest thing you can do.',
  },
];

/**
 * Build the live checklist.
 *
 * `haveKinds` is what has actually been uploaded and `documentReady` whether the
 * motivation has passed the quality gate, so the "ours" items reflect real
 * state rather than intent.
 */
export function buildChecklist(
  licenceType: MotivationLicenceType,
  haveKinds: MotivationUploadKind[],
  documentReady = false,
): ChecklistProgress {
  const annexures = buildAnnexures(haveKinds);
  const have = new Set(haveKinds);
  const byKind = new Map(annexures.map((a) => [a.kind, a]));

  const ours: ChecklistItem[] = [
    {
      key: 'motivation',
      label: 'Your motivation',
      owner: 'us',
      done: documentReady,
      note: documentReady ? undefined : 'Finish the questions and we will prepare it.',
    },
    {
      key: 'paja',
      label: 'Request for prior notice before refusal (PAJA)',
      owner: 'us',
      done: documentReady,
      note: 'Lodged together with the application.',
    },
  ];

  // Everything recommended for this licence type, done or not — so a missing
  // item is visible rather than silently absent.
  for (const kind of RECOMMENDED[licenceType]) {
    const entry = byKind.get(kind);
    const item: ChecklistItem = {
      key: `upload_${kind.toLowerCase()}`,
      label: UPLOAD_KIND_LABELS[kind],
      owner: 'us',
      done: have.has(kind),
      annexure: entry?.letter,
    };
    if (kind === 'SAFE_PHOTO') {
      item.subItems = SAFE_PHOTO_SHOTS.map((sh) => ({ ...sh }));
      item.note = 'Three photographs — a DFO looks for all three.';
    }
    if (kind === 'INCIDENT_REPORT') {
      item.note =
        'Any SAPS case number or armed-response report from an incident that affected you. Far stronger than general crime figures.';
    }
    ours.push(item);
  }

  const theirs: ChecklistItem[] = APPLICANT_MUST_BRING.map((i) => ({
    ...i,
    owner: 'applicant' as const,
    done: false,
  }));

  const oursDone = ours.filter((i) => i.done).length;

  return {
    sections: [
      {
        key: 'ours',
        title: 'Your pack',
        intro:
          'We prepare these, and you upload the supporting documents here. Everything stays digital until you print.',
        items: ours,
      },
      {
        key: 'theirs',
        title: 'Take these to the police station',
        intro:
          'We do not hold these — you bring them yourself. Confirm the full list with your own DFO before you go: requirements differ between stations and this list is not exhaustive.',
        items: theirs,
      },
    ],
    oursDone,
    oursTotal: ours.length,
    theirsTotal: theirs.length,
  };
}
