import { MotivationLicenceType, MotivationUploadKind } from '@prisma/client';

// ────────────────────────────────────────────────────────────────────
// THE SUBMISSION CHECKLIST — a LIVE, TICKABLE SURFACE, not a PDF page.
//
// Operator, 2026-08-18: "The tick boxes must be on the platform and PWA, not a
// PDF document. The whole point of this is to have it all digital until the
// document is ready to be printed."
//
// So this module is DATA. It reports what is done, what is outstanding, and
// what the applicant has to fetch themselves; the platform and the PWA render
// it as a progress list they tick as they go, and it stays live right up to the
// moment they print. Only the ANNEXURE INDEX goes into the printed document —
// a reviewer holding the paper needs to find what the body cross-references.
//
// THE CONTENT IS THE OPERATOR'S OWN LIST ("Neem saam na SAP"), not a generic
// one I invented. It is materially better because it comes from someone who has
// actually lodged these applications: it names the THREE specific safe
// photographs a DFO wants, the fee per firearm, and the warning not to sign the
// SAPS forms in advance. That last one is the kind of detail that costs a
// wasted trip to the station if you get it wrong.
//
// TWO ITEM CLASSES, and the distinction is the whole design:
//   OURS   — generated by us or uploaded by the applicant. We know the state,
//            so these tick themselves.
//   THEIRS — SAPS forms, certified copies, passport photographs, the fee. We
//            do NOT hold these and must never imply we do. They stay tickable
//            by hand, and the list says plainly that it is not exhaustive and
//            that requirements differ by station.
//
// ⚠️ VERIFY BEFORE GO-LIVE: the fee and the SAPS form number are the two things
// most likely to be quietly out of date. They are marked `verifyBeforeUse`.
// ────────────────────────────────────────────────────────────────────

/** Who is responsible for producing the item. */
export type ChecklistOwner = 'us' | 'applicant';

export interface ChecklistItem {
  /** Stable key so the UI can persist a hand-tick against it. */
  key: string;
  label: string;
  owner: ChecklistOwner;
  /** True only for `owner: 'us'` items we can actually confirm. */
  done: boolean;
  /** Annexure letter, where this is one of ours. */
  annexure?: string;
  /** Shown smaller under the label. */
  note?: string;
  /** Sub-points — e.g. the three safe photographs. */
  subItems?: { key: string; label: string; done?: boolean }[];
  /** Operator/attorney must confirm this is current before go-live. */
  verifyBeforeUse?: true;
}

export interface ChecklistSection {
  key: string;
  title: string;
  intro?: string;
  items: ChecklistItem[];
}

export interface ChecklistProgress {
  sections: ChecklistSection[];
  /** Items we own that are done, over items we own. Drives the progress ring. */
  oursDone: number;
  oursTotal: number;
  /** Count the applicant still has to gather themselves. */
  theirsTotal: number;
}

export const UPLOAD_KIND_LABELS: Record<MotivationUploadKind, string> = {
  IDENTITY_DOCUMENT: 'Copy of your ID',
  COMPETENCY_CERTIFICATE: 'SAPS competency certificate',
  PROFICIENCY_CERTIFICATE: 'Proficiency / training certificate',
  CURRENT_LICENCE: 'Existing firearm licence(s)',
  ASSOCIATION_CARD: 'Association membership proof',
  ADDRESS_CONFIRMATION: 'Proof of residential address',
  EMPLOYMENT_CONFIRMATION: 'Confirmation of employment',
  SAFE_PHOTO_CLOSED: 'Safe closed',
  SAFE_PHOTO_AJAR: 'Safe half open, key in the door',
  SAFE_PHOTO_BOLTS: 'Safe fully open, roll bolts visible',
  // Retired 2026-08-19. Present so a row written before the split still
  // labels in the annexure index and in the file list.
  SAFE_PHOTO: 'Photographs of your safe (earlier upload)',
  SAFE_INSTALLATION: 'Photograph of the safe bolted to the wall',
  CHARACTER_REFERENCE: 'Character reference(s)',
  INCIDENT_REPORT: 'Incident report / SAPS case number',
  PREVIOUS_MOTIVATION: 'Previous motivation',
  OTHER: 'Supporting document',
};

// SAFE_PHOTO_SHOTS lived here: the three shots as SUB-ITEMS hanging off one
// checklist row. It was deleted on 2026-08-19 rather than tripled, because it
// never reached a single applicant and could not have enforced anything —
// its `done` flag was never assigned, so the sub-items rendered permanently
// unticked while the parent row ticked green on the first photograph, and the
// only endpoint that served it has no caller in the frontend.
//
// The three shots are now three MotivationUploadKind values, which the
// requirement engine already knows how to count.

/** Annexure lettering order — reading order, not upload order. */
const ANNEXURE_ORDER: MotivationUploadKind[] = [
  'IDENTITY_DOCUMENT',
  'PROFICIENCY_CERTIFICATE',
  'COMPETENCY_CERTIFICATE',
  'ADDRESS_CONFIRMATION',
  'EMPLOYMENT_CONFIRMATION',
  'ASSOCIATION_CARD',
  'SAFE_PHOTO_CLOSED',
  'SAFE_PHOTO_AJAR',
  'SAFE_PHOTO_BOLTS',
  // Retired, but still lettered — a row written before the split must not
  // fall out of the printed index.
  'SAFE_PHOTO',
  'SAFE_INSTALLATION',
  'CURRENT_LICENCE',
  'INCIDENT_REPORT',
  'CHARACTER_REFERENCE',
  'PREVIOUS_MOTIVATION',
  'OTHER',
] as const;

export interface AnnexureEntry {
  letter: string;
  kind: MotivationUploadKind;
  label: string;
  count: number;
}

/**
 * Assign annexure letters to what was actually uploaded.
 *
 * Letters go to KINDS, not files, so two copies of one ID share a letter.
 *
 * The safe is the exception, and deliberately so since 2026-08-19: its three
 * shots are three kinds, so they take three consecutive letters. A reviewer
 * looking for the roll bolts can now be sent to a letter instead of to "one of
 * the photographs in Annexure G".
 */
export function buildAnnexures(kinds: MotivationUploadKind[]): AnnexureEntry[] {
  const counts = new Map<MotivationUploadKind, number>();
  for (const k of kinds) counts.set(k, (counts.get(k) ?? 0) + 1);

  const out: AnnexureEntry[] = [];
  let i = 0;
  for (const kind of ANNEXURE_ORDER) {
    const count = counts.get(kind);
    if (!count) continue;
    out.push({
      letter: String.fromCharCode(65 + i),
      kind,
      label: UPLOAD_KIND_LABELS[kind],
      count,
    });
    i++;
  }
  return out;
}

/** Uploads that materially strengthen each licence type. */
const RECOMMENDED: Record<MotivationLicenceType, MotivationUploadKind[]> = {
  S13_SELF_DEFENCE: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'SAFE_PHOTO_CLOSED',
    'SAFE_PHOTO_AJAR',
    'SAFE_PHOTO_BOLTS',
    'SAFE_INSTALLATION',
    'INCIDENT_REPORT',
  ],
  S15_OCCASIONAL_HUNTER: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'PROFICIENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'SAFE_PHOTO_CLOSED',
    'SAFE_PHOTO_AJAR',
    'SAFE_PHOTO_BOLTS',
    'SAFE_INSTALLATION',
    'CURRENT_LICENCE',
  ],
  S16_DEDICATED_HUNTER: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'PROFICIENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'ASSOCIATION_CARD',
    'SAFE_PHOTO_CLOSED',
    'SAFE_PHOTO_AJAR',
    'SAFE_PHOTO_BOLTS',
    'SAFE_INSTALLATION',
    'CURRENT_LICENCE',
  ],
  S16_DEDICATED_SPORT: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'PROFICIENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'ASSOCIATION_CARD',
    'SAFE_PHOTO_CLOSED',
    'SAFE_PHOTO_AJAR',
    'SAFE_PHOTO_BOLTS',
    'SAFE_INSTALLATION',
    'CURRENT_LICENCE',
  ],
  S24_RENEWAL: [
    'IDENTITY_DOCUMENT',
    'COMPETENCY_CERTIFICATE',
    'ADDRESS_CONFIRMATION',
    'SAFE_PHOTO_CLOSED',
    'SAFE_PHOTO_AJAR',
    'SAFE_PHOTO_BOLTS',
    'CURRENT_LICENCE',
  ],
};

/**
 * What the applicant must bring themselves — from the operator's own list.
 *
 * ⚠️ Items marked verifyBeforeUse carry a number or a form reference that can
 * go stale without notice. Confirm before the flag is flipped.
 */
const APPLICANT_MUST_BRING: Omit<ChecklistItem, 'done' | 'owner'>[] = [
  {
    key: 'saps_form',
    label: 'The SAPS application form for this licence',
    // Most dealers complete the 271 with the buyer, which is why filling it is
    // an opt-in extra rather than part of the pack.
    note: 'Your dealer will usually complete this with you — otherwise get it from your DFO, or ask us to pre-fill it in your application. Do NOT sign it beforehand — it must be signed in front of the DFO.',
    verifyBeforeUse: true,
  },
  {
    key: 'id_copies',
    // ⚠️ THE ONE CERTIFICATION THE REGULATIONS ACTUALLY IMPOSE on an
    // individual applicant: regulation 13(4)(b) requires a certified copy of
    // the identity document. Everything else on this list is certified at the
    // counter against the original, or not at all — which is why this entry
    // says "certified" and the others no longer do.
    label: 'A certified copy of your ID (the page with your photograph)',
    note: 'This is the one copy the regulations require to be certified. Any police station or Commissioner of Oaths does it free. Bring the original as well — most DFOs certify the rest of your copies against the originals at the counter.',
  },
  {
    key: 'proof_of_residence',
    label: 'Proof of your residential address, not older than 3 months',
    note: 'A municipal bill, bank statement or lease. The three-month rule is about how RECENT it is, not about certification — bring the original and the DFO will copy or certify it there. Practice varies by station, so ask yours what they want.',
  },
  {
    key: 'character_references',
    label: 'Two character references',
    note: 'People who have known you for two years or more. Most DFOs prefer non-family: a colleague, neighbour, or community leader.',
  },
  {
    key: 'saps_541',
    label: 'SAPS 541 safe-storage undertaking, or a DFO safe inspection',
    note: 'Ask your DFO which they use — stations differ.',
    verifyBeforeUse: true,
  },
  {
    key: 'safe_invoice',
    label: 'The invoice or receipt for your safe',
  },
  {
    key: 'tax_invoice',
    label: "The dealer's tax invoice for the firearm",
    note: 'Proof of purchase. If you bought it on All Outdoor, your invoice is in your orders.',
  },
  {
    key: 'competency_copy',
    label: 'A copy of your SAPS competency certificate',
  },
  {
    key: 'passport_photos',
    label: 'Two passport photographs',
    // The SAPS 271 says PLAIN, not white — a detail that costs a second trip
    // to the photographer if you take the wrong ones.
    note: 'Colour, against a plain background. The form says "plain", not white.',
  },
  {
    key: 'fee',
    label: 'The application fee, per firearm',
    // The AMOUNT changes and is marked for checking; the SEQUENCE does not,
    // and knowing it stops a wasted queue.
    note: 'Per firearm, not per application. The DFO gives you a remittance advice, you pay at the station\u2019s own finance office, and the receipt goes back to the DFO to be attached. Confirm the current amount and what the station accepts \u2014 not every one takes cards.',
    verifyBeforeUse: true,
  },
  {
    key: 'originals',
    label: 'All your original documents',
    note: 'ID, competency, existing licences, certificates — in case the DFO wants to see them. Keep the originals; hand over copies.',
  },
  {
    key: 'own_copy',
    label: 'A copy of the whole application, for yourself',
    note: 'You will want it if anything has to be followed up later.',
  },
  {
    key: 'acknowledgement',
    // Not a document they bring — the one they must not leave without.
    label: 'Before you leave: the acknowledgement of receipt',
    note: 'The DFO issues this once the application is accepted. It is your proof of the date you lodged, and your reference for any follow-up. Do not leave the station without it.',
    verifyBeforeUse: true,
  },
  {
    key: 'dfo_extras',
    label: 'Anything else your DFO asks for',
    note: 'Requirements differ between stations and provinces. Phone ahead — it is the cheapest thing you can do.',
  },
];

/**
 * Build the live checklist.
 *
 * `haveKinds` is what has actually been uploaded and `documentReady` whether the
 * motivation has passed the quality gate, so the "ours" items reflect real
 * state rather than intent.
 */
export function buildChecklist(
  licenceType: MotivationLicenceType,
  haveKinds: MotivationUploadKind[],
  documentReady = false,
): ChecklistProgress {
  const annexures = buildAnnexures(haveKinds);
  const have = new Set(haveKinds);
  const byKind = new Map(annexures.map((a) => [a.kind, a]));

  const ours: ChecklistItem[] = [
    {
      key: 'motivation',
      label: 'Your motivation',
      owner: 'us',
      done: documentReady,
      note: documentReady ? undefined : 'Finish the questions and we will prepare it.',
    },
    {
      key: 'paja',
      label: 'Request for prior notice before refusal (PAJA)',
      owner: 'us',
      done: documentReady,
      note: 'Lodged together with the application.',
    },
  ];

  // Everything recommended for this licence type, done or not — so a missing
  // item is visible rather than silently absent.
  for (const kind of RECOMMENDED[licenceType]) {
    const entry = byKind.get(kind);
    const item: ChecklistItem = {
      key: `upload_${kind.toLowerCase()}`,
      label: UPLOAD_KIND_LABELS[kind],
      owner: 'us',
      done: have.has(kind),
      annexure: entry?.letter,
    };
    if (kind === 'SAFE_PHOTO_CLOSED') {
      item.note =
        'Three photographs of the safe, each its own line below — a DFO looks for all three.';
    }
    if (kind === 'INCIDENT_REPORT') {
      item.note =
        'Any SAPS case number or armed-response report from an incident that affected you. Far stronger than general crime figures.';
    }
    ours.push(item);
  }

  const theirs: ChecklistItem[] = APPLICANT_MUST_BRING.map((i) => ({
    ...i,
    owner: 'applicant' as const,
    done: false,
  }));

  const oursDone = ours.filter((i) => i.done).length;

  return {
    sections: [
      {
        key: 'ours',
        title: 'Your pack',
        intro:
          'We prepare these, and you upload the supporting documents here. Everything stays digital until you print.',
        items: ours,
      },
      {
        key: 'theirs',
        title: 'Take these to the police station',
        // ⚠️ WHY THIS LIST EXISTS, in one sentence the applicant can act on.
        // Regulation 13(10): the DFO does not have to accept an incomplete
        // application, and the acknowledgement is withheld until the pack IS
        // complete. A pack checked before you travel is the difference between
        // walking out with a receipt and walking out with nothing.
        intro:
          'We do not hold these — you bring them yourself. A DFO does not have to accept an incomplete application, and will not issue the acknowledgement until it is complete, so it is worth checking every line before you travel. Requirements differ between stations and this list is not exhaustive: confirm it with your own DFO.',
        items: theirs,
      },
    ],
    oursDone,
    oursTotal: ours.length,
    theirsTotal: theirs.length,
  };
}
