// GENERATED by scripts/saps271-measure.mjs — DO NOT EDIT BY HAND.
//
// Measured from the blank SAPS 271 by reading the form's own geometry: pdfjs
// gives every text run a position and every drawn path a bounding box, and the
// form is a table, so its ruling lines are its boxes. Each entry below was
// located by naming the label the form prints beside it.
//
// Regenerate after ANY change to the blank form:
//   node scripts/saps271-measure.mjs assets/saps271-blank.pdf
//
// Coordinates are PDF user space: origin BOTTOM-LEFT, points, A4 596x842.
// `y` is the bottom of the row, so a caller adds its own baseline padding.
//
// 82 of 84 fields resolved.
// The rest are listed in UNRESOLVED below and are left BLANK on the form: a box
// the applicant completes by hand is a nuisance, a guessed coordinate is a
// wrong answer on a signed firearm licence application.

/**
 * A field bound to the fillable template carries `field`; one that is not
 * carries only its measured box and is DRAWN instead. Both paths are real —
 * the operator's template has no field over Calibre or Make on page 2.
 */
export interface Saps271Bound {
  /** AcroForm field name in the template, where one covers this box. */
  field?: string;
  fieldKind?: 'text' | 'checkbox';
}

export interface Saps271TextBox extends Saps271Bound {
  kind: 'text';
  page: number;
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface Saps271Tick extends Saps271Bound {
  kind: 'tick';
  page: number;
  /** Centre of the tick cell. */
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface Saps271CharCells {
  kind: 'chars';
  page: number;
  y: number;
  h: number;
  /** One field per digit, in order, where the template provides them. */
  fields?: string[];
  /** Cell centres in order. `sep` marks a cell the form already prints into. */
  cells: { x: number; sep: string | null }[];
}

export type Saps271Field = Saps271TextBox | Saps271Tick | Saps271CharCells;

export const SAPS271_PAGE_SIZE = { width: 596, height: 842 } as const;

export const SAPS271_PAGES = 12;

export const SAPS271_COORDS = {
  "d_section_13": {
    "page": 2,
    "kind": "tick",
    "x": 540.9,
    "y": 728.8,
    "w": 38.7,
    "h": 17.4,
    "field": "text_36",
    "fieldKind": "text"
  },
  "d_section_15": {
    "page": 2,
    "kind": "tick",
    "x": 540.9,
    "y": 694,
    "w": 38.7,
    "h": 17.4,
    "field": "text_21",
    "fieldKind": "text"
  },
  "d_section_16": {
    "page": 2,
    "kind": "tick",
    "x": 540.9,
    "y": 676.6,
    "w": 38.7,
    "h": 17.4,
    "field": "text_16",
    "fieldKind": "text"
  },
  "e_type_rifle": {
    "page": 2,
    "kind": "tick",
    "x": 164.4,
    "y": 449.4,
    "w": 22.7,
    "h": 18.2,
    "field": "CheckBoxFormField 1",
    "fieldKind": "checkbox"
  },
  "e_type_shotgun": {
    "page": 2,
    "kind": "tick",
    "x": 282,
    "y": 449.4,
    "w": 20,
    "h": 18.2,
    "field": "checkbox_9",
    "fieldKind": "checkbox"
  },
  "e_type_handgun": {
    "page": 2,
    "kind": "tick",
    "x": 418,
    "y": 449.4,
    "w": 19.8,
    "h": 18.2,
    "field": "checkbox_4",
    "fieldKind": "checkbox"
  },
  "e_type_combination": {
    "page": 2,
    "kind": "tick",
    "x": 550.8,
    "y": 449.4,
    "w": 18.9,
    "h": 18.2,
    "field": "checkbox_7",
    "fieldKind": "checkbox"
  },
  "e_action_semi_auto": {
    "page": 2,
    "kind": "tick",
    "x": 284.5,
    "y": 357.6,
    "w": 20.3,
    "h": 18.5,
    "field": "checkbox_1",
    "fieldKind": "checkbox"
  },
  "e_action_manual": {
    "page": 2,
    "kind": "tick",
    "x": 550.9,
    "y": 357.6,
    "w": 19.3,
    "h": 18.5,
    "field": "checkbox_6",
    "fieldKind": "checkbox"
  },
  "e_calibre": {
    "page": 2,
    "kind": "text",
    "x": 155,
    "y": 266.6,
    "w": 211.7,
    "h": 19.1
  },
  "e_make": {
    "page": 2,
    "kind": "text",
    "x": 155,
    "y": 248.5,
    "w": 406.4,
    "h": 18.1
  },
  "e_model": {
    "page": 2,
    "kind": "text",
    "x": 155,
    "y": 230.3,
    "w": 406.4,
    "h": 18.2,
    "field": "TextFormField 3",
    "fieldKind": "text"
  },
  "e_frame_serial": {
    "page": 2,
    "kind": "text",
    "x": 155,
    "y": 176.9,
    "w": 276.8,
    "h": 17.2,
    "field": "TextFormField 4",
    "fieldKind": "text"
  },
  "e_receiver_serial": {
    "page": 2,
    "kind": "text",
    "x": 155,
    "y": 158.8,
    "w": 277.6,
    "h": 18.1,
    "field": "text_18",
    "fieldKind": "text"
  },
  "g_competency_number": {
    "page": 5,
    "kind": "text",
    "x": 180.8,
    "y": 393.9,
    "w": 380.6,
    "h": 18.1,
    "field": "TextFormField 20",
    "fieldKind": "text"
  },
  "g_competency_issued": {
    "page": 5,
    "kind": "chars",
    "y": 376.7,
    "h": 17.2,
    "cells": [
      {
        "x": 113.3,
        "sep": null
      },
      {
        "x": 131.1,
        "sep": null
      },
      {
        "x": 150.1,
        "sep": null
      },
      {
        "x": 169.3,
        "sep": null
      },
      {
        "x": 188.4,
        "sep": "-"
      },
      {
        "x": 207.5,
        "sep": null
      },
      {
        "x": 226.5,
        "sep": null
      },
      {
        "x": 245.6,
        "sep": "-"
      },
      {
        "x": 264.7,
        "sep": null
      },
      {
        "x": 283.8,
        "sep": null
      }
    ],
    "fields": [
      "text_136",
      "text_126",
      "text_127",
      "text_128",
      "text_107",
      "text_109",
      "text_102",
      "text_110"
    ]
  },
  "g_competency_expiry": {
    "page": 5,
    "kind": "chars",
    "y": 376.7,
    "h": 17.2,
    "cells": [
      {
        "x": 379.2,
        "sep": null
      },
      {
        "x": 398.3,
        "sep": null
      },
      {
        "x": 417.3,
        "sep": null
      },
      {
        "x": 436.4,
        "sep": null
      },
      {
        "x": 455.5,
        "sep": "-"
      },
      {
        "x": 474.6,
        "sep": null
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": "-"
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.9,
        "sep": null
      }
    ],
    "fields": [
      "text_118",
      "text_123",
      "text_112",
      "text_93",
      "text_115",
      "text_122",
      "text_89",
      "text_117"
    ]
  },
  "g_citizen_sa": {
    "page": 6,
    "kind": "tick",
    "x": 128.9,
    "y": 472.5,
    "w": 19.8,
    "h": 18.1,
    "field": "checkbox_1",
    "fieldKind": "checkbox"
  },
  "g_citizen_pr": {
    "page": 6,
    "kind": "tick",
    "x": 261.8,
    "y": 472.5,
    "w": 19.3,
    "h": 18.1
  },
  "g_id_number": {
    "page": 6,
    "kind": "chars",
    "y": 446.2,
    "h": 17.2,
    "cells": [
      {
        "x": 261.8,
        "sep": null
      },
      {
        "x": 281.1,
        "sep": null
      },
      {
        "x": 300.5,
        "sep": null
      },
      {
        "x": 319.3,
        "sep": null
      },
      {
        "x": 338.5,
        "sep": null
      },
      {
        "x": 358.4,
        "sep": null
      },
      {
        "x": 377.7,
        "sep": "-"
      },
      {
        "x": 397,
        "sep": null
      },
      {
        "x": 416.4,
        "sep": null
      },
      {
        "x": 435.7,
        "sep": null
      },
      {
        "x": 455,
        "sep": null
      },
      {
        "x": 474.3,
        "sep": "-"
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 513,
        "sep": null
      },
      {
        "x": 532.3,
        "sep": "-"
      },
      {
        "x": 551.2,
        "sep": null
      }
    ],
    "fields": [
      "text_118",
      "text_126",
      "text_95",
      "text_85",
      "text_82",
      "text_65",
      "text_89",
      "text_92",
      "text_93",
      "text_103",
      "text_119",
      "text_98",
      "text_123"
    ]
  },
  "g_surname": {
    "page": 6,
    "kind": "text",
    "x": 123.8,
    "y": 427.1,
    "w": 306.6,
    "h": 19.1,
    "field": "text_112",
    "fieldKind": "text"
  },
  "g_initials": {
    "page": 6,
    "kind": "chars",
    "y": 427.1,
    "h": 19.1,
    "cells": [
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.9,
        "sep": null
      },
      {
        "x": 532.1,
        "sep": null
      },
      {
        "x": 551.1,
        "sep": null
      }
    ],
    "fields": [
      "text_111",
      "text_90",
      "text_109",
      "text_110"
    ]
  },
  "g_full_names": {
    "page": 6,
    "kind": "text",
    "x": 123.8,
    "y": 409,
    "w": 437.6,
    "h": 18.1,
    "field": "text_143",
    "fieldKind": "text"
  },
  "g_date_of_birth": {
    "page": 6,
    "kind": "chars",
    "y": 391.9,
    "h": 17.1,
    "cells": [
      {
        "x": 130.3,
        "sep": null
      },
      {
        "x": 148.3,
        "sep": null
      },
      {
        "x": 167.3,
        "sep": null
      },
      {
        "x": 186.5,
        "sep": null
      },
      {
        "x": 205.7,
        "sep": "-"
      },
      {
        "x": 224.9,
        "sep": null
      },
      {
        "x": 244.1,
        "sep": null
      },
      {
        "x": 263.3,
        "sep": "-"
      },
      {
        "x": 282.5,
        "sep": null
      },
      {
        "x": 301.7,
        "sep": null
      }
    ],
    "fields": [
      "text_122",
      "text_68",
      "text_22",
      "text_33",
      "text_13",
      "text_9",
      "text_4",
      "text_145"
    ]
  },
  "g_age": {
    "page": 6,
    "kind": "chars",
    "y": 391.9,
    "h": 17.1,
    "cells": [
      {
        "x": 378.5,
        "sep": null
      },
      {
        "x": 397.7,
        "sep": null
      },
      {
        "x": 416.9,
        "sep": null
      }
    ],
    "fields": [
      "text_127",
      "text_120",
      "text_125"
    ]
  },
  "g_residential_address": {
    "page": 6,
    "kind": "text",
    "x": 140.5,
    "y": 372.8,
    "w": 420.9,
    "h": 19.1,
    "field": "text_116",
    "fieldKind": "text"
  },
  "g_postal_address": {
    "page": 6,
    "kind": "text",
    "x": 140.5,
    "y": 336.5,
    "w": 420.9,
    "h": 18.2,
    "field": "text_128",
    "fieldKind": "text"
  },
  "g_residence_type": {
    "page": 6,
    "kind": "text",
    "x": 344,
    "y": 301.3,
    "w": 217.4,
    "h": 17.1,
    "field": "text_106",
    "fieldKind": "text"
  },
  "g_occupation": {
    "page": 6,
    "kind": "text",
    "x": 164,
    "y": 282.2,
    "w": 133.3,
    "h": 19.1,
    "field": "text_59",
    "fieldKind": "text"
  },
  "g_employer": {
    "page": 6,
    "kind": "text",
    "x": 164,
    "y": 264.1,
    "w": 397.4,
    "h": 18.1,
    "field": "text_96",
    "fieldKind": "text"
  },
  "g_business_address": {
    "page": 6,
    "kind": "text",
    "x": 164,
    "y": 245.9,
    "w": 397.4,
    "h": 18.2,
    "field": "text_94",
    "fieldKind": "text"
  },
  "g_cellphone": {
    "page": 6,
    "kind": "text",
    "x": 161.7,
    "y": 191.6,
    "w": 211.8,
    "h": 18.1,
    "field": "text_78",
    "fieldKind": "text"
  },
  "g_email": {
    "page": 6,
    "kind": "text",
    "x": 161.7,
    "y": 174.4,
    "w": 399.4,
    "h": 17.2,
    "field": "text_101",
    "fieldKind": "text"
  },
  "g_marital_single": {
    "page": 6,
    "kind": "tick",
    "x": 131.1,
    "y": 127.5,
    "w": 19,
    "h": 18.1,
    "field": "TextFormField 24",
    "fieldKind": "text"
  },
  "g_marital_married": {
    "page": 6,
    "kind": "tick",
    "x": 245.6,
    "y": 127.5,
    "w": 19.1,
    "h": 18.1,
    "field": "TextFormField 25",
    "fieldKind": "text"
  },
  "g_marital_divorced": {
    "page": 6,
    "kind": "tick",
    "x": 341,
    "y": 127.5,
    "w": 19.1,
    "h": 18.1,
    "field": "TextFormField 26",
    "fieldKind": "text"
  },
  "g_marital_widow": {
    "page": 6,
    "kind": "tick",
    "x": 455.5,
    "y": 127.5,
    "w": 19.1,
    "h": 18.1,
    "field": "checkbox_3",
    "fieldKind": "checkbox"
  },
  "g_marital_widower": {
    "page": 6,
    "kind": "tick",
    "x": 550.9,
    "y": 127.5,
    "w": 19.2,
    "h": 18.1,
    "field": "checkbox_2",
    "fieldKind": "checkbox"
  },
  "g_spouse_id_type_sa": {
    "page": 7,
    "kind": "tick",
    "x": 108,
    "y": 745,
    "w": 18,
    "h": 18.1,
    "field": "text_103",
    "fieldKind": "text"
  },
  "g_spouse_id_number": {
    "page": 7,
    "kind": "chars",
    "y": 717.8,
    "h": 18.1,
    "cells": [
      {
        "x": 261.8,
        "sep": null
      },
      {
        "x": 281.1,
        "sep": null
      },
      {
        "x": 300.5,
        "sep": null
      },
      {
        "x": 319.8,
        "sep": null
      },
      {
        "x": 339,
        "sep": null
      },
      {
        "x": 358.4,
        "sep": null
      },
      {
        "x": 377.7,
        "sep": "-"
      },
      {
        "x": 397,
        "sep": null
      },
      {
        "x": 416.4,
        "sep": null
      },
      {
        "x": 435.7,
        "sep": null
      },
      {
        "x": 455,
        "sep": null
      },
      {
        "x": 474.3,
        "sep": "-"
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 513,
        "sep": null
      },
      {
        "x": 532.3,
        "sep": "-"
      },
      {
        "x": 551.2,
        "sep": null
      }
    ],
    "fields": [
      "text_77",
      "text_60",
      "text_62",
      "text_72",
      "text_68",
      "text_46",
      "text_81",
      "text_45",
      "text_54",
      "text_50",
      "text_57",
      "text_42",
      "text_82"
    ]
  },
  "g_spouse_name": {
    "page": 7,
    "kind": "text",
    "x": 157.5,
    "y": 682.5,
    "w": 403.8,
    "h": 17.2,
    "field": "text_117",
    "fieldKind": "text"
  },
  "g_association_yes": {
    "page": 7,
    "kind": "tick",
    "x": 341,
    "y": 226.6,
    "w": 19.1,
    "h": 18.1,
    "field": "TextFormField 32",
    "fieldKind": "text"
  },
  "g_association_no": {
    "page": 7,
    "kind": "tick",
    "x": 398.3,
    "y": 226.6,
    "w": 19.1,
    "h": 18.1,
    "field": "TextFormField 33",
    "fieldKind": "text"
  },
  "g_association_name": {
    "page": 7,
    "kind": "text",
    "x": 199.9,
    "y": 199.4,
    "w": 361.3,
    "h": 18.1
  },
  "g_association_far": {
    "page": 7,
    "kind": "text",
    "x": 199.9,
    "y": 181.3,
    "w": 361.2,
    "h": 18.1
  },
  "g_association_number": {
    "page": 7,
    "kind": "text",
    "x": 142.6,
    "y": 163.1,
    "w": 154.7,
    "h": 18.2,
    "field": "text_88",
    "fieldKind": "text"
  },
  "g_association_joined": {
    "page": 7,
    "kind": "chars",
    "y": 163.1,
    "h": 18.2,
    "cells": [
      {
        "x": 379.2,
        "sep": null
      },
      {
        "x": 398.3,
        "sep": null
      },
      {
        "x": 417.3,
        "sep": null
      },
      {
        "x": 436.4,
        "sep": null
      },
      {
        "x": 455.5,
        "sep": "-"
      },
      {
        "x": 474.6,
        "sep": null
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": "-"
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.8,
        "sep": null
      }
    ],
    "fields": [
      "text_124",
      "text_121",
      "text_122",
      "text_116",
      "text_129",
      "text_128",
      "text_114",
      "text_120"
    ]
  },
  "g_association_expiry": {
    "page": 7,
    "kind": "chars",
    "y": 146,
    "h": 17.1,
    "cells": [
      {
        "x": 379.2,
        "sep": null
      },
      {
        "x": 398.3,
        "sep": null
      },
      {
        "x": 417.3,
        "sep": null
      },
      {
        "x": 436.4,
        "sep": null
      },
      {
        "x": 455.5,
        "sep": "-"
      },
      {
        "x": 474.6,
        "sep": null
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": "-"
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.8,
        "sep": null
      }
    ],
    "fields": [
      "text_99",
      "text_105",
      "text_94",
      "text_100",
      "text_108",
      "text_104",
      "text_92",
      "text_106"
    ]
  },
  "g_motivation_reference": {
    "page": 7,
    "kind": "text",
    "x": 49.2,
    "y": 100.9,
    "w": 508.1,
    "h": 16.8,
    "field": "text_66",
    "fieldKind": "text"
  },
  "h_conviction_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 774.8,
    "w": 18.8,
    "h": 17.4,
    "field": "checkbox_7",
    "fieldKind": "checkbox"
  },
  "h_conviction_no": {
    "page": 8,
    "kind": "tick",
    "x": 227.1,
    "y": 774.8,
    "w": 17.8,
    "h": 17.4,
    "field": "checkbox_10",
    "fieldKind": "checkbox"
  },
  "h_pending_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 627.1,
    "w": 18.8,
    "h": 17.4,
    "field": "checkbox_5",
    "fieldKind": "checkbox"
  },
  "h_pending_no": {
    "page": 8,
    "kind": "tick",
    "x": 225.7,
    "y": 627.1,
    "w": 20.6,
    "h": 17.4,
    "field": "checkbox_12",
    "fieldKind": "checkbox"
  },
  "h_lost_stolen_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 514.2,
    "w": 18.8,
    "h": 17.4,
    "field": "checkbox_4",
    "fieldKind": "checkbox"
  },
  "h_lost_stolen_no": {
    "page": 8,
    "kind": "tick",
    "x": 225.7,
    "y": 514.2,
    "w": 20.6,
    "h": 17.4,
    "field": "checkbox_9",
    "fieldKind": "checkbox"
  },
  "h_negligence_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 366.5,
    "w": 18.8,
    "h": 17.4,
    "field": "checkbox_2",
    "fieldKind": "checkbox"
  },
  "h_negligence_no": {
    "page": 8,
    "kind": "tick",
    "x": 226.7,
    "y": 366.5,
    "w": 17,
    "h": 17.4,
    "field": "checkbox_6",
    "fieldKind": "checkbox"
  },
  "h_unfit_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 253.6,
    "w": 18.8,
    "h": 17.4,
    "field": "checkbox_1",
    "fieldKind": "checkbox"
  },
  "h_unfit_no": {
    "page": 8,
    "kind": "tick",
    "x": 226.7,
    "y": 253.6,
    "w": 17,
    "h": 17.4,
    "field": "checkbox_3",
    "fieldKind": "checkbox"
  },
  "h_confiscated_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 105.8,
    "w": 18.8,
    "h": 17.4,
    "field": "checkbox_8",
    "fieldKind": "checkbox"
  },
  "h_confiscated_no": {
    "page": 8,
    "kind": "tick",
    "x": 226.7,
    "y": 105.8,
    "w": 17,
    "h": 17.4,
    "field": "checkbox_11",
    "fieldKind": "checkbox"
  },
  "h_conviction_station": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 748.7,
    "w": 193.4,
    "h": 17.4,
    "field": "text_35",
    "fieldKind": "text"
  },
  "h_conviction_case": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 748.7,
    "w": 132.5,
    "h": 17.4,
    "field": "text_47",
    "fieldKind": "text"
  },
  "h_conviction_charge": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 731.3,
    "w": 418.7,
    "h": 17.4,
    "field": "text_51",
    "fieldKind": "text"
  },
  "h_conviction_outcome": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 713.9,
    "w": 418.7,
    "h": 17.4,
    "field": "text_44",
    "fieldKind": "text"
  },
  "h_pending_station": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 601,
    "w": 192.8,
    "h": 17.4,
    "field": "text_26",
    "fieldKind": "text"
  },
  "h_pending_case": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 601,
    "w": 132.5,
    "h": 17.4,
    "field": "text_39",
    "fieldKind": "text"
  },
  "h_pending_offence": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 583.6,
    "w": 418.7,
    "h": 17.4,
    "field": "text_38",
    "fieldKind": "text"
  },
  "h_lost_stolen_station": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 488.1,
    "w": 192.8,
    "h": 17.4,
    "field": "text_50",
    "fieldKind": "text"
  },
  "h_lost_stolen_case": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 488.1,
    "w": 132.5,
    "h": 17.4,
    "field": "text_46",
    "fieldKind": "text"
  },
  "h_lost_stolen_circumstances": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 470.7,
    "w": 418.7,
    "h": 17.4,
    "field": "text_45",
    "fieldKind": "text"
  },
  "h_lost_stolen_firearm": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 453.3,
    "w": 418.7,
    "h": 17.4,
    "field": "text_43",
    "fieldKind": "text"
  },
  "safe_yes": {
    "page": 9,
    "kind": "tick",
    "x": 130.2,
    "y": 742.1,
    "w": 17.2,
    "h": 18.1,
    "field": "checkbox_4",
    "fieldKind": "checkbox"
  },
  "safe_no": {
    "page": 9,
    "kind": "tick",
    "x": 226.5,
    "y": 742.1,
    "w": 19,
    "h": 18.1,
    "field": "checkbox_7",
    "fieldKind": "checkbox"
  },
  "safe_type_handgun": {
    "page": 9,
    "kind": "tick",
    "x": 226.2,
    "y": 705.5,
    "w": 16,
    "h": 18.1,
    "field": "checkbox_10",
    "fieldKind": "checkbox"
  },
  "safe_type_rifle": {
    "page": 9,
    "kind": "tick",
    "x": 339.6,
    "y": 705.5,
    "w": 16,
    "h": 18.1,
    "field": "checkbox_9",
    "fieldKind": "checkbox"
  },
  "safe_type_strongroom": {
    "page": 9,
    "kind": "tick",
    "x": 129.8,
    "y": 687.3,
    "w": 16.3,
    "h": 18.1,
    "field": "checkbox_5",
    "fieldKind": "checkbox"
  },
  "safe_type_device": {
    "page": 9,
    "kind": "tick",
    "x": 129.8,
    "y": 669.3,
    "w": 16.3,
    "h": 18.1,
    "field": "checkbox_8",
    "fieldKind": "checkbox"
  },
  "safe_mounted_yes": {
    "page": 9,
    "kind": "tick",
    "x": 130.2,
    "y": 632.5,
    "w": 17.2,
    "h": 18.5,
    "field": "checkbox_3",
    "fieldKind": "checkbox"
  },
  "safe_mounted_no": {
    "page": 9,
    "kind": "tick",
    "x": 226.5,
    "y": 632.5,
    "w": 19,
    "h": 18.5,
    "field": "checkbox_6",
    "fieldKind": "checkbox"
  },
  "safe_mounted_wall": {
    "page": 9,
    "kind": "tick",
    "x": 129.8,
    "y": 596,
    "w": 16.3,
    "h": 17.5,
    "field": "checkbox_1",
    "fieldKind": "checkbox"
  },
  "safe_mounted_floor": {
    "page": 9,
    "kind": "tick",
    "x": 227.7,
    "y": 596,
    "w": 18.9,
    "h": 17.5,
    "field": "checkbox_2",
    "fieldKind": "checkbox"
  }
} as const satisfies Record<string, Saps271Field>;

export type Saps271FieldName = keyof typeof SAPS271_COORDS;

/**
 * Fields the measuring pass could NOT locate, with the reason.
 *
 * Kept in the generated output on purpose. A missing key is otherwise invisible
 * — the fill service would simply never write that box and nobody would know
 * why. Gender is the interesting one: the form prints "Male" and "Female" in
 * adjacent cells with no empty cell to mark, so there is nowhere to put an X.
 */
/**
 * Measured boxes with NO field over them in the template, so the fill service
 * draws the value instead of setting a field. Not a defect — the operator's
 * template simply has no field over these — but the values still land, and this
 * list is what tells anyone why some values are editable and some are not.
 */
export const SAPS271_DRAWN_NOT_FIELDED: string[] = [
  "e_calibre",
  "e_make",
  "g_citizen_pr",
  "g_association_name",
  "g_association_far"
];

export const SAPS271_UNRESOLVED: { name: string; label: string; page: number; reason: string }[] = [
  {
    "name": "g_gender_male",
    "label": "Male",
    "page": 6,
    "reason": "cell after \"Male\" p6 already prints \"Female\""
  },
  {
    "name": "g_gender_female",
    "label": "Female",
    "page": 6,
    "reason": "\"Female\" p6 is the last cell in its row"
  }
];
