// GENERATED by scripts/saps271-measure.mjs — DO NOT EDIT BY HAND.
//
// Measured from the blank SAPS 271 by reading the form's own geometry: pdfjs
// gives every text run a position and every drawn path a bounding box, and the
// form is a table, so its ruling lines are its boxes. Each entry below was
// located by naming the label the form prints beside it.
//
// Regenerate after ANY change to the blank form:
//   node scripts/saps271-measure.mjs assets/saps271-blank.pdf
//
// Coordinates are PDF user space: origin BOTTOM-LEFT, points, A4 596x842.
// `y` is the bottom of the row, so a caller adds its own baseline padding.
//
// 188 of 188 fields resolved.
// The rest are listed in UNRESOLVED below and are left BLANK on the form: a box
// the applicant completes by hand is a nuisance, a guessed coordinate is a
// wrong answer on a signed firearm licence application.

/**
 * A field bound to the fillable template carries `field`; one that is not
 * carries only its measured box and is DRAWN instead. Both paths are real —
 * the operator's template has no field over Calibre or Make on page 2.
 */
export interface Saps271Bound {
  /** AcroForm field name in the template, where one covers this box. */
  field?: string;
  fieldKind?: 'text' | 'checkbox';
}

export interface Saps271TextBox extends Saps271Bound {
  kind: 'text';
  page: number;
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface Saps271Tick extends Saps271Bound {
  kind: 'tick';
  /**
   * The target is the option's OWN cell, not an empty one beside it — gender is
   * the case. Safe to SET as a field (the box was drawn over the word on
   * purpose); NEVER safe to draw, which would stamp an X over printed text.
   */
  overLabel?: true;
  page: number;
  /** Centre of the tick cell. */
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface Saps271CharCells {
  kind: 'chars';
  page: number;
  y: number;
  h: number;
  /** One field per digit, in order, where the template provides them. */
  fields?: string[];
  /** Cell centres in order. `sep` marks a cell the form already prints into. */
  cells: { x: number; sep: string | null }[];
}

export type Saps271Field = Saps271TextBox | Saps271Tick | Saps271CharCells;

export const SAPS271_PAGE_SIZE = { width: 596, height: 842 } as const;

export const SAPS271_PAGES = 12;

export const SAPS271_COORDS = {
  "d_section_13": {
    "page": 2,
    "kind": "tick",
    "x": 540.9,
    "y": 728.8,
    "w": 38.7,
    "h": 17.4
  },
  "d_section_15": {
    "page": 2,
    "kind": "tick",
    "x": 540.9,
    "y": 694,
    "w": 38.7,
    "h": 17.4
  },
  "d_section_16": {
    "page": 2,
    "kind": "tick",
    "x": 540.9,
    "y": 676.6,
    "w": 38.7,
    "h": 17.4
  },
  "e_type_rifle": {
    "page": 2,
    "kind": "tick",
    "x": 164.4,
    "y": 449.4,
    "w": 22.7,
    "h": 18.2
  },
  "e_type_shotgun": {
    "page": 2,
    "kind": "tick",
    "x": 282,
    "y": 449.4,
    "w": 20,
    "h": 18.2
  },
  "e_type_handgun": {
    "page": 2,
    "kind": "tick",
    "x": 418,
    "y": 449.4,
    "w": 19.8,
    "h": 18.2
  },
  "e_type_combination": {
    "page": 2,
    "kind": "tick",
    "x": 550.8,
    "y": 449.4,
    "w": 18.9,
    "h": 18.2
  },
  "e_action_semi_auto": {
    "page": 2,
    "kind": "tick",
    "x": 284.5,
    "y": 357.6,
    "w": 20.3,
    "h": 18.5
  },
  "e_action_manual": {
    "page": 2,
    "kind": "tick",
    "x": 550.9,
    "y": 357.6,
    "w": 19.3,
    "h": 18.5
  },
  "e_calibre": {
    "page": 2,
    "kind": "text",
    "x": 197.5,
    "y": 266.6,
    "w": 169.2,
    "h": 19.1
  },
  "e_make": {
    "page": 2,
    "kind": "text",
    "x": 197.5,
    "y": 248.5,
    "w": 363.9,
    "h": 18.1
  },
  "e_model": {
    "page": 2,
    "kind": "text",
    "x": 197.5,
    "y": 230.3,
    "w": 363.9,
    "h": 18.2
  },
  "e_frame_serial": {
    "page": 2,
    "kind": "text",
    "x": 197.5,
    "y": 176.9,
    "w": 234.3,
    "h": 17.2
  },
  "e_receiver_serial": {
    "page": 2,
    "kind": "text",
    "x": 197.5,
    "y": 158.8,
    "w": 235.1,
    "h": 18.1
  },
  "e_barrel_serial": {
    "page": 2,
    "kind": "text",
    "x": 197.5,
    "y": 194.1,
    "w": 236.8,
    "h": 18.1
  },
  "e_barrel_make": {
    "page": 2,
    "kind": "text",
    "x": 478.2,
    "y": 194.1,
    "w": 83.2,
    "h": 18.1
  },
  "e_frame_make": {
    "page": 2,
    "kind": "text",
    "x": 478.2,
    "y": 176.9,
    "w": 83.2,
    "h": 17.2
  },
  "e_receiver_make": {
    "page": 2,
    "kind": "text",
    "x": 478.2,
    "y": 158.8,
    "w": 83.2,
    "h": 18.1
  },
  "f_additional_holders_yes": {
    "page": 3,
    "kind": "tick",
    "x": 451.1,
    "y": 589.6,
    "w": 19.8,
    "h": 17.1
  },
  "f_additional_holders_no": {
    "page": 3,
    "kind": "tick",
    "x": 550.3,
    "y": 589.6,
    "w": 20.1,
    "h": 17.1
  },
  "g_competency_type_a": {
    "page": 5,
    "kind": "tick",
    "x": 386.4,
    "y": 493.6,
    "w": 18.9,
    "h": 18.1
  },
  "g_competency_type_b": {
    "page": 5,
    "kind": "tick",
    "x": 386.4,
    "y": 475.5,
    "w": 18.9,
    "h": 18.1
  },
  "g_competency_type_c": {
    "page": 5,
    "kind": "tick",
    "x": 386.4,
    "y": 457.4,
    "w": 18.9,
    "h": 18.1
  },
  "g_competency_type_d": {
    "page": 5,
    "kind": "tick",
    "x": 386.4,
    "y": 439.2,
    "w": 18.9,
    "h": 18.2
  },
  "g_competency_for_handgun": {
    "page": 5,
    "kind": "tick",
    "x": 177.3,
    "y": 421.1,
    "w": 3.1,
    "h": 18.1
  },
  "g_competency_for_rifle": {
    "page": 5,
    "kind": "tick",
    "x": 291.9,
    "y": 421.1,
    "w": 17,
    "h": 18.1
  },
  "g_competency_for_shotgun": {
    "page": 5,
    "kind": "tick",
    "x": 386.4,
    "y": 421.1,
    "w": 18.9,
    "h": 18.1
  },
  "g_competency_number": {
    "page": 5,
    "kind": "text",
    "x": 180.8,
    "y": 393.9,
    "w": 380.6,
    "h": 18.1
  },
  "g_competency_issued": {
    "page": 5,
    "kind": "chars",
    "y": 376.7,
    "h": 17.2,
    "cells": [
      {
        "x": 113.3,
        "sep": null
      },
      {
        "x": 131.1,
        "sep": null
      },
      {
        "x": 150.1,
        "sep": null
      },
      {
        "x": 169.3,
        "sep": null
      },
      {
        "x": 188.4,
        "sep": "-"
      },
      {
        "x": 207.5,
        "sep": null
      },
      {
        "x": 226.5,
        "sep": null
      },
      {
        "x": 245.6,
        "sep": "-"
      },
      {
        "x": 264.7,
        "sep": null
      },
      {
        "x": 283.8,
        "sep": null
      }
    ]
  },
  "g_competency_expiry": {
    "page": 5,
    "kind": "chars",
    "y": 376.7,
    "h": 17.2,
    "cells": [
      {
        "x": 379.2,
        "sep": null
      },
      {
        "x": 398.3,
        "sep": null
      },
      {
        "x": 417.3,
        "sep": null
      },
      {
        "x": 436.4,
        "sep": null
      },
      {
        "x": 455.5,
        "sep": "-"
      },
      {
        "x": 474.6,
        "sep": null
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": "-"
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.9,
        "sep": null
      }
    ]
  },
  "g_citizen_sa": {
    "page": 6,
    "kind": "tick",
    "x": 128.9,
    "y": 472.5,
    "w": 19.8,
    "h": 18.1
  },
  "g_citizen_pr": {
    "page": 6,
    "kind": "tick",
    "x": 261.8,
    "y": 472.5,
    "w": 19.3,
    "h": 18.1
  },
  "g_id_number": {
    "page": 6,
    "kind": "chars",
    "y": 446.2,
    "h": 17.2,
    "cells": [
      {
        "x": 261.8,
        "sep": null
      },
      {
        "x": 281.1,
        "sep": null
      },
      {
        "x": 300.5,
        "sep": null
      },
      {
        "x": 319.3,
        "sep": null
      },
      {
        "x": 338.5,
        "sep": null
      },
      {
        "x": 358.4,
        "sep": null
      },
      {
        "x": 377.7,
        "sep": "-"
      },
      {
        "x": 397,
        "sep": null
      },
      {
        "x": 416.4,
        "sep": null
      },
      {
        "x": 435.7,
        "sep": null
      },
      {
        "x": 455,
        "sep": null
      },
      {
        "x": 474.3,
        "sep": "-"
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 513,
        "sep": null
      },
      {
        "x": 532.3,
        "sep": "-"
      },
      {
        "x": 551.2,
        "sep": null
      }
    ]
  },
  "g_surname": {
    "page": 6,
    "kind": "text",
    "x": 123.8,
    "y": 427.1,
    "w": 306.6,
    "h": 19.1
  },
  "g_initials": {
    "page": 6,
    "kind": "chars",
    "y": 427.1,
    "h": 19.1,
    "cells": [
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.9,
        "sep": null
      },
      {
        "x": 532.1,
        "sep": null
      },
      {
        "x": 551.1,
        "sep": null
      }
    ]
  },
  "g_full_names": {
    "page": 6,
    "kind": "text",
    "x": 123.8,
    "y": 409,
    "w": 437.6,
    "h": 18.1
  },
  "g_date_of_birth": {
    "page": 6,
    "kind": "chars",
    "y": 391.9,
    "h": 17.1,
    "cells": [
      {
        "x": 130.3,
        "sep": null
      },
      {
        "x": 148.3,
        "sep": null
      },
      {
        "x": 167.3,
        "sep": null
      },
      {
        "x": 186.5,
        "sep": null
      },
      {
        "x": 205.7,
        "sep": "-"
      },
      {
        "x": 224.9,
        "sep": null
      },
      {
        "x": 244.1,
        "sep": null
      },
      {
        "x": 263.3,
        "sep": "-"
      },
      {
        "x": 282.5,
        "sep": null
      },
      {
        "x": 301.7,
        "sep": null
      }
    ]
  },
  "g_age": {
    "page": 6,
    "kind": "chars",
    "y": 391.9,
    "h": 17.1,
    "cells": [
      {
        "x": 378.5,
        "sep": null
      },
      {
        "x": 397.7,
        "sep": null
      },
      {
        "x": 416.9,
        "sep": null
      }
    ]
  },
  "g_residential_address": {
    "page": 6,
    "kind": "text",
    "x": 140.5,
    "y": 372.8,
    "w": 420.9,
    "h": 19.1
  },
  "g_postal_address": {
    "page": 6,
    "kind": "text",
    "x": 140.5,
    "y": 336.5,
    "w": 420.9,
    "h": 18.2
  },
  "g_residence_type": {
    "page": 6,
    "kind": "text",
    "x": 344,
    "y": 301.3,
    "w": 217.4,
    "h": 17.1
  },
  "g_occupation": {
    "page": 6,
    "kind": "text",
    "x": 164,
    "y": 282.2,
    "w": 133.3,
    "h": 19.1
  },
  "g_employer": {
    "page": 6,
    "kind": "text",
    "x": 164,
    "y": 264.1,
    "w": 397.4,
    "h": 18.1
  },
  "g_business_address": {
    "page": 6,
    "kind": "text",
    "x": 164,
    "y": 245.9,
    "w": 397.4,
    "h": 18.2
  },
  "g_cellphone": {
    "page": 6,
    "kind": "text",
    "x": 161.7,
    "y": 191.6,
    "w": 211.8,
    "h": 18.1
  },
  "g_email": {
    "page": 6,
    "kind": "text",
    "x": 161.7,
    "y": 174.4,
    "w": 399.4,
    "h": 17.2
  },
  "g_gender_male": {
    "page": 6,
    "kind": "tick",
    "x": 503.3,
    "y": 400.5,
    "w": 38.4,
    "h": 17.1,
    "overLabel": true
  },
  "g_gender_female": {
    "page": 6,
    "kind": "tick",
    "x": 541.5,
    "y": 400.5,
    "w": 38,
    "h": 17.1,
    "overLabel": true
  },
  "g_marital_single": {
    "page": 6,
    "kind": "tick",
    "x": 131.1,
    "y": 127.5,
    "w": 19,
    "h": 18.1
  },
  "g_marital_married": {
    "page": 6,
    "kind": "tick",
    "x": 245.6,
    "y": 127.5,
    "w": 19.1,
    "h": 18.1
  },
  "g_marital_divorced": {
    "page": 6,
    "kind": "tick",
    "x": 341,
    "y": 127.5,
    "w": 19.1,
    "h": 18.1
  },
  "g_marital_widow": {
    "page": 6,
    "kind": "tick",
    "x": 455.5,
    "y": 127.5,
    "w": 19.1,
    "h": 18.1
  },
  "g_marital_widower": {
    "page": 6,
    "kind": "tick",
    "x": 550.9,
    "y": 127.5,
    "w": 19.2,
    "h": 18.1
  },
  "g_spouse_id_type_sa": {
    "page": 7,
    "kind": "tick",
    "x": 108,
    "y": 745,
    "w": 18,
    "h": 18.1
  },
  "g_spouse_id_number": {
    "page": 7,
    "kind": "chars",
    "y": 717.8,
    "h": 18.1,
    "cells": [
      {
        "x": 261.8,
        "sep": null
      },
      {
        "x": 281.1,
        "sep": null
      },
      {
        "x": 300.5,
        "sep": null
      },
      {
        "x": 319.8,
        "sep": null
      },
      {
        "x": 339,
        "sep": null
      },
      {
        "x": 358.4,
        "sep": null
      },
      {
        "x": 377.7,
        "sep": "-"
      },
      {
        "x": 397,
        "sep": null
      },
      {
        "x": 416.4,
        "sep": null
      },
      {
        "x": 435.7,
        "sep": null
      },
      {
        "x": 455,
        "sep": null
      },
      {
        "x": 474.3,
        "sep": "-"
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 513,
        "sep": null
      },
      {
        "x": 532.3,
        "sep": "-"
      },
      {
        "x": 551.2,
        "sep": null
      }
    ]
  },
  "g_spouse_name": {
    "page": 7,
    "kind": "text",
    "x": 157.5,
    "y": 682.5,
    "w": 403.8,
    "h": 17.2
  },
  "f_owner_type_a": {
    "page": 2,
    "kind": "tick",
    "x": 169.3,
    "y": 76.1,
    "w": 19.1,
    "h": 26.4
  },
  "f_owner_type_b": {
    "page": 2,
    "kind": "tick",
    "x": 264.7,
    "y": 76.1,
    "w": 19.1,
    "h": 26.4
  },
  "f_owner_type_c": {
    "page": 2,
    "kind": "tick",
    "x": 360.1,
    "y": 76.1,
    "w": 19.1,
    "h": 26.4
  },
  "f_owner_type_d": {
    "page": 2,
    "kind": "tick",
    "x": 455.5,
    "y": 76.1,
    "w": 19.1,
    "h": 26.4
  },
  "f_owner_type_e": {
    "page": 2,
    "kind": "tick",
    "x": 550.8,
    "y": 76.1,
    "w": 19,
    "h": 26.4
  },
  "f_surname": {
    "page": 3,
    "kind": "text",
    "x": 123.6,
    "y": 761.2,
    "w": 294.3,
    "h": 18.1
  },
  "f_initials": {
    "page": 3,
    "kind": "chars",
    "y": 761.2,
    "h": 18.1,
    "cells": [
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": null
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.8,
        "sep": null
      }
    ]
  },
  "f_full_names": {
    "page": 3,
    "kind": "text",
    "x": 123.6,
    "y": 743.1,
    "w": 437.5,
    "h": 18.1
  },
  "f_id_number": {
    "page": 3,
    "kind": "chars",
    "y": 725,
    "h": 18.1,
    "cells": [
      {
        "x": 264.7,
        "sep": null
      },
      {
        "x": 283.8,
        "sep": null
      },
      {
        "x": 302.9,
        "sep": null
      },
      {
        "x": 321.9,
        "sep": null
      },
      {
        "x": 341,
        "sep": null
      },
      {
        "x": 360.1,
        "sep": null
      },
      {
        "x": 379.2,
        "sep": "-"
      },
      {
        "x": 398.3,
        "sep": null
      },
      {
        "x": 417.6,
        "sep": null
      },
      {
        "x": 436.7,
        "sep": null
      },
      {
        "x": 455.5,
        "sep": null
      },
      {
        "x": 474.6,
        "sep": "-"
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": null
      },
      {
        "x": 531.8,
        "sep": "-"
      },
      {
        "x": 550.8,
        "sep": null
      }
    ]
  },
  "f_residential_address": {
    "page": 3,
    "kind": "text",
    "x": 161.7,
    "y": 706.9,
    "w": 399.4,
    "h": 18.1
  },
  "f_residential_postal_code": {
    "page": 3,
    "kind": "chars",
    "y": 688.7,
    "h": 18.2,
    "cells": [
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": null
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.8,
        "sep": null
      }
    ]
  },
  "f_postal_address": {
    "page": 3,
    "kind": "text",
    "x": 161.7,
    "y": 670.6,
    "w": 399.4,
    "h": 18.1
  },
  "f_postal_postal_code": {
    "page": 3,
    "kind": "chars",
    "y": 653.5,
    "h": 17.1,
    "cells": [
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": null
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.8,
        "sep": null
      }
    ]
  },
  "f_home_dialling_code": {
    "page": 3,
    "kind": "text",
    "x": 233.1,
    "y": 634.4,
    "w": 20.8,
    "h": 19.1
  },
  "f_home_telephone": {
    "page": 3,
    "kind": "text",
    "x": 258.6,
    "y": 634.4,
    "w": 101.4,
    "h": 19.1
  },
  "f_work_dialling_code": {
    "page": 3,
    "kind": "text",
    "x": 437.1,
    "y": 634.4,
    "w": 20.7,
    "h": 19.1
  },
  "f_work_telephone": {
    "page": 3,
    "kind": "text",
    "x": 462.5,
    "y": 634.4,
    "w": 95.8,
    "h": 19.1
  },
  "f_cellphone": {
    "page": 3,
    "kind": "text",
    "x": 166,
    "y": 616.3,
    "w": 200,
    "h": 18.1
  },
  "f_email": {
    "page": 3,
    "kind": "text",
    "x": 166,
    "y": 598.1,
    "w": 395.1,
    "h": 18.2
  },
  "f_firearm_address": {
    "page": 5,
    "kind": "text",
    "x": 218.8,
    "y": 798.9,
    "w": 342.2,
    "h": 18.1
  },
  "f_firearm_address_2": {
    "page": 5,
    "kind": "text",
    "x": 46.3,
    "y": 781.7,
    "w": 370,
    "h": 17.2
  },
  "f_firearm_postal_code": {
    "page": 5,
    "kind": "chars",
    "y": 781.7,
    "h": 17.2,
    "cells": [
      {
        "x": 493.5,
        "sep": null
      },
      {
        "x": 512.6,
        "sep": null
      },
      {
        "x": 531.7,
        "sep": null
      },
      {
        "x": 550.8,
        "sep": null
      }
    ]
  },
  "f_owner_name": {
    "page": 5,
    "kind": "text",
    "x": 258.4,
    "y": 670,
    "w": 302.6,
    "h": 17.2
  },
  "f_owner_id": {
    "page": 5,
    "kind": "chars",
    "y": 642.7,
    "h": 27.3,
    "cells": [
      {
        "x": 265.3,
        "sep": null
      },
      {
        "x": 283.8,
        "sep": null
      },
      {
        "x": 302.9,
        "sep": null
      },
      {
        "x": 321.9,
        "sep": null
      },
      {
        "x": 341,
        "sep": null
      },
      {
        "x": 360.1,
        "sep": null
      },
      {
        "x": 379.2,
        "sep": "-"
      },
      {
        "x": 398.3,
        "sep": null
      },
      {
        "x": 417.3,
        "sep": null
      },
      {
        "x": 436.4,
        "sep": null
      },
      {
        "x": 455.5,
        "sep": null
      },
      {
        "x": 474.6,
        "sep": "-"
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": null
      },
      {
        "x": 531.8,
        "sep": "-"
      },
      {
        "x": 550.8,
        "sep": null
      }
    ]
  },
  "f_designation": {
    "page": 5,
    "kind": "text",
    "x": 104.5,
    "y": 614.3,
    "w": 212.2,
    "h": 18.2
  },
  "f_declaration_date": {
    "page": 5,
    "kind": "chars",
    "y": 614.3,
    "h": 18.2,
    "cells": [
      {
        "x": 379.2,
        "sep": null
      },
      {
        "x": 398.3,
        "sep": null
      },
      {
        "x": 417.3,
        "sep": null
      },
      {
        "x": 436.4,
        "sep": null
      },
      {
        "x": 455.5,
        "sep": "-"
      },
      {
        "x": 474.6,
        "sep": null
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": "-"
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.8,
        "sep": null
      }
    ]
  },
  "f_place": {
    "page": 5,
    "kind": "text",
    "x": 371.6,
    "y": 579.1,
    "w": 189.5,
    "h": 17.1
  },
  "d_holder_main": {
    "page": 2,
    "kind": "tick",
    "x": 188.4,
    "y": 780.3,
    "w": 19.1,
    "h": 16.7
  },
  "d_holder_additional": {
    "page": 2,
    "kind": "tick",
    "x": 355.4,
    "y": 780.3,
    "w": 18,
    "h": 16.7
  },
  "g_owned_1_type": {
    "page": 5,
    "kind": "text",
    "x": 47.2,
    "y": 294.1,
    "w": 72.6,
    "h": 17.7
  },
  "g_owned_1_calibre": {
    "page": 5,
    "kind": "text",
    "x": 123.8,
    "y": 294.1,
    "w": 72.6,
    "h": 17.7
  },
  "g_owned_1_make": {
    "page": 5,
    "kind": "text",
    "x": 200.4,
    "y": 294.1,
    "w": 72.5,
    "h": 17.7
  },
  "g_owned_1_barrel_serial": {
    "page": 5,
    "kind": "text",
    "x": 276.9,
    "y": 294.1,
    "w": 92.4,
    "h": 17.7
  },
  "g_owned_1_frame_serial": {
    "page": 5,
    "kind": "text",
    "x": 373.3,
    "y": 294.1,
    "w": 89.6,
    "h": 17.7
  },
  "g_owned_1_licence": {
    "page": 5,
    "kind": "text",
    "x": 466.9,
    "y": 294.1,
    "w": 91.4,
    "h": 17.7
  },
  "g_owned_2_type": {
    "page": 5,
    "kind": "text",
    "x": 47.2,
    "y": 277,
    "w": 72.6,
    "h": 17.1
  },
  "g_owned_2_calibre": {
    "page": 5,
    "kind": "text",
    "x": 123.8,
    "y": 277,
    "w": 72.6,
    "h": 17.1
  },
  "g_owned_2_make": {
    "page": 5,
    "kind": "text",
    "x": 200.4,
    "y": 277,
    "w": 72.5,
    "h": 17.1
  },
  "g_owned_2_barrel_serial": {
    "page": 5,
    "kind": "text",
    "x": 276.9,
    "y": 277,
    "w": 92.4,
    "h": 17.1
  },
  "g_owned_2_frame_serial": {
    "page": 5,
    "kind": "text",
    "x": 373.3,
    "y": 277,
    "w": 89.6,
    "h": 17.1
  },
  "g_owned_2_licence": {
    "page": 5,
    "kind": "text",
    "x": 466.9,
    "y": 277,
    "w": 91.4,
    "h": 17.1
  },
  "g_owned_3_type": {
    "page": 5,
    "kind": "text",
    "x": 47.2,
    "y": 257.9,
    "w": 72.6,
    "h": 19.1
  },
  "g_owned_3_calibre": {
    "page": 5,
    "kind": "text",
    "x": 123.8,
    "y": 257.9,
    "w": 72.6,
    "h": 19.1
  },
  "g_owned_3_make": {
    "page": 5,
    "kind": "text",
    "x": 200.4,
    "y": 257.9,
    "w": 72.5,
    "h": 19.1
  },
  "g_owned_3_barrel_serial": {
    "page": 5,
    "kind": "text",
    "x": 276.9,
    "y": 257.9,
    "w": 92.4,
    "h": 19.1
  },
  "g_owned_3_frame_serial": {
    "page": 5,
    "kind": "text",
    "x": 373.3,
    "y": 257.9,
    "w": 89.6,
    "h": 19.1
  },
  "g_owned_3_licence": {
    "page": 5,
    "kind": "text",
    "x": 466.9,
    "y": 257.9,
    "w": 91.4,
    "h": 19.1
  },
  "g_owned_4_type": {
    "page": 5,
    "kind": "text",
    "x": 47.2,
    "y": 240.7,
    "w": 72.6,
    "h": 17.2
  },
  "g_owned_4_calibre": {
    "page": 5,
    "kind": "text",
    "x": 123.8,
    "y": 240.7,
    "w": 72.6,
    "h": 17.2
  },
  "g_owned_4_make": {
    "page": 5,
    "kind": "text",
    "x": 200.4,
    "y": 240.7,
    "w": 72.5,
    "h": 17.2
  },
  "g_owned_4_barrel_serial": {
    "page": 5,
    "kind": "text",
    "x": 276.9,
    "y": 240.7,
    "w": 92.4,
    "h": 17.2
  },
  "g_owned_4_frame_serial": {
    "page": 5,
    "kind": "text",
    "x": 373.3,
    "y": 240.7,
    "w": 89.6,
    "h": 17.2
  },
  "g_owned_4_licence": {
    "page": 5,
    "kind": "text",
    "x": 466.9,
    "y": 240.7,
    "w": 91.4,
    "h": 17.2
  },
  "g_owned_5_type": {
    "page": 5,
    "kind": "text",
    "x": 47.2,
    "y": 221.6,
    "w": 72.6,
    "h": 19.1
  },
  "g_owned_5_calibre": {
    "page": 5,
    "kind": "text",
    "x": 123.8,
    "y": 221.6,
    "w": 72.6,
    "h": 19.1
  },
  "g_owned_5_make": {
    "page": 5,
    "kind": "text",
    "x": 200.4,
    "y": 221.6,
    "w": 72.5,
    "h": 19.1
  },
  "g_owned_5_barrel_serial": {
    "page": 5,
    "kind": "text",
    "x": 276.9,
    "y": 221.6,
    "w": 92.4,
    "h": 19.1
  },
  "g_owned_5_frame_serial": {
    "page": 5,
    "kind": "text",
    "x": 373.3,
    "y": 221.6,
    "w": 89.6,
    "h": 19.1
  },
  "g_owned_5_licence": {
    "page": 5,
    "kind": "text",
    "x": 466.9,
    "y": 221.6,
    "w": 91.4,
    "h": 19.1
  },
  "g_owned_6_type": {
    "page": 5,
    "kind": "text",
    "x": 47.2,
    "y": 204.5,
    "w": 72.6,
    "h": 17.1
  },
  "g_owned_6_calibre": {
    "page": 5,
    "kind": "text",
    "x": 123.8,
    "y": 204.5,
    "w": 72.6,
    "h": 17.1
  },
  "g_owned_6_make": {
    "page": 5,
    "kind": "text",
    "x": 200.4,
    "y": 204.5,
    "w": 72.5,
    "h": 17.1
  },
  "g_owned_6_barrel_serial": {
    "page": 5,
    "kind": "text",
    "x": 276.9,
    "y": 204.5,
    "w": 92.4,
    "h": 17.1
  },
  "g_owned_6_frame_serial": {
    "page": 5,
    "kind": "text",
    "x": 373.3,
    "y": 204.5,
    "w": 89.6,
    "h": 17.1
  },
  "g_owned_6_licence": {
    "page": 5,
    "kind": "text",
    "x": 466.9,
    "y": 204.5,
    "w": 91.4,
    "h": 17.1
  },
  "g_residential_postal_code": {
    "page": 6,
    "kind": "chars",
    "y": 354.7,
    "h": 18.1,
    "cells": [
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.9,
        "sep": null
      },
      {
        "x": 532.1,
        "sep": null
      },
      {
        "x": 551.1,
        "sep": null
      }
    ]
  },
  "g_postal_postal_code": {
    "page": 6,
    "kind": "chars",
    "y": 318.4,
    "h": 18.1,
    "cells": [
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.9,
        "sep": null
      },
      {
        "x": 532.1,
        "sep": null
      },
      {
        "x": 551.1,
        "sep": null
      }
    ]
  },
  "g_business_postal_code": {
    "page": 6,
    "kind": "chars",
    "y": 228.8,
    "h": 17.1,
    "cells": [
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": null
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.9,
        "sep": null
      }
    ]
  },
  "g_home_dialling_code": {
    "page": 6,
    "kind": "text",
    "x": 226.7,
    "y": 209.7,
    "w": 20.7,
    "h": 19.1
  },
  "g_home_telephone": {
    "page": 6,
    "kind": "text",
    "x": 252.1,
    "y": 209.7,
    "w": 115.5,
    "h": 19.1
  },
  "g_work_dialling_code": {
    "page": 6,
    "kind": "text",
    "x": 432.6,
    "y": 209.7,
    "w": 20.8,
    "h": 19.1
  },
  "g_work_telephone": {
    "page": 6,
    "kind": "text",
    "x": 458.1,
    "y": 209.7,
    "w": 100.2,
    "h": 19.1
  },
  "g_spouse_id_type_passport": {
    "page": 7,
    "kind": "tick",
    "x": 171,
    "y": 745,
    "w": 18,
    "h": 18.1
  },
  "g_spouse_passport": {
    "page": 7,
    "kind": "chars",
    "y": 699.7,
    "h": 18.1,
    "cells": [
      {
        "x": 261.8,
        "sep": null
      },
      {
        "x": 281.1,
        "sep": null
      },
      {
        "x": 300.5,
        "sep": null
      },
      {
        "x": 319.8,
        "sep": null
      },
      {
        "x": 339,
        "sep": null
      },
      {
        "x": 358.4,
        "sep": null
      },
      {
        "x": 377.7,
        "sep": null
      },
      {
        "x": 397,
        "sep": null
      },
      {
        "x": 416.4,
        "sep": null
      },
      {
        "x": 435.7,
        "sep": null
      },
      {
        "x": 455,
        "sep": null
      },
      {
        "x": 474.3,
        "sep": null
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 513,
        "sep": null
      },
      {
        "x": 532.3,
        "sep": null
      },
      {
        "x": 551.2,
        "sep": null
      }
    ]
  },
  "h_negligence_station": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 340.4,
    "w": 192.8,
    "h": 17.4
  },
  "h_negligence_case": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 340.4,
    "w": 132.5,
    "h": 17.4
  },
  "h_negligence_charge": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 322,
    "w": 192.9,
    "h": 18.4
  },
  "h_negligence_outcome": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 322,
    "w": 132.5,
    "h": 18.4
  },
  "h_unfit_station": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 227.5,
    "w": 192.8,
    "h": 17.4
  },
  "h_unfit_case": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 227.5,
    "w": 132.5,
    "h": 17.4
  },
  "h_unfit_charge": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 210.1,
    "w": 418.7,
    "h": 17.4
  },
  "h_unfit_date_from": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 191.7,
    "w": 192.8,
    "h": 18.4
  },
  "h_unfit_period": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 191.7,
    "w": 132.5,
    "h": 18.4
  },
  "h_confiscated_station": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 79.7,
    "w": 192.8,
    "h": 17.4
  },
  "h_confiscated_case": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 79.7,
    "w": 132.5,
    "h": 17.4
  },
  "h_confiscated_circumstances": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 63.3,
    "w": 192.8,
    "h": 16.4
  },
  "h_confiscated_outcome": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 63.3,
    "w": 132.5,
    "h": 16.4
  },
  "g_association_yes": {
    "page": 7,
    "kind": "tick",
    "x": 341,
    "y": 226.6,
    "w": 19.1,
    "h": 18.1
  },
  "g_association_no": {
    "page": 7,
    "kind": "tick",
    "x": 398.3,
    "y": 226.6,
    "w": 19.1,
    "h": 18.1
  },
  "g_association_name": {
    "page": 7,
    "kind": "text",
    "x": 199.9,
    "y": 199.4,
    "w": 361.3,
    "h": 18.1
  },
  "g_association_far": {
    "page": 7,
    "kind": "chars",
    "y": 181.3,
    "h": 18.1,
    "cells": [
      {
        "x": 206.7,
        "sep": null
      },
      {
        "x": 225.3,
        "sep": null
      },
      {
        "x": 245.1,
        "sep": null
      },
      {
        "x": 265,
        "sep": null
      },
      {
        "x": 284.1,
        "sep": null
      },
      {
        "x": 302.6,
        "sep": null
      },
      {
        "x": 321.6,
        "sep": null
      },
      {
        "x": 341,
        "sep": null
      },
      {
        "x": 360.1,
        "sep": null
      },
      {
        "x": 379.2,
        "sep": null
      },
      {
        "x": 398.3,
        "sep": null
      },
      {
        "x": 417.3,
        "sep": null
      },
      {
        "x": 436.4,
        "sep": null
      },
      {
        "x": 455.5,
        "sep": null
      },
      {
        "x": 474.6,
        "sep": null
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": null
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.8,
        "sep": null
      }
    ]
  },
  "g_association_number": {
    "page": 7,
    "kind": "text",
    "x": 142.6,
    "y": 163.1,
    "w": 154.7,
    "h": 18.2
  },
  "g_association_joined": {
    "page": 7,
    "kind": "chars",
    "y": 163.1,
    "h": 18.2,
    "cells": [
      {
        "x": 379.2,
        "sep": null
      },
      {
        "x": 398.3,
        "sep": null
      },
      {
        "x": 417.3,
        "sep": null
      },
      {
        "x": 436.4,
        "sep": null
      },
      {
        "x": 455.5,
        "sep": "-"
      },
      {
        "x": 474.6,
        "sep": null
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": "-"
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.8,
        "sep": null
      }
    ]
  },
  "g_association_expiry": {
    "page": 7,
    "kind": "chars",
    "y": 146,
    "h": 17.1,
    "cells": [
      {
        "x": 379.2,
        "sep": null
      },
      {
        "x": 398.3,
        "sep": null
      },
      {
        "x": 417.3,
        "sep": null
      },
      {
        "x": 436.4,
        "sep": null
      },
      {
        "x": 455.5,
        "sep": "-"
      },
      {
        "x": 474.6,
        "sep": null
      },
      {
        "x": 493.7,
        "sep": null
      },
      {
        "x": 512.7,
        "sep": "-"
      },
      {
        "x": 531.8,
        "sep": null
      },
      {
        "x": 550.8,
        "sep": null
      }
    ]
  },
  "g_motivation_reference": {
    "page": 7,
    "kind": "text",
    "x": 49.2,
    "y": 100.9,
    "w": 508.1,
    "h": 16.8
  },
  "h_conviction_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 774.8,
    "w": 18.8,
    "h": 17.4
  },
  "h_conviction_no": {
    "page": 8,
    "kind": "tick",
    "x": 227.1,
    "y": 774.8,
    "w": 17.8,
    "h": 17.4
  },
  "h_pending_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 627.1,
    "w": 18.8,
    "h": 17.4
  },
  "h_pending_no": {
    "page": 8,
    "kind": "tick",
    "x": 225.7,
    "y": 627.1,
    "w": 20.6,
    "h": 17.4
  },
  "h_lost_stolen_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 514.2,
    "w": 18.8,
    "h": 17.4
  },
  "h_lost_stolen_no": {
    "page": 8,
    "kind": "tick",
    "x": 225.7,
    "y": 514.2,
    "w": 20.6,
    "h": 17.4
  },
  "h_negligence_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 366.5,
    "w": 18.8,
    "h": 17.4
  },
  "h_negligence_no": {
    "page": 8,
    "kind": "tick",
    "x": 226.7,
    "y": 366.5,
    "w": 17,
    "h": 17.4
  },
  "h_unfit_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 253.6,
    "w": 18.8,
    "h": 17.4
  },
  "h_unfit_no": {
    "page": 8,
    "kind": "tick",
    "x": 226.7,
    "y": 253.6,
    "w": 17,
    "h": 17.4
  },
  "h_confiscated_yes": {
    "page": 8,
    "kind": "tick",
    "x": 131.2,
    "y": 105.8,
    "w": 18.8,
    "h": 17.4
  },
  "h_confiscated_no": {
    "page": 8,
    "kind": "tick",
    "x": 226.7,
    "y": 105.8,
    "w": 17,
    "h": 17.4
  },
  "h_conviction_station": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 748.7,
    "w": 193.4,
    "h": 17.4
  },
  "h_conviction_case": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 748.7,
    "w": 132.5,
    "h": 17.4
  },
  "h_conviction_charge": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 731.3,
    "w": 418.7,
    "h": 17.4
  },
  "h_conviction_outcome": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 713.9,
    "w": 418.7,
    "h": 17.4
  },
  "h_pending_station": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 601,
    "w": 192.8,
    "h": 17.4
  },
  "h_pending_case": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 601,
    "w": 132.5,
    "h": 17.4
  },
  "h_pending_offence": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 583.6,
    "w": 418.7,
    "h": 17.4
  },
  "h_lost_stolen_station": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 488.1,
    "w": 192.8,
    "h": 17.4
  },
  "h_lost_stolen_case": {
    "page": 8,
    "kind": "text",
    "x": 428.8,
    "y": 488.1,
    "w": 132.5,
    "h": 17.4
  },
  "h_lost_stolen_circumstances": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 470.7,
    "w": 418.7,
    "h": 17.4
  },
  "h_lost_stolen_firearm": {
    "page": 8,
    "kind": "text",
    "x": 142.6,
    "y": 453.3,
    "w": 418.7,
    "h": 17.4
  },
  "safe_yes": {
    "page": 9,
    "kind": "tick",
    "x": 130.2,
    "y": 742.1,
    "w": 17.2,
    "h": 18.1
  },
  "safe_no": {
    "page": 9,
    "kind": "tick",
    "x": 226.5,
    "y": 742.1,
    "w": 19,
    "h": 18.1
  },
  "safe_type_handgun": {
    "page": 9,
    "kind": "tick",
    "x": 226.2,
    "y": 705.5,
    "w": 16,
    "h": 18.1
  },
  "safe_type_rifle": {
    "page": 9,
    "kind": "tick",
    "x": 339.6,
    "y": 705.5,
    "w": 16,
    "h": 18.1
  },
  "safe_type_strongroom": {
    "page": 9,
    "kind": "tick",
    "x": 129.8,
    "y": 687.3,
    "w": 16.3,
    "h": 18.1
  },
  "safe_type_device": {
    "page": 9,
    "kind": "tick",
    "x": 129.8,
    "y": 669.3,
    "w": 16.3,
    "h": 18.1
  },
  "safe_mounted_yes": {
    "page": 9,
    "kind": "tick",
    "x": 130.2,
    "y": 632.5,
    "w": 17.2,
    "h": 18.5
  },
  "safe_mounted_no": {
    "page": 9,
    "kind": "tick",
    "x": 226.5,
    "y": 632.5,
    "w": 19,
    "h": 18.5
  },
  "safe_mounted_wall": {
    "page": 9,
    "kind": "tick",
    "x": 129.8,
    "y": 596,
    "w": 16.3,
    "h": 17.5
  },
  "safe_mounted_floor": {
    "page": 9,
    "kind": "tick",
    "x": 227.7,
    "y": 596,
    "w": 18.9,
    "h": 17.5
  },
  "safe_detail_handgun_rifle": {
    "page": 9,
    "kind": "text",
    "x": 349.6,
    "y": 696.4,
    "w": 211.8,
    "h": 18.1
  },
  "safe_detail_strongroom": {
    "page": 9,
    "kind": "text",
    "x": 139.9,
    "y": 678.3,
    "w": 421.5,
    "h": 18.1
  },
  "safe_detail_device": {
    "page": 9,
    "kind": "text",
    "x": 139.9,
    "y": 660.2,
    "w": 421.4,
    "h": 18.1
  },
  "safe_detail_mounted": {
    "page": 9,
    "kind": "text",
    "x": 239.1,
    "y": 587.2,
    "w": 322.3,
    "h": 17.5
  }
} as const satisfies Record<string, Saps271Field>;

export type Saps271FieldName = keyof typeof SAPS271_COORDS;

/**
 * Fields the measuring pass could NOT locate, with the reason.
 *
 * Kept in the generated output on purpose. A missing key is otherwise invisible
 * — the fill service would simply never write that box and nobody would know
 * why. Gender is the interesting one: the form prints "Male" and "Female" in
 * adjacent cells with no empty cell to mark, so there is nowhere to put an X.
 */
/**
 * Measured boxes with NO field over them in the template, so the fill service
 * draws the value instead of setting a field. Not a defect — the operator's
 * template simply has no field over these — but the values still land, and this
 * list is what tells anyone why some values are editable and some are not.
 */
export const SAPS271_DRAWN_NOT_FIELDED: string[] = [];

export const SAPS271_UNRESOLVED: { name: string; label: string; page: number; reason: string }[] = [];
