export { DocumentScanner, type DocumentScannerExtras } from './ui/DocumentScanner';
export type { DocumentScannerProps, DocShape, EnhanceMode, QualityVerdict, QualityLevel } from './types';
export type { DiagSample } from './ui/screens/CameraScreen';
export { cameraSupport, type CameraSupport } from './camera/support';
export { type Detector, type Detection, NullDetector, MIN_CONFIDENCE } from './pipeline/detector';
export type { Quad, Point } from './pipeline/geometry';
export { processStill, renderVariant, type ScanPage } from './pipeline/process';
export { decodeFile } from './pipeline/decode';
export { imageDataToJpeg, nameFiles, safeName, OUTPUT_MAX_EDGE, JPEG_QUALITY } from './pipeline/output';
export { estimateAspect, classifyShape, SHAPE_RATIOS } from './pipeline/aspect';
export { DEFAULT_GATES, HINT_TEXT, type GateThresholds, type Hint } from './pipeline/gates';
export { WorkerDetector, type WorkerDetectorOptions } from './pipeline/worker-detector';
export { DocAlignerRunner, DOCALIGNER_INPUT } from './pipeline/docaligner';
export { quadFromHeatmap, findPeak } from './pipeline/heatmap';
export { refineQuad, type RefineResult, type RefineOptions } from './pipeline/refine';
export type { CameraOpener, OpenCamera, CameraCapabilities } from './camera/camera';
export type { CaptureMeta } from './ui/screens/CameraScreen';
export type { StillSource } from './camera/still';
export { recropPage } from './pipeline/process';
export { chooseRotation, rotateImageData, uprightScore, type Rotation } from './pipeline/orientation';
