import type { Metadata, Viewport } from 'next';
import { Suspense } from 'react';
import { ClerkProvider } from '@clerk/nextjs';
import { PublicNav, PublicFooter } from '@/components/public-chrome';
import { UrgentNotifications } from '@/components/urgent-notifications';
import { InstallPrompt } from '@/components/install-prompt';
import { SwKillSwitch } from '@/components/sw-killswitch';
import { BottomTabBar } from '@/components/bottom-tab-bar';
import { MobileSearchBar } from '@/components/mobile-search-bar';
import { StickyFeaturedStrip } from '@/components/sticky-featured-strip';
import './globals.css';

// Inline script that runs BEFORE first paint and sets
// `data-standalone="true"` on <html> whenever the page is running as
// an installed PWA. Two signals because no single API covers all
// browsers (Safari iOS still uses the legacy `navigator.standalone`).
//
// Critical that this runs before paint — without it the top nav (which
// CSS hides via `html[data-standalone='true'] [data-public-nav]`)
// flashes for one frame on launch before the React useStandalone()
// hook re-renders. Inline-string script in <head> avoids that flash.
const STANDALONE_DETECT_SCRIPT = `(function(){try{var m=window.matchMedia&&window.matchMedia('(display-mode: standalone)');var s=(m&&m.matches)||window.navigator.standalone===true;if(s){document.documentElement.dataset.standalone='true';}if(m&&m.addEventListener){m.addEventListener('change',function(e){if(e.matches){document.documentElement.dataset.standalone='true';}else{delete document.documentElement.dataset.standalone;}});}}catch(_){}})();`;

export const metadata: Metadata = {
  title: 'Gun Galore — SA Firearms Marketplace',
  description: "South Africa's verified firearms, hunting and outdoor marketplace.",
  // PWA / iOS install hints. The manifest itself is generated by
  // app/manifest.ts and Next auto-links it; these tags add the
  // iOS-specific equivalents Safari needs to honour "Add to Home
  // Screen" properly (Safari ignores the web manifest's display
  // mode and uses apple-mobile-web-app-capable instead).
  appleWebApp: {
    capable: true,
    title: 'Gun Galore',
    statusBarStyle: 'black-translucent',
  },
  applicationName: 'Gun Galore',
  formatDetection: {
    telephone: false,
  },
  // Icon family — Next emits the corresponding <link> tags into <head>.
  // favicon.ico in app/ is auto-picked up; explicit PNGs here give
  // browsers + iOS proper sized assets to choose from.
  icons: {
    icon: [
      { url: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/apple-icon-180.png',
  },
};

// Viewport + theme-color must live in the Viewport export (Next 14+
// moved them out of Metadata). themeColor is what colours the Android
// status bar + the Chrome tab bar when the PWA is installed.
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Lets the user pinch-zoom — accessibility. We don't lock zoom.
  maximumScale: 5,
  themeColor: [
    { media: '(prefers-color-scheme: dark)', color: '#0f0f0f' },
    { media: '(prefers-color-scheme: light)', color: '#0f0f0f' },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en-ZA">
        <head>
          {/* Pre-paint standalone-mode detection — sets
              <html data-standalone="true"> when the app is running as
              an installed PWA so CSS gated on that attribute applies
              on the very first frame. Without this the top nav would
              flash for one frame in the installed app before React's
              useStandalone() hook hydrates. */}
          <script
            dangerouslySetInnerHTML={{ __html: STANDALONE_DETECT_SCRIPT }}
          />
          {/* iOS apple-touch-startup-image splash screens. iOS picks
              the right image via the media-attribute device match
              (portrait orientation + device-width + device-pixel-
              -ratio). Without these, launching the installed PWA on
              iOS shows a white-flash before our React renders — with
              them, iOS shows our branded #0f0f0f splash with the
              centred logo until the app boots.

              Files generated by pwa-asset-generator from
              public/logo-mark.svg with background #0f0f0f. */}
          {APPLE_SPLASH_LINKS.map((s) => (
            <link
              key={s.href}
              rel="apple-touch-startup-image"
              href={s.href}
              media={s.media}
            />
          ))}
        </head>
        <body className="antialiased">
          {/* PublicNav + PublicFooter hide themselves on /admin/*
              (the admin layout owns its own chrome) so the public
              Nav and ECT § 43 footer only render on the buyer/
              seller-facing pages. */}
          {/* SW kill switch — when NEXT_PUBLIC_DISABLE_PWA=true,
              unregisters any cached service worker on the user's
              browser and clears its caches. Runs as the page loads
              so a single visit cleans up after a shipped-broken SW.
              No-op when the env var is unset. */}
          <SwKillSwitch />
          <PublicNav />
          {/* Search affordance for standalone-PWA users on the Browse
              screen — the top nav (with its search input) is hidden
              in standalone mode, so this fills the gap. Self-gates on
              both display-mode + pathname, no-op everywhere else. */}
          <MobileSearchBar />
          <UrgentNotifications />
          {children}
          <PublicFooter />
          {/* Sticky featured-listings strip — hugs the bottom tab bar
              on the 5 shopping-surface pages in standalone mode.
              Self-gates on standalone + pathname. */}
          <StickyFeaturedStrip />
          {/* Bottom tab bar — installed-PWA users only. Renders null
              in browser-mobile mode so server HTML stays identical
              and the existing hamburger drawer in nav.tsx is what
              browser-mobile users see.
              Wrapped in Suspense because it reads useSearchParams()
              for the active-tab matcher; without the boundary, Next
              fails to prerender static pages that don't otherwise
              use search params (e.g. /admin/featured/banned). */}
          <Suspense fallback={null}>
            <BottomTabBar />
          </Suspense>
          {/* Floating "Install Gun Galore" CTA — listens for
              beforeinstallprompt on Android/desktop, shows an iOS
              "Share → Add to Home Screen" hint on iOS Safari. 14-day
              dismissal stored in localStorage. Already standalone-
              aware so it hides itself once the app is installed. */}
          <InstallPrompt />
        </body>
      </html>
    </ClerkProvider>
  );
}

// iOS startup-image link table — generated by pwa-asset-generator and
// pasted here. Each entry matches one device size/orientation via the
// media attribute. iOS chooses whichever matches.
//
// Regenerate with:
//   cd frontend && npx pwa-asset-generator public/logo-mark.svg public/splash \
//     --background "#0f0f0f" --splash-only --portrait-only \
//     --opaque false --padding "30%" --quality 90 --type jpeg
// Then paste the printed <link> list into this array (drop the
// `public/` prefix on hrefs since /public is served at root).
const APPLE_SPLASH_LINKS: Array<{ href: string; media: string }> = [
  { href: '/splash/apple-splash-2048-2732.jpeg', media: '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1668-2388.jpeg', media: '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1536-2048.jpeg', media: '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1640-2360.jpeg', media: '(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1668-2224.jpeg', media: '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1620-2160.jpeg', media: '(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1488-2266.jpeg', media: '(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1320-2868.jpeg', media: '(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1206-2622.jpeg', media: '(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1260-2736.jpeg', media: '(device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1290-2796.jpeg', media: '(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1179-2556.jpeg', media: '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1170-2532.jpeg', media: '(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1284-2778.jpeg', media: '(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1125-2436.jpeg', media: '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1242-2688.jpeg', media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { href: '/splash/apple-splash-828-1792.jpeg', media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  { href: '/splash/apple-splash-1242-2208.jpeg', media: '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { href: '/splash/apple-splash-750-1334.jpeg', media: '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  { href: '/splash/apple-splash-640-1136.jpeg', media: '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
];
