import type { Metadata, Viewport } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { PublicNav, PublicFooter } from '@/components/public-chrome';
import { UrgentNotifications } from '@/components/urgent-notifications';
import { InstallPrompt } from '@/components/install-prompt';
import './globals.css';

export const metadata: Metadata = {
  title: 'Gun Galore — SA Firearms Marketplace',
  description: "South Africa's verified firearms, hunting and outdoor marketplace.",
  // PWA / iOS install hints. The manifest itself is generated by
  // app/manifest.ts and Next auto-links it; these tags add the
  // iOS-specific equivalents Safari needs to honour "Add to Home
  // Screen" properly (Safari ignores the web manifest's display
  // mode and uses apple-mobile-web-app-capable instead).
  appleWebApp: {
    capable: true,
    title: 'Gun Galore',
    statusBarStyle: 'black-translucent',
  },
  applicationName: 'Gun Galore',
  formatDetection: {
    telephone: false,
  },
  // Icon family — Next emits the corresponding <link> tags into <head>.
  // favicon.ico in app/ is auto-picked up; explicit PNGs here give
  // browsers + iOS proper sized assets to choose from.
  icons: {
    icon: [
      { url: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/apple-icon-180.png',
  },
};

// Viewport + theme-color must live in the Viewport export (Next 14+
// moved them out of Metadata). themeColor is what colours the Android
// status bar + the Chrome tab bar when the PWA is installed.
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Lets the user pinch-zoom — accessibility. We don't lock zoom.
  maximumScale: 5,
  themeColor: [
    { media: '(prefers-color-scheme: dark)', color: '#0f0f0f' },
    { media: '(prefers-color-scheme: light)', color: '#0f0f0f' },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en-ZA">
        <body className="antialiased">
          {/* PublicNav + PublicFooter hide themselves on /admin/*
              (the admin layout owns its own chrome) so the public
              Nav and ECT § 43 footer only render on the buyer/
              seller-facing pages. */}
          <PublicNav />
          <UrgentNotifications />
          {children}
          <PublicFooter />
          {/* Floating "Install Gun Galore" CTA — listens for
              beforeinstallprompt on Android/desktop, shows an iOS
              "Share → Add to Home Screen" hint on iOS Safari. 14-day
              dismissal stored in localStorage. */}
          <InstallPrompt />
        </body>
      </html>
    </ClerkProvider>
  );
}
