import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

/**
 * Zoho Books integration — accounting backend for Gun Galore.
 *
 * Design contract:
 *   - Buyer never sees a Books document. Their "Order Confirmation"
 *     is generated by Gun Galore's own platform (agent model — see
 *     the accounting-flow doc that went to the accountant).
 *   - Seller receives a Books-issued Tax Invoice for the commission
 *     when verification approves. The H&G-style Reference field
 *     spells out "Sold for R X - R Y (Platform Fee) = R Z Due to you".
 *   - When the seller payout fires, we mark the invoice paid in Books
 *     against the Client Funds Payable liability — closing the loop.
 *   - Raffle ticket purchases create Sales Receipts directly to buyer
 *     (raffles are NOT marketplace — Gun Galore is the actual seller).
 *   - Featured-slot bid wins create invoices to the winning seller.
 *
 * Failure handling:
 *   - Every public method is fire-and-forget from the caller's
 *     perspective. We never block the user-facing flow on a Books API
 *     call — Books going down can't delay payouts or break checkout.
 *   - Each Gun Galore record (Transaction, Ticket, FeaturedSlotBid)
 *     has zohoSyncStatus + zohoSyncError + zohoSyncLastAttemptAt
 *     fields. On failure we write FAILED + the error message; the
 *     admin panel shows these + a retry button.
 *   - Feature-flag gated: ZOHO_BOOKS_ENABLED=false skips every API
 *     call (records get status SKIPPED). Lets us deploy code without
 *     touching the live Books account until we explicitly turn it on.
 *
 * Auth:
 *   - Long-lived refresh token in env. Access tokens cached in-memory
 *     for ~55 minutes (Zoho gives 1 hour, we refresh a bit early).
 *   - 401 responses force a refresh and one retry.
 */
@Injectable()
export class ZohoBooksService {
  private readonly logger = new Logger(ZohoBooksService.name);

  private readonly enabled: boolean;
  private readonly clientId: string;
  private readonly clientSecret: string;
  private readonly refreshToken: string;
  private readonly orgId: string;
  private readonly apiDomain: string;
  private readonly accountsDomain: string;

  // In-memory access-token cache. Access tokens are short-lived (1h);
  // we refresh on demand and cache until just before expiry.
  private cachedAccessToken: string | null = null;
  private cachedAccessTokenExpiresAt = 0; // epoch ms

  constructor(private readonly prisma: PrismaService) {
    // Feature flag — leave OFF (false) by default until we're ready
    // to push real documents to Books. Set ZOHO_BOOKS_ENABLED=true
    // in .env when going live.
    this.enabled = process.env.ZOHO_BOOKS_ENABLED === 'true';
    this.clientId = process.env.ZOHO_BOOKS_CLIENT_ID ?? '';
    this.clientSecret = process.env.ZOHO_BOOKS_CLIENT_SECRET ?? '';
    this.refreshToken = process.env.ZOHO_BOOKS_REFRESH_TOKEN ?? '';
    this.orgId = process.env.ZOHO_BOOKS_ORG_ID ?? '';
    this.apiDomain =
      process.env.ZOHO_BOOKS_API_DOMAIN ?? 'https://www.zohoapis.com';
    this.accountsDomain =
      process.env.ZOHO_BOOKS_ACCOUNTS_DOMAIN ?? 'https://accounts.zoho.com';

    if (this.enabled && !this.hasCredentials()) {
      this.logger.error(
        'ZOHO_BOOKS_ENABLED=true but credentials are missing — disabling.',
      );
    }

    if (this.enabled) {
      this.logger.log(
        `Zoho Books integration ENABLED (org ${this.orgId}, api ${this.apiDomain})`,
      );
    } else {
      this.logger.log(
        'Zoho Books integration DISABLED (set ZOHO_BOOKS_ENABLED=true to turn on)',
      );
    }
  }

  /** Public — used by health monitor + admin panel. */
  isEnabled(): boolean {
    return this.enabled && this.hasCredentials();
  }

  private hasCredentials(): boolean {
    return !!(
      this.clientId &&
      this.clientSecret &&
      this.refreshToken &&
      this.orgId
    );
  }

  // ─── Access token management ─────────────────────────────────────

  /**
   * Returns a valid access token. Cached in-memory for ~55 minutes;
   * refreshes from the long-lived refresh token when stale.
   *
   * Don't call externally — every public method on this service that
   * hits the API uses this internally.
   */
  private async getAccessToken(): Promise<string> {
    const now = Date.now();
    // 60-second safety margin so we don't ship a token that expires
    // mid-request.
    if (this.cachedAccessToken && this.cachedAccessTokenExpiresAt > now + 60_000) {
      return this.cachedAccessToken;
    }

    const body = new URLSearchParams({
      grant_type: 'refresh_token',
      client_id: this.clientId,
      client_secret: this.clientSecret,
      refresh_token: this.refreshToken,
    });

    const res = await fetch(`${this.accountsDomain}/oauth/v2/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: body.toString(),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(
        `Zoho token refresh failed (${res.status}): ${text || res.statusText}`,
      );
    }

    const data = (await res.json()) as {
      access_token?: string;
      expires_in?: number;
      error?: string;
    };

    if (!data.access_token) {
      throw new Error(
        `Zoho token refresh returned no access_token: ${data.error ?? 'unknown'}`,
      );
    }

    // Cache. Zoho usually returns expires_in: 3600 (one hour).
    const expiresInMs = (data.expires_in ?? 3600) * 1000;
    this.cachedAccessToken = data.access_token;
    this.cachedAccessTokenExpiresAt = now + expiresInMs;
    this.logger.log(
      `Zoho access token refreshed (expires in ${Math.round(expiresInMs / 60000)}m)`,
    );
    return data.access_token;
  }

  // ─── Authenticated HTTP wrapper ──────────────────────────────────

  /**
   * Authenticated request to Zoho Books API.
   * Auto-prepends organization_id query param to every call.
   * On 401, forces a token refresh and retries once.
   */
  private async request<T>(
    method: 'GET' | 'POST' | 'PUT' | 'DELETE',
    path: string,
    body?: unknown,
  ): Promise<T> {
    return this.requestInner<T>(method, path, body, /* retried */ false);
  }

  private async requestInner<T>(
    method: 'GET' | 'POST' | 'PUT' | 'DELETE',
    path: string,
    body: unknown,
    retried: boolean,
  ): Promise<T> {
    const token = await this.getAccessToken();
    // Books REST API requires organization_id as a query param on
    // every endpoint. We append it ourselves so callers don't have to
    // remember.
    const sep = path.includes('?') ? '&' : '?';
    const url = `${this.apiDomain}/books/v3${path}${sep}organization_id=${this.orgId}`;

    const init: RequestInit = {
      method,
      headers: {
        Authorization: `Zoho-oauthtoken ${token}`,
        'Content-Type': 'application/json',
      },
    };
    if (body !== undefined) {
      init.body = JSON.stringify(body);
    }

    const res = await fetch(url, init);

    if (res.status === 401 && !retried) {
      // Token cache thinks it's valid but Zoho disagrees — force
      // refresh and retry once.
      this.logger.warn('Zoho returned 401 — forcing token refresh');
      this.cachedAccessToken = null;
      this.cachedAccessTokenExpiresAt = 0;
      return this.requestInner<T>(method, path, body, true);
    }

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(
        `Zoho Books ${method} ${path} failed (${res.status}): ${text || res.statusText}`,
      );
    }

    return (await res.json()) as T;
  }

  // ─── Contact (customer) management ───────────────────────────────

  /**
   * Find-or-create the Books contact for a Gun Galore user.
   *
   * Strategy:
   *   - If user.zohoContactId is set, return it (already created).
   *   - Else create a new contact via API and save the returned ID
   *     onto the User record.
   *
   * Used for both sellers (we invoice them for commission) and
   * raffle-ticket buyers (we issue them Sales Receipts).
   *
   * Idempotent — concurrent calls for the same user are safe; the
   * unique constraint isn't enforced at DB level but the User row
   * update is atomic, and Zoho's create-contact returns 400 if a
   * duplicate email is detected, which we catch + look up by email.
   */
  async ensureContact(
    userId: string,
    fallbackEmail?: string,
  ): Promise<string | null> {
    if (!this.isEnabled()) return null;

    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: {
        id: true,
        zohoContactId: true,
        email: true,
        firstName: true,
        lastName: true,
        username: true,
        phone: true,
        addrStreet: true,
        addrSuburb: true,
        addrCity: true,
        addrPostalCode: true,
        addrProvince: true,
      },
    });
    if (!user) return null;
    if (user.zohoContactId) return user.zohoContactId;

    const displayName =
      [user.firstName, user.lastName].filter(Boolean).join(' ') ||
      user.username ||
      fallbackEmail ||
      user.email;

    const payload = {
      contact_name: displayName,
      contact_type: 'customer',
      // Books treats this list as the people you can email invoices
      // to. We use the user's primary email.
      contact_persons: [
        {
          first_name: user.firstName ?? '',
          last_name: user.lastName ?? user.username ?? '',
          email: user.email,
          phone: user.phone ?? '',
          is_primary_contact: true,
        },
      ],
      // Address block — used as the bill-to on invoices.
      billing_address: {
        address: user.addrStreet ?? '',
        street2: user.addrSuburb ?? '',
        city: user.addrCity ?? '',
        state: user.addrProvince ?? '',
        zip: user.addrPostalCode ?? '',
        country: 'South Africa',
      },
      // Notes field — surfaces the Gun Galore user ID for the
      // accountant to cross-reference with our admin panel.
      notes: `Gun Galore user ID: ${user.id} / username: @${user.username ?? '(none)'}`,
    };

    type CreateContactResp = {
      contact?: { contact_id?: string };
      code?: number;
      message?: string;
    };
    const resp = await this.request<CreateContactResp>(
      'POST',
      '/contacts',
      payload,
    );

    const contactId = resp.contact?.contact_id;
    if (!contactId) {
      throw new Error(
        `Zoho Books contact create returned no contact_id: ${resp.message ?? 'unknown'}`,
      );
    }

    // Save the ID on the user so we don't recreate next time.
    await this.prisma.user.update({
      where: { id: user.id },
      data: { zohoContactId: contactId },
    });

    this.logger.log(
      `Created Books contact ${contactId} for user ${user.id} (${displayName})`,
    );
    return contactId;
  }

  // ─── Account ID lookup ───────────────────────────────────────────

  /**
   * Find a Books Chart-of-Accounts account by name.
   * Used at startup time (or on first invoice) to resolve account
   * names like "Commission Revenue" or "Client Funds Payable" to the
   * Books account IDs the API needs.
   *
   * Cached in-memory after first lookup (account IDs don't change).
   */
  private accountIdCache: Map<string, string> = new Map();

  async getAccountIdByName(accountName: string): Promise<string | null> {
    if (!this.isEnabled()) return null;
    const cached = this.accountIdCache.get(accountName);
    if (cached) return cached;

    type ChartOfAccountsResp = {
      chartofaccounts?: Array<{
        account_id?: string;
        account_name?: string;
      }>;
    };
    const resp = await this.request<ChartOfAccountsResp>(
      'GET',
      '/chartofaccounts',
    );

    const accounts = resp.chartofaccounts ?? [];
    // Cache them all while we have the list — we'll need several.
    for (const acc of accounts) {
      if (acc.account_id && acc.account_name) {
        this.accountIdCache.set(acc.account_name, acc.account_id);
      }
    }
    return this.accountIdCache.get(accountName) ?? null;
  }

  // ─── Public document-creation methods ────────────────────────────
  // ZB-4 onwards wires these into the actual hooks. They're stubs
  // here so ZB-3 (this file) compiles cleanly + the integration
  // boundaries are documented.

  /**
   * Commission invoice: Gun Galore → Seller for the platform fee on
   * a marketplace sale. Called from the verification-APPROVED hook.
   *
   * Idempotent: skips if zohoCommissionInvoiceId already set.
   * Skips silently for PRIVATE_ARRANGE (no commission on that flow —
   * funds release direct to seller at payment capture, no agent
   * relationship to invoice).
   *
   * On any error: writes FAILED status + error message to the
   * transaction row. Caller doesn't need to try/catch — this method
   * never throws.
   */
  async createCommissionInvoice(transactionId: string): Promise<void> {
    if (!this.isEnabled()) return;
    const tx = await this.prisma.transaction.findUnique({
      where: { id: transactionId },
      include: {
        seller: {
          select: {
            id: true,
            email: true,
            username: true,
            firstName: true,
            lastName: true,
          },
        },
        listing: {
          select: {
            title: true,
            referenceNumber: true,
          },
        },
      },
    });
    if (!tx) return;
    // Idempotency — if we've already created the invoice, no-op.
    if (tx.zohoCommissionInvoiceId) return;
    // PRIVATE_ARRANGE has no platform commission invoice (we don't
    // hold funds for it). Skip silently.
    if (tx.shippingMethod === 'PRIVATE_ARRANGE') {
      await this.markSkipped(
        transactionId,
        'PRIVATE_ARRANGE — no commission invoice',
      );
      return;
    }
    if (tx.commissionZar <= 0) {
      await this.markSkipped(transactionId, 'commissionZar is zero');
      return;
    }

    await this.markPending(transactionId);

    try {
      const contactId = await this.ensureContact(tx.seller.id, tx.seller.email);
      if (!contactId) {
        throw new Error('Could not resolve Books contact for seller');
      }

      const commissionRand = tx.commissionZar / 100;
      const listingPriceRand = tx.listingPrice / 100;
      const sellerPayoutRand = tx.sellerPayout / 100;
      const orderRef =
        tx.listing.referenceNumber ?? tx.id.slice(-8).toUpperCase();

      // H&G-style reference: spells out the math in plain language
      // so the seller sees "what I sold for - what you took = what I
      // get". This is exactly what the H&G invoice we mirrored does.
      const reference = `Sold for ${this.formatRand(listingPriceRand)} - ${this.formatRand(commissionRand)} (Platform Fee) = ${this.formatRand(sellerPayoutRand)} Due to you`;

      // Resolve Commission Revenue account so Books posts the income
      // to the right ledger row. Cached after first lookup.
      const commissionAccountId = await this.getAccountIdByName(
        'Commission Revenue',
      );
      if (!commissionAccountId) {
        throw new Error(
          'Commission Revenue account not found in Books chart-of-accounts',
        );
      }

      const today = new Date().toISOString().slice(0, 10);

      type CreateInvoiceResp = {
        invoice?: { invoice_id?: string; invoice_number?: string };
        code?: number;
        message?: string;
      };
      const payload = {
        customer_id: contactId,
        reference_number: reference,
        date: today,
        due_date: today,
        line_items: [
          {
            name: 'Platform Fee',
            description: `${orderRef} — ${tx.listing.title}`,
            rate: commissionRand,
            quantity: 1,
            account_id: commissionAccountId,
          },
        ],
        notes: `${reference}.\nGun Galore transaction reference: ${orderRef}`,
        // Skip tax — we're pre-VAT. When VAT-registered this flips
        // to is_inclusive_tax: false + tax_id on each line.
      };

      const resp = await this.request<CreateInvoiceResp>(
        'POST',
        '/invoices',
        payload,
      );

      const invoiceId = resp.invoice?.invoice_id;
      if (!invoiceId) {
        throw new Error(
          `Books invoice create returned no invoice_id: ${resp.message ?? 'unknown'}`,
        );
      }

      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoCommissionInvoiceId: invoiceId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Created commission invoice ${resp.invoice?.invoice_number ?? invoiceId} for tx ${transactionId} (R${commissionRand.toFixed(2)})`,
      );
    } catch (err) {
      await this.markFailed(transactionId, err as Error);
    }
  }

  /**
   * Records payment against the commission invoice using Client
   * Funds Payable as the source — effectively draining the held
   * funds liability by the commission amount and marking the
   * invoice as Paid in one Books operation.
   *
   * Called after createCommissionInvoice (typically in the same
   * verification-APPROVED hook). Idempotent: skips if
   * zohoCommissionPaymentId already set, or if the invoice ID is
   * not yet set (createCommissionInvoice must run first).
   *
   * Like createCommissionInvoice, never throws — failures are
   * persisted as FAILED status on the transaction.
   */
  async markCommissionInvoicePaid(transactionId: string): Promise<void> {
    if (!this.isEnabled()) return;
    const tx = await this.prisma.transaction.findUnique({
      where: { id: transactionId },
      include: {
        seller: { select: { id: true } },
      },
    });
    if (!tx) return;
    if (!tx.zohoCommissionInvoiceId) return; // invoice must exist first
    if (tx.zohoCommissionPaymentId) return; // already marked paid

    try {
      const sellerContactId = await this.ensureContact(tx.seller.id);
      if (!sellerContactId) {
        throw new Error('Could not resolve seller contact for payment');
      }

      const cfpAccountId = await this.getAccountIdByName(
        'Client Funds Payable',
      );
      if (!cfpAccountId) {
        throw new Error(
          'Client Funds Payable account not found in Books chart-of-accounts',
        );
      }

      const commissionRand = tx.commissionZar / 100;
      const today = new Date().toISOString().slice(0, 10);
      const orderRef = tx.id.slice(-8).toUpperCase();

      type CreatePaymentResp = {
        payment?: { payment_id?: string };
        code?: number;
        message?: string;
      };
      const payload = {
        customer_id: sellerContactId,
        payment_mode: 'Other',
        amount: commissionRand,
        date: today,
        reference_number: `Settled from buyer funds — ${orderRef}`,
        // The deposit_to_account is where the money "came from" —
        // in our case from the Client Funds Payable liability, NOT
        // from a real bank account. Books may need this set up as
        // a "Bank" type account in their CoA for this to work; if
        // it errors here we'll know to either reclassify CFP or
        // switch to a manual-journal posting pattern.
        deposit_to_account_id: cfpAccountId,
        invoices: [
          {
            invoice_id: tx.zohoCommissionInvoiceId,
            amount_applied: commissionRand,
          },
        ],
        description:
          'Commission settled by draining buyer funds held in trust',
      };

      const resp = await this.request<CreatePaymentResp>(
        'POST',
        '/customerpayments',
        payload,
      );

      const paymentId = resp.payment?.payment_id;
      if (!paymentId) {
        throw new Error(
          `Books payment create returned no payment_id: ${resp.message ?? 'unknown'}`,
        );
      }

      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoCommissionPaymentId: paymentId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Marked commission invoice paid for tx ${transactionId} (R${commissionRand.toFixed(2)})`,
      );
    } catch (err) {
      await this.markFailed(transactionId, err as Error);
    }
  }

  // ─── Status helpers ──────────────────────────────────────────────

  private async markPending(transactionId: string): Promise<void> {
    await this.prisma.transaction.update({
      where: { id: transactionId },
      data: {
        zohoSyncStatus: 'PENDING',
        zohoSyncLastAttemptAt: new Date(),
      },
    });
  }

  private async markSkipped(
    transactionId: string,
    reason: string,
  ): Promise<void> {
    await this.prisma.transaction.update({
      where: { id: transactionId },
      data: {
        zohoSyncStatus: 'SKIPPED',
        zohoSyncError: reason,
        zohoSyncLastAttemptAt: new Date(),
      },
    });
  }

  private async markFailed(
    transactionId: string,
    err: Error,
  ): Promise<void> {
    const message = err.message.slice(0, 1000);
    this.logger.error(
      `Zoho Books sync FAILED for tx ${transactionId}: ${message}`,
    );
    try {
      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoSyncStatus: 'FAILED',
          zohoSyncError: message,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
    } catch (writeErr) {
      this.logger.error(
        `Could not write FAILED status to tx ${transactionId}: ${(writeErr as Error).message}`,
      );
    }
  }

  private formatRand(amount: number): string {
    // R 10,000 / R 1,500.50 / R 0.99 — matches H&G invoice style.
    // Use en-US locale so the thousands separator is a regular comma
    // (ASCII U+002C). Earlier version used en-ZA which gave us a
    // non-breaking space (U+00A0) — Zoho's PDF font doesn't have a
    // glyph for that and renders it as U+FFFD replacement character
    // ("R 10�000" instead of "R 10,000").
    const formatted = amount.toLocaleString('en-US', {
      minimumFractionDigits: amount % 1 === 0 ? 0 : 2,
      maximumFractionDigits: 2,
    });
    return `R ${formatted}`;
  }

  /**
   * Credit Note: reverses a commission invoice on refund.
   * Called by ZB-6 when a refund is issued.
   */
  async createCommissionCreditNote(_transactionId: string): Promise<void> {
    if (!this.isEnabled()) return;
    this.logger.debug('createCommissionCreditNote not yet wired (ZB-6)');
  }

  /**
   * Sales Receipt for a raffle ticket purchase (one receipt per
   * peachCheckoutId, covering all tickets bought in the batch).
   * Called by ZB-7.
   */
  async createRaffleTicketSalesReceipt(
    _peachCheckoutId: string,
  ): Promise<void> {
    if (!this.isEnabled()) return;
    this.logger.debug('createRaffleTicketSalesReceipt not yet wired (ZB-7)');
  }

  /**
   * Invoice for a featured-slot fee. Called by ZB-8 when a winning
   * bid is committed (Peach captures the payment).
   */
  async createFeaturedSlotInvoice(_bidId: string): Promise<void> {
    if (!this.isEnabled()) return;
    this.logger.debug('createFeaturedSlotInvoice not yet wired (ZB-8)');
  }

  // ─── Health check ────────────────────────────────────────────────

  /**
   * Lightweight probe for /admin/health. Pings the /organizations
   * endpoint to confirm auth + connectivity. Used by ZB-11.
   */
  async healthCheck(): Promise<{
    ok: boolean;
    enabled: boolean;
    detail?: string;
  }> {
    if (!this.enabled) {
      return { ok: true, enabled: false, detail: 'disabled by feature flag' };
    }
    if (!this.hasCredentials()) {
      return { ok: false, enabled: true, detail: 'missing credentials' };
    }
    try {
      type OrgsResp = { organizations?: Array<{ organization_id?: string }> };
      const resp = await this.request<OrgsResp>('GET', '/organizations');
      const orgIds = resp.organizations?.map((o) => o.organization_id) ?? [];
      if (!orgIds.includes(this.orgId)) {
        return {
          ok: false,
          enabled: true,
          detail: `org ${this.orgId} not visible to credentials`,
        };
      }
      return { ok: true, enabled: true, detail: 'auth + org access verified' };
    } catch (err) {
      return {
        ok: false,
        enabled: true,
        detail: (err as Error).message,
      };
    }
  }
}
