import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

/**
 * Zoho Books integration — accounting backend for Gun Galore.
 *
 * Design contract:
 *   - Buyer never sees a Books document. Their "Order Confirmation"
 *     is generated by Gun Galore's own platform (agent model — see
 *     the accounting-flow doc that went to the accountant).
 *   - Seller receives a Books-issued Tax Invoice for the commission
 *     when verification approves. The H&G-style Reference field
 *     spells out "Sold for R X - R Y (Platform Fee) = R Z Due to you".
 *   - When the seller payout fires, we mark the invoice paid in Books
 *     against the Client Funds Payable liability — closing the loop.
 *   - Raffle ticket purchases create Sales Receipts directly to buyer
 *     (raffles are NOT marketplace — Gun Galore is the actual seller).
 *   - Featured-slot bid wins create invoices to the winning seller.
 *
 * Failure handling:
 *   - Every public method is fire-and-forget from the caller's
 *     perspective. We never block the user-facing flow on a Books API
 *     call — Books going down can't delay payouts or break checkout.
 *   - Each Gun Galore record (Transaction, Ticket, FeaturedSlotBid)
 *     has zohoSyncStatus + zohoSyncError + zohoSyncLastAttemptAt
 *     fields. On failure we write FAILED + the error message; the
 *     admin panel shows these + a retry button.
 *   - Feature-flag gated: ZOHO_BOOKS_ENABLED=false skips every API
 *     call (records get status SKIPPED). Lets us deploy code without
 *     touching the live Books account until we explicitly turn it on.
 *
 * Auth:
 *   - Long-lived refresh token in env. Access tokens cached in-memory
 *     for ~55 minutes (Zoho gives 1 hour, we refresh a bit early).
 *   - 401 responses force a refresh and one retry.
 */
@Injectable()
export class ZohoBooksService {
  private readonly logger = new Logger(ZohoBooksService.name);

  private readonly enabled: boolean;
  private readonly clientId: string;
  private readonly clientSecret: string;
  private readonly refreshToken: string;
  private readonly orgId: string;
  private readonly apiDomain: string;
  private readonly accountsDomain: string;

  // In-memory access-token cache. Access tokens are short-lived (1h);
  // we refresh on demand and cache until just before expiry.
  private cachedAccessToken: string | null = null;
  private cachedAccessTokenExpiresAt = 0; // epoch ms

  constructor(private readonly prisma: PrismaService) {
    // Feature flag — leave OFF (false) by default until we're ready
    // to push real documents to Books. Set ZOHO_BOOKS_ENABLED=true
    // in .env when going live.
    this.enabled = process.env.ZOHO_BOOKS_ENABLED === 'true';
    this.clientId = process.env.ZOHO_BOOKS_CLIENT_ID ?? '';
    this.clientSecret = process.env.ZOHO_BOOKS_CLIENT_SECRET ?? '';
    this.refreshToken = process.env.ZOHO_BOOKS_REFRESH_TOKEN ?? '';
    this.orgId = process.env.ZOHO_BOOKS_ORG_ID ?? '';
    this.apiDomain =
      process.env.ZOHO_BOOKS_API_DOMAIN ?? 'https://www.zohoapis.com';
    this.accountsDomain =
      process.env.ZOHO_BOOKS_ACCOUNTS_DOMAIN ?? 'https://accounts.zoho.com';

    if (this.enabled && !this.hasCredentials()) {
      this.logger.error(
        'ZOHO_BOOKS_ENABLED=true but credentials are missing — disabling.',
      );
    }

    if (this.enabled) {
      this.logger.log(
        `Zoho Books integration ENABLED (org ${this.orgId}, api ${this.apiDomain})`,
      );
    } else {
      this.logger.log(
        'Zoho Books integration DISABLED (set ZOHO_BOOKS_ENABLED=true to turn on)',
      );
    }
  }

  /** Public — used by health monitor + admin panel. */
  isEnabled(): boolean {
    return this.enabled && this.hasCredentials();
  }

  private hasCredentials(): boolean {
    return !!(
      this.clientId &&
      this.clientSecret &&
      this.refreshToken &&
      this.orgId
    );
  }

  // ─── Access token management ─────────────────────────────────────

  /**
   * Returns a valid access token. Cached in-memory for ~55 minutes;
   * refreshes from the long-lived refresh token when stale.
   *
   * Don't call externally — every public method on this service that
   * hits the API uses this internally.
   */
  private async getAccessToken(): Promise<string> {
    const now = Date.now();
    // 60-second safety margin so we don't ship a token that expires
    // mid-request.
    if (this.cachedAccessToken && this.cachedAccessTokenExpiresAt > now + 60_000) {
      return this.cachedAccessToken;
    }

    const body = new URLSearchParams({
      grant_type: 'refresh_token',
      client_id: this.clientId,
      client_secret: this.clientSecret,
      refresh_token: this.refreshToken,
    });

    const res = await fetch(`${this.accountsDomain}/oauth/v2/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: body.toString(),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(
        `Zoho token refresh failed (${res.status}): ${text || res.statusText}`,
      );
    }

    const data = (await res.json()) as {
      access_token?: string;
      expires_in?: number;
      error?: string;
    };

    if (!data.access_token) {
      throw new Error(
        `Zoho token refresh returned no access_token: ${data.error ?? 'unknown'}`,
      );
    }

    // Cache. Zoho usually returns expires_in: 3600 (one hour).
    const expiresInMs = (data.expires_in ?? 3600) * 1000;
    this.cachedAccessToken = data.access_token;
    this.cachedAccessTokenExpiresAt = now + expiresInMs;
    this.logger.log(
      `Zoho access token refreshed (expires in ${Math.round(expiresInMs / 60000)}m)`,
    );
    return data.access_token;
  }

  // ─── Authenticated HTTP wrapper ──────────────────────────────────

  /**
   * Authenticated request to Zoho Books API.
   * Auto-prepends organization_id query param to every call.
   * On 401, forces a token refresh and retries once.
   */
  private async request<T>(
    method: 'GET' | 'POST' | 'PUT' | 'DELETE',
    path: string,
    body?: unknown,
  ): Promise<T> {
    return this.requestInner<T>(method, path, body, /* retried */ false);
  }

  private async requestInner<T>(
    method: 'GET' | 'POST' | 'PUT' | 'DELETE',
    path: string,
    body: unknown,
    retried: boolean,
  ): Promise<T> {
    const token = await this.getAccessToken();
    // Books REST API requires organization_id as a query param on
    // every endpoint. We append it ourselves so callers don't have to
    // remember.
    const sep = path.includes('?') ? '&' : '?';
    const url = `${this.apiDomain}/books/v3${path}${sep}organization_id=${this.orgId}`;

    const init: RequestInit = {
      method,
      headers: {
        Authorization: `Zoho-oauthtoken ${token}`,
        'Content-Type': 'application/json',
      },
    };
    if (body !== undefined) {
      init.body = JSON.stringify(body);
    }

    const res = await fetch(url, init);

    if (res.status === 401 && !retried) {
      // Token cache thinks it's valid but Zoho disagrees — force
      // refresh and retry once.
      this.logger.warn('Zoho returned 401 — forcing token refresh');
      this.cachedAccessToken = null;
      this.cachedAccessTokenExpiresAt = 0;
      return this.requestInner<T>(method, path, body, true);
    }

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(
        `Zoho Books ${method} ${path} failed (${res.status}): ${text || res.statusText}`,
      );
    }

    return (await res.json()) as T;
  }

  // ─── Contact (customer) management ───────────────────────────────

  /**
   * Find-or-create the Books contact for a Gun Galore user.
   *
   * Strategy:
   *   - If user.zohoContactId is set, return it (already created).
   *   - Else create a new contact via API and save the returned ID
   *     onto the User record.
   *
   * Used for both sellers (we invoice them for commission) and
   * raffle-ticket buyers (we issue them Sales Receipts).
   *
   * Idempotent — concurrent calls for the same user are safe; the
   * unique constraint isn't enforced at DB level but the User row
   * update is atomic, and Zoho's create-contact returns 400 if a
   * duplicate email is detected, which we catch + look up by email.
   */
  async ensureContact(
    userId: string,
    fallbackEmail?: string,
  ): Promise<string | null> {
    if (!this.isEnabled()) return null;

    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: {
        id: true,
        zohoContactId: true,
        email: true,
        firstName: true,
        lastName: true,
        username: true,
        phone: true,
        addrStreet: true,
        addrSuburb: true,
        addrCity: true,
        addrPostalCode: true,
        addrProvince: true,
      },
    });
    if (!user) return null;
    if (user.zohoContactId) return user.zohoContactId;

    const displayName =
      [user.firstName, user.lastName].filter(Boolean).join(' ') ||
      user.username ||
      fallbackEmail ||
      user.email;

    const payload = {
      contact_name: displayName,
      contact_type: 'customer',
      // Books treats this list as the people you can email invoices
      // to. We use the user's primary email.
      contact_persons: [
        {
          first_name: user.firstName ?? '',
          last_name: user.lastName ?? user.username ?? '',
          email: user.email,
          phone: user.phone ?? '',
          is_primary_contact: true,
        },
      ],
      // Address block — used as the bill-to on invoices.
      billing_address: {
        address: user.addrStreet ?? '',
        street2: user.addrSuburb ?? '',
        city: user.addrCity ?? '',
        state: user.addrProvince ?? '',
        zip: user.addrPostalCode ?? '',
        country: 'South Africa',
      },
      // Notes field — surfaces the Gun Galore user ID for the
      // accountant to cross-reference with our admin panel.
      notes: `Gun Galore user ID: ${user.id} / username: @${user.username ?? '(none)'}`,
    };

    type CreateContactResp = {
      contact?: { contact_id?: string };
      code?: number;
      message?: string;
    };
    const resp = await this.request<CreateContactResp>(
      'POST',
      '/contacts',
      payload,
    );

    const contactId = resp.contact?.contact_id;
    if (!contactId) {
      throw new Error(
        `Zoho Books contact create returned no contact_id: ${resp.message ?? 'unknown'}`,
      );
    }

    // Save the ID on the user so we don't recreate next time.
    await this.prisma.user.update({
      where: { id: user.id },
      data: { zohoContactId: contactId },
    });

    this.logger.log(
      `Created Books contact ${contactId} for user ${user.id} (${displayName})`,
    );
    return contactId;
  }

  // ─── Account ID lookup ───────────────────────────────────────────

  /**
   * Find a Books Chart-of-Accounts account by name.
   * Used at startup time (or on first invoice) to resolve account
   * names like "Commission Revenue" or "Client Funds Payable" to the
   * Books account IDs the API needs.
   *
   * Cached in-memory after first lookup (account IDs don't change).
   */
  private accountIdCache: Map<string, string> = new Map();

  async getAccountIdByName(accountName: string): Promise<string | null> {
    if (!this.isEnabled()) return null;
    const cached = this.accountIdCache.get(accountName);
    if (cached) return cached;

    type ChartOfAccountsResp = {
      chartofaccounts?: Array<{
        account_id?: string;
        account_name?: string;
      }>;
    };
    const resp = await this.request<ChartOfAccountsResp>(
      'GET',
      '/chartofaccounts',
    );

    const accounts = resp.chartofaccounts ?? [];
    // Cache them all while we have the list — we'll need several.
    for (const acc of accounts) {
      if (acc.account_id && acc.account_name) {
        this.accountIdCache.set(acc.account_name, acc.account_id);
      }
    }
    return this.accountIdCache.get(accountName) ?? null;
  }

  // ─── Public document-creation methods ────────────────────────────
  // ZB-4 onwards wires these into the actual hooks. They're stubs
  // here so ZB-3 (this file) compiles cleanly + the integration
  // boundaries are documented.

  /**
   * Commission invoice: Gun Galore → Seller for the platform fee on
   * a marketplace sale. Called from the verification-APPROVED hook.
   *
   * Idempotent: skips if zohoCommissionInvoiceId already set.
   * Skips silently for PRIVATE_ARRANGE (no commission on that flow —
   * funds release direct to seller at payment capture, no agent
   * relationship to invoice).
   *
   * On any error: writes FAILED status + error message to the
   * transaction row. Caller doesn't need to try/catch — this method
   * never throws.
   */
  async createCommissionInvoice(transactionId: string): Promise<void> {
    if (!this.isEnabled()) return;
    const tx = await this.prisma.transaction.findUnique({
      where: { id: transactionId },
      include: {
        seller: {
          select: {
            id: true,
            email: true,
            username: true,
            firstName: true,
            lastName: true,
          },
        },
        listing: {
          select: {
            title: true,
            referenceNumber: true,
          },
        },
      },
    });
    if (!tx) return;
    // Idempotency — if we've already created the invoice, no-op.
    if (tx.zohoCommissionInvoiceId) return;
    // PRIVATE_ARRANGE has no platform commission invoice (we don't
    // hold funds for it). Skip silently.
    if (tx.shippingMethod === 'PRIVATE_ARRANGE') {
      await this.markSkipped(
        transactionId,
        'PRIVATE_ARRANGE — no commission invoice',
      );
      return;
    }
    if (tx.commissionZar <= 0) {
      await this.markSkipped(transactionId, 'commissionZar is zero');
      return;
    }

    await this.markPending(transactionId);

    try {
      const contactId = await this.ensureContact(tx.seller.id, tx.seller.email);
      if (!contactId) {
        throw new Error('Could not resolve Books contact for seller');
      }

      const commissionRand = tx.commissionZar / 100;
      const listingPriceRand = tx.listingPrice / 100;
      const sellerPayoutRand = tx.sellerPayout / 100;
      const orderRef =
        tx.listing.referenceNumber ?? tx.id.slice(-8).toUpperCase();

      // H&G-style reference: spells out the math in plain language
      // so the seller sees "what I sold for - what you took = what I
      // get". This is exactly what the H&G invoice we mirrored does.
      const reference = `Sold for ${this.formatRand(listingPriceRand)} - ${this.formatRand(commissionRand)} (Platform Fee) = ${this.formatRand(sellerPayoutRand)} Due to you`;

      // Resolve Commission Revenue account so Books posts the income
      // to the right ledger row. Cached after first lookup.
      const commissionAccountId = await this.getAccountIdByName(
        'Commission Revenue',
      );
      if (!commissionAccountId) {
        throw new Error(
          'Commission Revenue account not found in Books chart-of-accounts',
        );
      }

      const today = new Date().toISOString().slice(0, 10);

      type CreateInvoiceResp = {
        invoice?: { invoice_id?: string; invoice_number?: string };
        code?: number;
        message?: string;
      };

      // P0.7 — the payment-processing fee GG retains (1.5% EFT handling
      // today; card rate under a gateway) is real revenue but was never
      // documented in Books. When the SELLER absorbs it (passFeeToBuyer
      // false — the default), it is deducted from their payout exactly
      // like the commission, so it belongs on this same invoice as a
      // second line. When the BUYER paid it on top, invoicing the seller
      // would misstate who bore it — excluded here; the accountant picks
      // those up from the reconciliation. Posts to a dedicated
      // "Processing Fee Revenue" account when one exists, else falls
      // back to Commission Revenue.
      const lineItems: Array<{
        name: string;
        description: string;
        rate: number;
        quantity: number;
        account_id: string;
      }> = [
        {
          name: 'Platform Fee',
          description: `${orderRef} — ${tx.listing.title}`,
          rate: commissionRand,
          quantity: 1,
          account_id: commissionAccountId,
        },
      ];
      if (!tx.passFeeToBuyer && tx.processingFee > 0) {
        const processingAccountId =
          (await this.getAccountIdByName('Processing Fee Revenue')) ??
          commissionAccountId;
        lineItems.push({
          name: 'Payment Processing Fee',
          description: `${orderRef} — payment handling`,
          rate: tx.processingFee / 100,
          quantity: 1,
          account_id: processingAccountId,
        });
      }

      const payload = {
        customer_id: contactId,
        reference_number: reference,
        date: today,
        due_date: today,
        line_items: lineItems,
        notes: `${reference}.\nGun Galore transaction reference: ${orderRef}`,
        // Skip tax — we're pre-VAT. When VAT-registered this flips
        // to is_inclusive_tax: false + tax_id on each line.
      };

      const resp = await this.request<CreateInvoiceResp>(
        'POST',
        '/invoices',
        payload,
      );

      const invoiceId = resp.invoice?.invoice_id;
      if (!invoiceId) {
        throw new Error(
          `Books invoice create returned no invoice_id: ${resp.message ?? 'unknown'}`,
        );
      }

      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoCommissionInvoiceId: invoiceId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Created commission invoice ${resp.invoice?.invoice_number ?? invoiceId} for tx ${transactionId} (R${commissionRand.toFixed(2)})`,
      );
    } catch (err) {
      await this.markFailed(transactionId, err as Error);
    }
  }

  /**
   * Records payment against the commission invoice using Client
   * Funds Payable as the source — effectively draining the held
   * funds liability by the commission amount and marking the
   * invoice as Paid in one Books operation.
   *
   * Called after createCommissionInvoice (typically in the same
   * verification-APPROVED hook). Idempotent: skips if
   * zohoCommissionPaymentId already set, or if the invoice ID is
   * not yet set (createCommissionInvoice must run first).
   *
   * Like createCommissionInvoice, never throws — failures are
   * persisted as FAILED status on the transaction.
   */
  async markCommissionInvoicePaid(transactionId: string): Promise<void> {
    if (!this.isEnabled()) return;
    const tx = await this.prisma.transaction.findUnique({
      where: { id: transactionId },
      include: {
        seller: { select: { id: true } },
      },
    });
    if (!tx) return;
    if (!tx.zohoCommissionInvoiceId) return; // invoice must exist first
    if (tx.zohoCommissionPaymentId) return; // already marked paid

    try {
      const sellerContactId = await this.ensureContact(tx.seller.id);
      if (!sellerContactId) {
        throw new Error('Could not resolve seller contact for payment');
      }

      const cfpAccountId = await this.getAccountIdByName(
        'Client Funds Payable',
      );
      if (!cfpAccountId) {
        throw new Error(
          'Client Funds Payable account not found in Books chart-of-accounts',
        );
      }

      // P0.7 (review fix) — settle what the INVOICE actually says, not a
      // recomputation from tx fields. Legacy pre-deploy invoices carry a
      // single commission-only line; recomputing commission+fee here would
      // over-apply, Zoho would reject the payment, and every retry would
      // fail identically (permanent FAILED loop). Reading the live balance
      // is correct for both cohorts and for any future line changes.
      type GetInvoiceResp = {
        invoice?: { balance?: number; total?: number; status?: string };
      };
      const inv = await this.request<GetInvoiceResp>(
        'GET',
        `/invoices/${tx.zohoCommissionInvoiceId}`,
      );
      const invoiceTotalRand = inv.invoice?.balance ?? 0;
      if (invoiceTotalRand <= 0) {
        // Nothing outstanding (already settled in Books, e.g. by hand).
        // Stamp a sentinel so the idempotency guard stops re-running this.
        await this.prisma.transaction.update({
          where: { id: transactionId },
          data: {
            zohoCommissionPaymentId: 'SETTLED_EXTERNALLY',
            zohoSyncStatus: 'OK',
            zohoSyncError: null,
            zohoSyncLastAttemptAt: new Date(),
          },
        });
        this.logger.log(
          `Commission invoice for tx ${transactionId} already has zero balance — stamped settled`,
        );
        return;
      }
      const today = new Date().toISOString().slice(0, 10);
      const orderRef = tx.id.slice(-8).toUpperCase();

      type CreatePaymentResp = {
        payment?: { payment_id?: string };
        code?: number;
        message?: string;
      };
      const payload = {
        customer_id: sellerContactId,
        payment_mode: 'Other',
        amount: invoiceTotalRand,
        date: today,
        reference_number: `Settled from buyer funds — ${orderRef}`,
        // The deposit_to_account is where the money "came from" —
        // in our case from the Client Funds Payable liability, NOT
        // from a real bank account. Books may need this set up as
        // a "Bank" type account in their CoA for this to work; if
        // it errors here we'll know to either reclassify CFP or
        // switch to a manual-journal posting pattern.
        deposit_to_account_id: cfpAccountId,
        invoices: [
          {
            invoice_id: tx.zohoCommissionInvoiceId,
            amount_applied: invoiceTotalRand,
          },
        ],
        description:
          'Commission settled by draining buyer funds held in trust',
      };

      const resp = await this.request<CreatePaymentResp>(
        'POST',
        '/customerpayments',
        payload,
      );

      const paymentId = resp.payment?.payment_id;
      if (!paymentId) {
        throw new Error(
          `Books payment create returned no payment_id: ${resp.message ?? 'unknown'}`,
        );
      }

      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoCommissionPaymentId: paymentId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Marked commission invoice paid for tx ${transactionId} (R${invoiceTotalRand.toFixed(2)})`,
      );
    } catch (err) {
      await this.markFailed(transactionId, err as Error);
    }
  }

  // ─── Status helpers ──────────────────────────────────────────────

  private async markPending(transactionId: string): Promise<void> {
    await this.prisma.transaction.update({
      where: { id: transactionId },
      data: {
        zohoSyncStatus: 'PENDING',
        zohoSyncLastAttemptAt: new Date(),
      },
    });
  }

  private async markSkipped(
    transactionId: string,
    reason: string,
  ): Promise<void> {
    await this.prisma.transaction.update({
      where: { id: transactionId },
      data: {
        zohoSyncStatus: 'SKIPPED',
        zohoSyncError: reason,
        zohoSyncLastAttemptAt: new Date(),
      },
    });
  }

  private async markFailed(
    transactionId: string,
    err: Error,
  ): Promise<void> {
    const message = err.message.slice(0, 1000);
    this.logger.error(
      `Zoho Books sync FAILED for tx ${transactionId}: ${message}`,
    );
    try {
      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoSyncStatus: 'FAILED',
          zohoSyncError: message,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
    } catch (writeErr) {
      this.logger.error(
        `Could not write FAILED status to tx ${transactionId}: ${(writeErr as Error).message}`,
      );
    }
  }

  private formatRand(amount: number): string {
    // R 10,000 / R 1,500.50 / R 0.99 — matches H&G invoice style.
    // Use en-US locale so the thousands separator is a regular comma
    // (ASCII U+002C). Earlier version used en-ZA which gave us a
    // non-breaking space (U+00A0) — Zoho's PDF font doesn't have a
    // glyph for that and renders it as U+FFFD replacement character
    // ("R 10�000" instead of "R 10,000").
    const formatted = amount.toLocaleString('en-US', {
      minimumFractionDigits: amount % 1 === 0 ? 0 : 2,
      maximumFractionDigits: 2,
    });
    return `R ${formatted}`;
  }

  /**
   * Credit Note for refund: reverses the commission invoice when a
   * transaction is refunded by admin.
   *
   * Books semantics:
   *   - Credit Note is a tax document (the inverse of an Invoice)
   *   - Created against the seller (same contact as the original
   *     invoice), with one line item mirroring the commission
   *   - We then APPLY the credit note to the original invoice so
   *     Books shows the invoice as cancelled/refunded
   *
   * Idempotent: skips if zohoCreditNoteId already set.
   *
   * Skipped (with logged reason) if:
   *   - No original commission invoice exists (PRIVATE_ARRANGE
   *     refunds, or refunds of transactions that never reached
   *     verification-approved state)
   *   - Feature flag is off
   *
   * Never throws — failures persist as zohoSyncStatus=FAILED so
   * admin can retry from the dossier.
   */
  async createCommissionCreditNote(
    transactionId: string,
    refundReason?: string,
  ): Promise<void> {
    if (!this.isEnabled()) return;
    const tx = await this.prisma.transaction.findUnique({
      where: { id: transactionId },
      include: {
        seller: { select: { id: true, email: true } },
        listing: { select: { title: true, referenceNumber: true } },
      },
    });
    if (!tx) return;
    if (tx.zohoCreditNoteId) return; // already credited
    if (!tx.zohoCommissionInvoiceId) {
      await this.markSkipped(
        transactionId,
        'No commission invoice to credit (refund pre-approval or PRIVATE_ARRANGE)',
      );
      return;
    }

    try {
      const contactId = await this.ensureContact(tx.seller.id, tx.seller.email);
      if (!contactId) {
        throw new Error('Could not resolve Books contact for seller');
      }
      const commissionAccountId = await this.getAccountIdByName(
        'Commission Revenue',
      );
      if (!commissionAccountId) {
        throw new Error(
          'Commission Revenue account not found in Books chart-of-accounts',
        );
      }

      const commissionRand = tx.commissionZar / 100;
      const orderRef = tx.listing.referenceNumber ?? tx.id.slice(-8).toUpperCase();
      const reason = (refundReason ?? 'Transaction refunded by admin').slice(0, 200);
      const reference = `Refund — ${orderRef} (reversing commission of ${this.formatRand(commissionRand)})`;
      const today = new Date().toISOString().slice(0, 10);

      type CreateCreditNoteResp = {
        creditnote?: { creditnote_id?: string; creditnote_number?: string };
        message?: string;
      };
      const payload = {
        customer_id: contactId,
        reference_number: reference,
        date: today,
        line_items: [
          {
            name: 'Platform Fee — refund',
            description: `${orderRef} — ${tx.listing.title} (${reason})`,
            rate: commissionRand,
            quantity: 1,
            account_id: commissionAccountId,
          },
        ],
        notes: `${reference}.\nGun Galore transaction reference: ${orderRef}\nReason: ${reason}`,
      };

      const resp = await this.request<CreateCreditNoteResp>(
        'POST',
        '/creditnotes',
        payload,
      );

      const creditNoteId = resp.creditnote?.creditnote_id;
      if (!creditNoteId) {
        throw new Error(
          `Books credit-note create returned no creditnote_id: ${resp.message ?? 'unknown'}`,
        );
      }

      // Apply the credit note against the original invoice so Books
      // shows the invoice as effectively cancelled — without this,
      // both rows sit independently and the seller's open-balance
      // doesn't zero out.
      try {
        await this.request<{ message?: string }>(
          'POST',
          `/creditnotes/${creditNoteId}/invoices`,
          {
            invoices: [
              {
                invoice_id: tx.zohoCommissionInvoiceId,
                amount_applied: commissionRand,
              },
            ],
          },
        );
      } catch (applyErr) {
        // Non-fatal — the credit note exists, admin can manually
        // apply it from the Books UI if this step failed. Log it
        // but don't reverse the whole operation.
        this.logger.warn(
          `Credit note ${creditNoteId} created but apply-to-invoice failed: ${(applyErr as Error).message}`,
        );
      }

      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoCreditNoteId: creditNoteId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Created refund credit note ${resp.creditnote?.creditnote_number ?? creditNoteId} for tx ${transactionId} (R${commissionRand.toFixed(2)})`,
      );
    } catch (err) {
      await this.markFailed(transactionId, err as Error);
    }
  }

  /**
   * Sales Receipt for a raffle ticket purchase.
   *
   * Raffles are NOT marketplace — Gun Galore IS the seller, the
   * buyer is the customer. So the Books document is a Sales Receipt
   * (paid invoice in one step), not the commission invoice flow we
   * use for marketplace sales.
   *
   * Called from RafflesService.confirmTickets() with the list of
   * Ticket.id values that were just confirmed in one batch (one
   * Peach payment = one receipt covering N tickets).
   *
   * Idempotent — if ANY of the tickets in the batch already has a
   * zohoSalesReceiptId we treat the batch as done (the batch was
   * synced previously) and no-op.
   *
   * Never throws — failures persist as zohoSyncStatus=FAILED on
   * each ticket so admin can retry from the dossier.
   */
  async createRaffleTicketSalesReceipt(
    ticketIds: string[],
  ): Promise<void> {
    if (!this.isEnabled() || ticketIds.length === 0) return;

    const tickets = await this.prisma.ticket.findMany({
      where: { id: { in: ticketIds } },
      include: {
        buyer: { select: { id: true, email: true, username: true, firstName: true, lastName: true } },
        raffle: { select: { id: true, title: true, referenceNumber: true } },
      },
    });
    if (tickets.length === 0) return;

    // Idempotency — if any ticket already has a receipt ID, the
    // batch has already been synced. No-op.
    if (tickets.some((t) => t.zohoSalesReceiptId)) return;

    // Postal tickets (amountCents = 0) skip Books — no money changed
    // hands, no accounting entry needed.
    const paidTickets = tickets.filter((t) => t.amountCents > 0);
    if (paidTickets.length === 0) return;

    // Sanity — all tickets in the batch should share the same buyer
    // and raffle (set by confirmTickets() — one peachPaymentId batch
    // = one buyer + one raffle).
    const buyer = paidTickets[0].buyer;
    const raffle = paidTickets[0].raffle;
    if (!buyer || !raffle) return;
    const totalCents = paidTickets.reduce((s, t) => s + t.amountCents, 0);
    const totalRand = totalCents / 100;
    const unitRand = paidTickets[0].amountCents / 100;
    const raffleRef = raffle.referenceNumber ?? raffle.id.slice(-8).toUpperCase();

    try {
      const contactId = await this.ensureContact(buyer.id, buyer.email);
      if (!contactId) {
        throw new Error('Could not resolve Books contact for buyer');
      }
      const raffleAccountId = await this.getAccountIdByName(
        'Raffle Ticket Revenue',
      );
      if (!raffleAccountId) {
        throw new Error(
          'Raffle Ticket Revenue account not found in Books chart-of-accounts',
        );
      }
      // P1.3 — manual-EFT money lands straight in FNB, so the bank
      // account comes FIRST; "Peach Pending" stays only as a fallback
      // for CoAs that predate the manual rail.
      const depositAccountId =
        (await this.getAccountIdByName('Bank — FNB Business')) ??
        (await this.getAccountIdByName('Bank — Peach Pending'));
      if (!depositAccountId) {
        throw new Error(
          'No deposit account found in Books (need "Bank — Peach Pending" or "Bank — FNB Business")',
        );
      }

      const today = new Date().toISOString().slice(0, 10);
      const reference = `Raffle ticket purchase — ${raffleRef} (${paidTickets.length} ${paidTickets.length === 1 ? 'ticket' : 'tickets'})`;

      type CreateSalesReceiptResp = {
        salesreceipt?: { salesreceipt_id?: string; salesreceipt_number?: string };
        message?: string;
      };
      const payload = {
        customer_id: contactId,
        reference_number: reference,
        date: today,
        line_items: [
          {
            name: 'Raffle Ticket',
            description: `${raffleRef} — ${raffle.title} (x${paidTickets.length})`,
            rate: unitRand,
            quantity: paidTickets.length,
            account_id: raffleAccountId,
          },
        ],
        // Sales Receipts are paid-at-issue — deposit_to is the
        // account that holds the cash.
        payment_mode: 'Other',
        deposit_to_account_id: depositAccountId,
        notes: `${reference}.\nTotal: R${totalRand.toFixed(2)} (${paidTickets.length} x R${unitRand.toFixed(2)})`,
      };

      const resp = await this.request<CreateSalesReceiptResp>(
        'POST',
        '/salesreceipts',
        payload,
      );

      const receiptId = resp.salesreceipt?.salesreceipt_id;
      if (!receiptId) {
        throw new Error(
          `Books sales-receipt create returned no salesreceipt_id: ${resp.message ?? 'unknown'}`,
        );
      }

      // Stamp the receipt ID on every ticket in the batch so we
      // can look up the receipt from any one of them.
      await this.prisma.ticket.updateMany({
        where: { id: { in: paidTickets.map((t) => t.id) } },
        data: {
          zohoSalesReceiptId: receiptId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Created raffle sales receipt ${resp.salesreceipt?.salesreceipt_number ?? receiptId} (R${totalRand.toFixed(2)}, ${paidTickets.length} tickets, raffle ${raffleRef})`,
      );
    } catch (err) {
      await this.markRaffleTicketsFailed(
        paidTickets.map((t) => t.id),
        err as Error,
      );
    }
  }

  /**
   * P1.1 — Sales Receipt for a paid subscription period (manual EFT).
   * Fired by SubscriptionsService.confirmPayment. Idempotent via
   * SubscriptionCharge.zohoReceiptId. Never throws.
   */
  async createSubscriptionSalesReceipt(chargeId: string): Promise<void> {
    if (!this.isEnabled()) return;
    const charge = await this.prisma.subscriptionCharge.findUnique({
      where: { id: chargeId },
      include: {
        subscription: {
          include: {
            user: { select: { id: true, email: true, username: true } },
          },
        },
      },
    });
    if (!charge || charge.zohoReceiptId) return; // missing or already synced
    if (charge.status !== 'SUCCEEDED' || charge.amountCents <= 0) return;

    const user = charge.subscription.user;
    const tier = charge.tierPurchased ?? charge.subscription.tier;
    const amountRand = charge.amountCents / 100;
    const reference = `Ask GG ${tier} subscription — ${charge.orderReference ?? charge.id.slice(-8).toUpperCase()} (${charge.periodDays} days)`;

    try {
      const contactId = await this.ensureContact(user.id, user.email);
      if (!contactId) throw new Error('Could not resolve Books contact');
      const revenueAccountId =
        (await this.getAccountIdByName('Subscription Revenue')) ??
        (await this.getAccountIdByName('Commission Revenue'));
      if (!revenueAccountId) {
        throw new Error(
          'No revenue account found in Books (need "Subscription Revenue" or "Commission Revenue")',
        );
      }
      // Manual-EFT money lands straight in FNB — prefer the bank account.
      const depositAccountId =
        (await this.getAccountIdByName('Bank — FNB Business')) ??
        (await this.getAccountIdByName('Bank — Peach Pending'));
      if (!depositAccountId) {
        throw new Error(
          'No deposit account found in Books (need "Bank — FNB Business" or "Bank — Peach Pending")',
        );
      }
      const today = new Date().toISOString().slice(0, 10);
      type CreateSalesReceiptResp = {
        salesreceipt?: { salesreceipt_id?: string; salesreceipt_number?: string };
        message?: string;
      };
      const resp = await this.request<CreateSalesReceiptResp>(
        'POST',
        '/salesreceipts',
        {
          customer_id: contactId,
          reference_number: reference,
          date: today,
          line_items: [
            {
              name: `Ask GG ${tier} subscription`,
              description: reference,
              rate: amountRand,
              quantity: 1,
              account_id: revenueAccountId,
            },
          ],
          payment_mode: 'Bank Transfer',
          deposit_to_account_id: depositAccountId,
          notes: `${reference}.\nPaid by EFT (reference-matched).`,
        },
      );
      const receiptId = resp.salesreceipt?.salesreceipt_id;
      if (!receiptId) {
        throw new Error(
          `Books sales-receipt create returned no id: ${resp.message ?? 'unknown'}`,
        );
      }
      await this.prisma.subscriptionCharge.update({
        where: { id: chargeId },
        data: { zohoReceiptId: receiptId },
      });
      this.logger.log(
        `Created subscription sales receipt ${resp.salesreceipt?.salesreceipt_number ?? receiptId} (R${amountRand.toFixed(2)}, ${tier}, user ${user.username ?? user.id})`,
      );
    } catch (err) {
      // No zohoSync* columns on SubscriptionCharge — record the failure in
      // errorMessage (the charge itself already SUCCEEDED financially).
      const message = (err as Error).message.slice(0, 900);
      this.logger.error(`Zoho subscription receipt FAILED for ${chargeId}: ${message}`);
      await this.prisma.subscriptionCharge
        .update({
          where: { id: chargeId },
          data: { errorMessage: `Zoho receipt failed: ${message}` },
        })
        .catch(() => undefined);
    }
  }

  /**
   * P1.3 — Sales Receipts for the two flat swap leg fees GG retained
   * (courier service fee / firearm handling fee, snapshotted on the
   * Swap as swapFeeInitiator / swapFeeOwner and collected inside each
   * party's funding EFT). Booked at swap COMPLETION — the only point
   * where the fees are definitively earned (any earlier cancel/unwind
   * reimburses the payer in full). One receipt per paying party so the
   * Books entries mirror the two EFTs that actually landed in FNB.
   * Idempotent per side via zoho*FeeReceiptId. Never throws.
   */
  async createSwapFeeReceipts(swapId: string): Promise<void> {
    if (!this.isEnabled()) return;
    try {
      const swap = await this.prisma.swap.findUnique({
        where: { id: swapId },
        select: {
          id: true,
          status: true,
          swapFeeInitiator: true,
          swapFeeOwner: true,
          initiatorFundingRef: true,
          ownerFundingRef: true,
          zohoInitiatorFeeReceiptId: true,
          zohoOwnerFeeReceiptId: true,
          initiator: { select: { id: true, email: true } },
          owner: { select: { id: true, email: true } },
        },
      });
      if (!swap || swap.status !== 'COMPLETED') return;

      const revenueAccountId =
        (await this.getAccountIdByName('Swap Service Revenue')) ??
        (await this.getAccountIdByName('Commission Revenue'));
      if (!revenueAccountId) {
        throw new Error(
          'No revenue account found in Books (need "Swap Service Revenue" or "Commission Revenue")',
        );
      }
      const depositAccountId =
        (await this.getAccountIdByName('Bank — FNB Business')) ??
        (await this.getAccountIdByName('Bank — Peach Pending'));
      if (!depositAccountId) {
        throw new Error(
          'No deposit account found in Books (need "Bank — FNB Business" or "Bank — Peach Pending")',
        );
      }

      const sides: Array<{
        key: 'initiator' | 'owner';
        feeCents: number;
        alreadyId: string | null;
        userId: string;
        email: string;
        fundingRef: string | null;
        column: 'zohoInitiatorFeeReceiptId' | 'zohoOwnerFeeReceiptId';
      }> = [
        {
          key: 'initiator',
          feeCents: swap.swapFeeInitiator,
          alreadyId: swap.zohoInitiatorFeeReceiptId,
          userId: swap.initiator.id,
          email: swap.initiator.email,
          fundingRef: swap.initiatorFundingRef,
          column: 'zohoInitiatorFeeReceiptId',
        },
        {
          key: 'owner',
          feeCents: swap.swapFeeOwner,
          alreadyId: swap.zohoOwnerFeeReceiptId,
          userId: swap.owner.id,
          email: swap.owner.email,
          fundingRef: swap.ownerFundingRef,
          column: 'zohoOwnerFeeReceiptId',
        },
      ];

      const today = new Date().toISOString().slice(0, 10);
      type CreateSalesReceiptResp = {
        salesreceipt?: { salesreceipt_id?: string; salesreceipt_number?: string };
        message?: string;
      };

      for (const side of sides) {
        if (side.alreadyId || side.feeCents <= 0) continue;
        const contactId = await this.ensureContact(side.userId, side.email);
        if (!contactId) {
          throw new Error(`Could not resolve Books contact for swap ${side.key}`);
        }
        const reference = `Swap service fee — ${side.fundingRef ?? swap.id.slice(-8).toUpperCase()}`;
        const resp = await this.request<CreateSalesReceiptResp>(
          'POST',
          '/salesreceipts',
          {
            customer_id: contactId,
            reference_number: reference,
            date: today,
            line_items: [
              {
                name: 'Swap leg service fee',
                description: `${reference} — flat per-leg fee collected inside the funding EFT; recognised at swap completion.`,
                rate: side.feeCents / 100,
                quantity: 1,
                account_id: revenueAccountId,
              },
            ],
            payment_mode: 'Bank Transfer',
            deposit_to_account_id: depositAccountId,
            notes: `${reference}. Swap ${swap.id}.`,
          },
        );
        const receiptId = resp.salesreceipt?.salesreceipt_id;
        if (!receiptId) {
          throw new Error(
            `Books sales-receipt create returned no id: ${resp.message ?? 'unknown'}`,
          );
        }
        await this.prisma.swap.update({
          where: { id: swap.id },
          data: { [side.column]: receiptId },
        });
        this.logger.log(
          `Created swap fee receipt ${resp.salesreceipt?.salesreceipt_number ?? receiptId} (R${(side.feeCents / 100).toFixed(2)}, ${side.key}, swap ${swap.id})`,
        );
      }
    } catch (err) {
      // No zohoSync* columns on Swap — log only. The failure is DETECTED by
      // getZohoFailedSyncs (COMPLETED swap with a fee>0 side whose receipt id
      // is still null) and RE-FIRED by retryMissingSwapFeeReceipts (this is
      // idempotent per side, so a retry can only fill the missing receipt).
      this.logger.error(
        `Zoho swap fee receipts FAILED for ${swapId}: ${(err as Error).message}`,
      );
    }
  }

  /**
   * P1.3 — hourly retry for swap leg-fee receipts that failed at completion.
   * createSwapFeeReceipts is idempotent per side (guarded by
   * zoho*FeeReceiptId), so re-firing it for a COMPLETED swap with a missing
   * receipt can only fill the gap. Bounded per run; never throws.
   */
  async retryMissingSwapFeeReceipts(limit = 25): Promise<number> {
    if (!this.isEnabled()) return 0;
    try {
      const due = await this.prisma.swap.findMany({
        where: {
          status: 'COMPLETED',
          OR: [
            { swapFeeInitiator: { gt: 0 }, zohoInitiatorFeeReceiptId: null },
            { swapFeeOwner: { gt: 0 }, zohoOwnerFeeReceiptId: null },
          ],
        },
        orderBy: { completedAt: 'asc' },
        take: limit,
        select: { id: true },
      });
      for (const s of due) {
        await this.createSwapFeeReceipts(s.id);
      }
      if (due.length > 0) {
        this.logger.log(
          `retryMissingSwapFeeReceipts: re-fired ${due.length} swap fee receipt(s)`,
        );
      }
      return due.length;
    } catch (err) {
      this.logger.error(
        `retryMissingSwapFeeReceipts failed: ${(err as Error).message}`,
      );
      return 0;
    }
  }

  private async markRaffleTicketsFailed(
    ticketIds: string[],
    err: Error,
  ): Promise<void> {
    const message = err.message.slice(0, 1000);
    this.logger.error(
      `Zoho Books raffle sync FAILED for tickets [${ticketIds.length}]: ${message}`,
    );
    try {
      await this.prisma.ticket.updateMany({
        where: { id: { in: ticketIds } },
        data: {
          zohoSyncStatus: 'FAILED',
          zohoSyncError: message,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
    } catch (writeErr) {
      this.logger.error(
        `Could not write FAILED status to tickets: ${(writeErr as Error).message}`,
      );
    }
  }

  /**
   * Invoice for a featured-slot fee.
   *
   * Called from FeaturedService.bindListingToSlot() once the winning
   * bid is committed (status=WON, paidAt set). Issues the seller a
   * paid invoice for the slot fee — analogous to the commission
   * invoice flow but for featured-listing service revenue.
   *
   * Idempotent — skips if zohoInvoiceId already set on the bid.
   * Never throws — failures stamp FAILED on the bid row.
   */
  async createFeaturedSlotInvoice(bidId: string): Promise<void> {
    if (!this.isEnabled()) return;

    // M16 — the entire body runs inside try so the leading findUnique +
    // related lookups can't throw past the bare void caller in
    // featured.service.ts. Previously the findUnique sat OUTSIDE the
    // try block, so a DB hiccup there became an unhandled rejection
    // on a fire-and-forget call site.
    try {
      const bid = await this.prisma.featuredSlotBid.findUnique({
        where: { id: bidId },
        include: {
          bidder: { select: { id: true, email: true } },
          auction: { select: { slotId: true } },
        },
      });
      if (!bid) return;
      if (bid.zohoInvoiceId) return;
      // Phase E2 — receipt uses the cents we actually CHARGED
      // (post-discount), falling back to the face bid for legacy
      // rows from before the discount fields existed.
      const billableCents = bid.chargedAmountCents ?? bid.amountCents;
      if (billableCents <= 0) return;

      const contactId = await this.ensureContact(bid.bidder.id, bid.bidder.email);
      if (!contactId) {
        throw new Error('Could not resolve Books contact for winning bidder');
      }
      const featuredAccountId = await this.getAccountIdByName(
        'Featured-Slot Revenue',
      );
      if (!featuredAccountId) {
        throw new Error(
          'Featured-Slot Revenue account not found in Books chart-of-accounts',
        );
      }
      // P1.3 — EFT-paid slot fees land in FNB; bank account first.
      const depositAccountId =
        (await this.getAccountIdByName('Bank — FNB Business')) ??
        (await this.getAccountIdByName('Bank — Peach Pending'));

      const feeRand = billableCents / 100;
      const today = new Date().toISOString().slice(0, 10);
      const bidRef = bid.id.slice(-8).toUpperCase();
      // Phase E2 — surface the discount on the receipt so the
      // operator can see it in Books without re-doing the math.
      const discountSuffix =
        bid.discountPercent && bid.discountPercent > 0
          ? ` — GG+ ${bid.discountPercent}% off (face R${(bid.amountCents / 100).toFixed(0)})`
          : '';
      const reference = `Featured-slot ${bid.tier} — slot ${bid.auction?.slotId ?? 'unknown'} — bid ${bidRef}${discountSuffix}`;

      // Featured-slot fees are paid at the moment the bid commits
      // (the seller's card was already charged by Peach). So we use
      // a Sales Receipt (paid-at-issue) — same pattern as raffle
      // tickets, not the marketplace commission-invoice + mark-paid
      // two-step.
      type CreateSalesReceiptResp = {
        salesreceipt?: { salesreceipt_id?: string; salesreceipt_number?: string };
        message?: string;
      };
      const payload: Record<string, unknown> = {
        customer_id: contactId,
        reference_number: reference,
        date: today,
        line_items: [
          {
            name: 'Featured-Slot Fee',
            description: `${bid.tier} tier — slot ${bid.auction?.slotId ?? 'unknown'} — bid ${bidRef}`,
            rate: feeRand,
            quantity: 1,
            account_id: featuredAccountId,
          },
        ],
        payment_mode: 'Other',
        notes: reference,
      };
      if (depositAccountId) {
        payload.deposit_to_account_id = depositAccountId;
      }

      const resp = await this.request<CreateSalesReceiptResp>(
        'POST',
        '/salesreceipts',
        payload,
      );

      const receiptId = resp.salesreceipt?.salesreceipt_id;
      if (!receiptId) {
        throw new Error(
          `Books featured-slot receipt create returned no id: ${resp.message ?? 'unknown'}`,
        );
      }

      await this.prisma.featuredSlotBid.update({
        where: { id: bidId },
        data: {
          zohoInvoiceId: receiptId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Created featured-slot receipt ${resp.salesreceipt?.salesreceipt_number ?? receiptId} (R${feeRand.toFixed(2)}, bid ${bidRef})`,
      );
    } catch (err) {
      const message = (err as Error).message.slice(0, 1000);
      this.logger.error(
        `Featured-slot Books sync FAILED for bid ${bidId}: ${message}`,
      );
      try {
        await this.prisma.featuredSlotBid.update({
          where: { id: bidId },
          data: {
            zohoSyncStatus: 'FAILED',
            zohoSyncError: message,
            zohoSyncLastAttemptAt: new Date(),
          },
        });
      } catch (writeErr) {
        this.logger.error(
          `Could not write FAILED status to bid ${bidId}: ${(writeErr as Error).message}`,
        );
      }
    }
  }

  // ─── Health check ────────────────────────────────────────────────

  /**
   * Lightweight probe for /admin/health. Pings the /organizations
   * endpoint to confirm auth + connectivity. Used by ZB-11.
   */
  async healthCheck(): Promise<{
    ok: boolean;
    enabled: boolean;
    detail?: string;
  }> {
    if (!this.enabled) {
      return { ok: true, enabled: false, detail: 'disabled by feature flag' };
    }
    if (!this.hasCredentials()) {
      return { ok: false, enabled: true, detail: 'missing credentials' };
    }
    try {
      type OrgsResp = { organizations?: Array<{ organization_id?: string }> };
      const resp = await this.request<OrgsResp>('GET', '/organizations');
      const orgIds = resp.organizations?.map((o) => o.organization_id) ?? [];
      if (!orgIds.includes(this.orgId)) {
        return {
          ok: false,
          enabled: true,
          detail: `org ${this.orgId} not visible to credentials`,
        };
      }
      return { ok: true, enabled: true, detail: 'auth + org access verified' };
    } catch (err) {
      return {
        ok: false,
        enabled: true,
        detail: (err as Error).message,
      };
    }
  }
}
