import { Injectable, Logger } from '@nestjs/common';
import { FeeModel, PaymentStatus } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { SettingsService, FLAGS } from '../settings/settings.service';

/**
 * Zoho Books integration — accounting backend for All Outdoor.
 *
 * Design contract:
 *   - Buyer never sees a Books document. Their "Order Confirmation"
 *     is generated by All Outdoor's own platform (agent model — see
 *     the accounting-flow doc that went to the accountant).
 *   - Seller receives a Books-issued Tax Invoice for the commission
 *     when verification approves. The H&G-style Reference field
 *     spells out "Sold for R X - R Y (Platform Fee) = R Z Due to you".
 *   - When the seller payout fires, we mark the invoice paid in Books
 *     against the Client Funds Payable liability — closing the loop.
 *
 * Failure handling:
 *   - Every public method is fire-and-forget from the caller's
 *     perspective. We never block the user-facing flow on a Books API
 *     call — Books going down can't delay payouts or break checkout.
 *   - Each All Outdoor record (Transaction)
 *     has zohoSyncStatus + zohoSyncError + zohoSyncLastAttemptAt
 *     fields. On failure we write FAILED + the error message; the
 *     admin panel shows these + a retry button.
 *   - Feature-flag gated: ZOHO_BOOKS_ENABLED=false skips every API
 *     call (records get status SKIPPED). Lets us deploy code without
 *     touching the live Books account until we explicitly turn it on.
 *
 * Auth:
 *   - Long-lived refresh token in env. Access tokens cached in-memory
 *     for ~55 minutes (Zoho gives 1 hour, we refresh a bit early).
 *   - 401 responses force a refresh and one retry.
 */
@Injectable()
export class ZohoBooksService {
  private readonly logger = new Logger(ZohoBooksService.name);

  private readonly enabled: boolean;
  private readonly clientId: string;
  private readonly clientSecret: string;
  private readonly refreshToken: string;
  private readonly orgId: string;
  private readonly apiDomain: string;
  private readonly accountsDomain: string;

  // In-memory access-token cache. Access tokens are short-lived (1h);
  // we refresh on demand and cache until just before expiry.
  private cachedAccessToken: string | null = null;
  private cachedAccessTokenExpiresAt = 0; // epoch ms

  constructor(
    private readonly prisma: PrismaService,
    private readonly settings: SettingsService,
  ) {
    // Feature flag — leave OFF (false) by default until we're ready
    // to push real documents to Books. Set ZOHO_BOOKS_ENABLED=true
    // in .env when going live.
    this.enabled = process.env.ZOHO_BOOKS_ENABLED === 'true';
    this.clientId = process.env.ZOHO_BOOKS_CLIENT_ID ?? '';
    this.clientSecret = process.env.ZOHO_BOOKS_CLIENT_SECRET ?? '';
    this.refreshToken = process.env.ZOHO_BOOKS_REFRESH_TOKEN ?? '';
    this.orgId = process.env.ZOHO_BOOKS_ORG_ID ?? '';
    this.apiDomain =
      process.env.ZOHO_BOOKS_API_DOMAIN ?? 'https://www.zohoapis.com';
    this.accountsDomain =
      process.env.ZOHO_BOOKS_ACCOUNTS_DOMAIN ?? 'https://accounts.zoho.com';

    if (this.enabled && !this.hasCredentials()) {
      this.logger.error(
        'ZOHO_BOOKS_ENABLED=true but credentials are missing — disabling.',
      );
    }

    if (this.enabled) {
      this.logger.log(
        `Zoho Books integration ENABLED (org ${this.orgId}, api ${this.apiDomain})`,
      );
    } else {
      this.logger.log(
        'Zoho Books integration DISABLED (set ZOHO_BOOKS_ENABLED=true to turn on)',
      );
    }
  }

  /** Public — used by health monitor + admin panel. */
  isEnabled(): boolean {
    return this.enabled && this.hasCredentials();
  }

  private hasCredentials(): boolean {
    return !!(
      this.clientId &&
      this.clientSecret &&
      this.refreshToken &&
      this.orgId
    );
  }

  // ─── Access token management ─────────────────────────────────────

  /**
   * Returns a valid access token. Cached in-memory for ~55 minutes;
   * refreshes from the long-lived refresh token when stale.
   *
   * Don't call externally — every public method on this service that
   * hits the API uses this internally.
   */
  private async getAccessToken(): Promise<string> {
    const now = Date.now();
    // 60-second safety margin so we don't ship a token that expires
    // mid-request.
    if (this.cachedAccessToken && this.cachedAccessTokenExpiresAt > now + 60_000) {
      return this.cachedAccessToken;
    }

    const body = new URLSearchParams({
      grant_type: 'refresh_token',
      client_id: this.clientId,
      client_secret: this.clientSecret,
      refresh_token: this.refreshToken,
    });

    const res = await fetch(`${this.accountsDomain}/oauth/v2/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: body.toString(),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(
        `Zoho token refresh failed (${res.status}): ${text || res.statusText}`,
      );
    }

    const data = (await res.json()) as {
      access_token?: string;
      expires_in?: number;
      error?: string;
    };

    if (!data.access_token) {
      throw new Error(
        `Zoho token refresh returned no access_token: ${data.error ?? 'unknown'}`,
      );
    }

    // Cache. Zoho usually returns expires_in: 3600 (one hour).
    const expiresInMs = (data.expires_in ?? 3600) * 1000;
    this.cachedAccessToken = data.access_token;
    this.cachedAccessTokenExpiresAt = now + expiresInMs;
    this.logger.log(
      `Zoho access token refreshed (expires in ${Math.round(expiresInMs / 60000)}m)`,
    );
    return data.access_token;
  }

  // ─── Authenticated HTTP wrapper ──────────────────────────────────

  /**
   * Authenticated request to Zoho Books API.
   * Auto-prepends organization_id query param to every call.
   * On 401, forces a token refresh and retries once.
   */
  private async request<T>(
    method: 'GET' | 'POST' | 'PUT' | 'DELETE',
    path: string,
    body?: unknown,
  ): Promise<T> {
    return this.requestInner<T>(method, path, body, /* retried */ false);
  }

  private async requestInner<T>(
    method: 'GET' | 'POST' | 'PUT' | 'DELETE',
    path: string,
    body: unknown,
    retried: boolean,
  ): Promise<T> {
    const token = await this.getAccessToken();
    // Books REST API requires organization_id as a query param on
    // every endpoint. We append it ourselves so callers don't have to
    // remember.
    const sep = path.includes('?') ? '&' : '?';
    const url = `${this.apiDomain}/books/v3${path}${sep}organization_id=${this.orgId}`;

    const init: RequestInit = {
      method,
      headers: {
        Authorization: `Zoho-oauthtoken ${token}`,
        'Content-Type': 'application/json',
      },
    };
    if (body !== undefined) {
      init.body = JSON.stringify(body);
    }

    const res = await fetch(url, init);

    if (res.status === 401 && !retried) {
      // Token cache thinks it's valid but Zoho disagrees — force
      // refresh and retry once.
      this.logger.warn('Zoho returned 401 — forcing token refresh');
      this.cachedAccessToken = null;
      this.cachedAccessTokenExpiresAt = 0;
      return this.requestInner<T>(method, path, body, true);
    }

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(
        `Zoho Books ${method} ${path} failed (${res.status}): ${text || res.statusText}`,
      );
    }

    return (await res.json()) as T;
  }

  // ─── Contact (customer) management ───────────────────────────────

  /**
   * Find-or-create the Books contact for a All Outdoor user.
   *
   * Strategy:
   *   - If user.zohoContactId is set, return it (already created).
   *   - Else create a new contact via API and save the returned ID
   *     onto the User record.
   *
   * Used for sellers (we invoice them for commission).
   *
   * Idempotent — concurrent calls for the same user are safe; the
   * unique constraint isn't enforced at DB level but the User row
   * update is atomic, and Zoho's create-contact returns 400 if a
   * duplicate email is detected, which we catch + look up by email.
   */
  async ensureContact(
    userId: string,
    fallbackEmail?: string,
  ): Promise<string | null> {
    if (!this.isEnabled()) return null;

    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: {
        id: true,
        zohoContactId: true,
        email: true,
        firstName: true,
        lastName: true,
        username: true,
        phone: true,
        addrStreet: true,
        addrSuburb: true,
        addrCity: true,
        addrPostalCode: true,
        addrProvince: true,
      },
    });
    if (!user) return null;
    if (user.zohoContactId) return user.zohoContactId;

    const displayName =
      [user.firstName, user.lastName].filter(Boolean).join(' ') ||
      user.username ||
      fallbackEmail ||
      user.email;

    const payload = {
      contact_name: displayName,
      contact_type: 'customer',
      // Books treats this list as the people you can email invoices
      // to. We use the user's primary email.
      contact_persons: [
        {
          first_name: user.firstName ?? '',
          last_name: user.lastName ?? user.username ?? '',
          email: user.email,
          phone: user.phone ?? '',
          is_primary_contact: true,
        },
      ],
      // Address block — used as the bill-to on invoices.
      billing_address: {
        address: user.addrStreet ?? '',
        street2: user.addrSuburb ?? '',
        city: user.addrCity ?? '',
        state: user.addrProvince ?? '',
        zip: user.addrPostalCode ?? '',
        country: 'South Africa',
      },
      // Notes field — surfaces the All Outdoor user ID for the
      // accountant to cross-reference with our admin panel.
      notes: `All Outdoor user ID: ${user.id} / username: @${user.username ?? '(none)'}`,
    };

    type CreateContactResp = {
      contact?: { contact_id?: string };
      code?: number;
      message?: string;
    };
    const resp = await this.request<CreateContactResp>(
      'POST',
      '/contacts',
      payload,
    );

    const contactId = resp.contact?.contact_id;
    if (!contactId) {
      throw new Error(
        `Zoho Books contact create returned no contact_id: ${resp.message ?? 'unknown'}`,
      );
    }

    // Save the ID on the user so we don't recreate next time.
    await this.prisma.user.update({
      where: { id: user.id },
      data: { zohoContactId: contactId },
    });

    this.logger.log(
      `Created Books contact ${contactId} for user ${user.id} (${displayName})`,
    );
    return contactId;
  }

  // ─── Vendor (supplier) management ────────────────────────────────

  /**
   * DD-F — find-or-create the Books VENDOR contact for a Daily Deals supplier.
   *
   * Mirror of ensureContact but for the supply side: a supplier is a Books
   * contact with contact_type 'vendor' (we raise purchase orders against it).
   *
   * Strategy:
   *   - If supplier.zohoVendorId is set, return it (already created).
   *   - Else create a vendor contact via API and save the returned ID onto
   *     the Supplier row.
   *
   * Idempotent — the stored id short-circuits repeat calls. Unlike
   * createDealPurchaseOrder this DOES catch its own errors: a failure stamps
   * FAILED on the Supplier row (so the admin panel can show + retry it) and
   * returns null; the caller treats null as "no vendor" and records its own
   * failure on the PO. Never throws.
   */
  async ensureVendor(supplierId: string): Promise<string | null> {
    if (!this.isEnabled()) return null;

    const supplier = await this.prisma.supplier.findUnique({
      where: { id: supplierId },
    });
    if (!supplier) return null;
    if (supplier.zohoVendorId) return supplier.zohoVendorId;

    try {
      const payload = {
        contact_name: supplier.name,
        contact_type: 'vendor',
        // The people Books can email a purchase order to.
        contact_persons: [
          {
            first_name: supplier.contactPerson,
            email: supplier.email,
            phone: supplier.phone ?? '',
            is_primary_contact: true,
          },
        ],
        // Warehouse address — the collection point The Courier Guy picks up
        // from, and the bill-from on the PO.
        billing_address: {
          address: supplier.warehouseStreet,
          street2: supplier.warehouseSuburb,
          city: supplier.warehouseCity,
          state: supplier.warehouseProvince,
          zip: supplier.warehousePostalCode,
          country: 'South Africa',
        },
        notes: `All Outdoor supplier ID: ${supplier.id}${supplier.vatNumber ? ` / VAT: ${supplier.vatNumber}` : ''}`,
      };

      type CreateContactResp = {
        contact?: { contact_id?: string };
        code?: number;
        message?: string;
      };
      const resp = await this.request<CreateContactResp>(
        'POST',
        '/contacts',
        payload,
      );

      const vendorId = resp.contact?.contact_id;
      if (!vendorId) {
        throw new Error(
          `Zoho Books vendor create returned no contact_id: ${resp.message ?? 'unknown'}`,
        );
      }

      await this.prisma.supplier.update({
        where: { id: supplier.id },
        data: {
          zohoVendorId: vendorId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Created Books vendor ${vendorId} for supplier ${supplier.id} (${supplier.name})`,
      );
      return vendorId;
    } catch (err) {
      await this.markSupplierFailed(supplier.id, err as Error);
      return null;
    }
  }

  private async markSupplierFailed(
    supplierId: string,
    err: Error,
  ): Promise<void> {
    const message = err.message.slice(0, 1000);
    this.logger.error(
      `Zoho Books vendor sync FAILED for supplier ${supplierId}: ${message}`,
    );
    try {
      await this.prisma.supplier.update({
        where: { id: supplierId },
        data: {
          zohoSyncStatus: 'FAILED',
          zohoSyncError: message,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
    } catch (writeErr) {
      this.logger.error(
        `Could not write FAILED status to supplier ${supplierId}: ${(writeErr as Error).message}`,
      );
    }
  }

  // ─── Account ID lookup ───────────────────────────────────────────

  /**
   * Find a Books Chart-of-Accounts account by name.
   * Used at startup time (or on first invoice) to resolve account
   * names like "Commission Revenue" or "Client Funds Payable" to the
   * Books account IDs the API needs.
   *
   * Cached in-memory after first lookup (account IDs don't change).
   */
  private accountIdCache: Map<string, string> = new Map();

  async getAccountIdByName(accountName: string): Promise<string | null> {
    if (!this.isEnabled()) return null;
    const cached = this.accountIdCache.get(accountName);
    if (cached) return cached;

    type ChartOfAccountsResp = {
      chartofaccounts?: Array<{
        account_id?: string;
        account_name?: string;
      }>;
    };
    const resp = await this.request<ChartOfAccountsResp>(
      'GET',
      '/chartofaccounts',
    );

    const accounts = resp.chartofaccounts ?? [];
    // Cache them all while we have the list — we'll need several.
    for (const acc of accounts) {
      if (acc.account_id && acc.account_name) {
        this.accountIdCache.set(acc.account_name, acc.account_id);
      }
    }
    return this.accountIdCache.get(accountName) ?? null;
  }

  // ─── Public document-creation methods ────────────────────────────
  // ZB-4 onwards wires these into the actual hooks. They're stubs
  // here so ZB-3 (this file) compiles cleanly + the integration
  // boundaries are documented.

  /**
   * Commission invoice: All Outdoor → Seller for the platform fee on
   * a marketplace sale. Called from the verification-APPROVED hook.
   *
   * Idempotent: skips if zohoCommissionInvoiceId already set.
   * Skips silently for PRIVATE_ARRANGE (no commission on that flow —
   * funds release direct to seller at payment capture, no agent
   * relationship to invoice).
   *
   * On any error: writes FAILED status + error message to the
   * transaction row. Caller doesn't need to try/catch — this method
   * never throws.
   */
  async createCommissionInvoice(transactionId: string): Promise<void> {
    if (!this.isEnabled()) return;
    const tx = await this.prisma.transaction.findUnique({
      where: { id: transactionId },
      include: {
        seller: {
          select: {
            id: true,
            email: true,
            username: true,
            firstName: true,
            lastName: true,
          },
        },
        listing: {
          select: {
            title: true,
            referenceNumber: true,
            isDealListing: true,
          },
        },
      },
    });
    if (!tx) return;
    // Idempotency — if we've already created the invoice, no-op.
    if (tx.zohoCommissionInvoiceId) return;
    // DD-2 — Daily Deals house deal: GG is the SELLER (first-party), so there
    // is no commission invoice + payout. Post a full-amount Sales Receipt to
    // the BUYER instead, then return before the commission-invoice path. This
    // branch sits at the single release chokepoint (every non-firearm RELEASED
    // path funnels through createCommissionInvoice), so no release call-site
    // needs to change. zohoCommissionInvoiceId stays null → markCommission-
    // InvoicePaid self-skips for house rows.
    if (tx.listing.isDealListing) {
      await this.createDealSalesReceipt(transactionId);
      return;
    }
    // FLOW-F4 (H21) — PRIVATE_ARRANGE was skipped here on the false premise
    // that "we don't hold funds / take commission on that flow". We DO:
    // fee.calculator charges the same commission on PA sales, so skipping the
    // invoice left every PA commission uninvoiced (revenue collected, never
    // recorded in Books). Operator decision: keep the commission AND invoice
    // it — PA now falls through to the standard commission-invoice path below.
    if (tx.commissionZar <= 0) {
      await this.markSkipped(transactionId, 'commissionZar is zero');
      return;
    }

    await this.markPending(transactionId);

    try {
      const contactId = await this.ensureContact(tx.seller.id, tx.seller.email);
      if (!contactId) {
        throw new Error('Could not resolve Books contact for seller');
      }

      const commissionRand = tx.commissionZar / 100;
      const listingPriceRand = tx.listingPrice / 100;
      const sellerPayoutRand = tx.sellerPayout / 100;
      const orderRef =
        tx.listing.referenceNumber ?? tx.id.slice(-8).toUpperCase();

      // Reference line that spells the maths out in plain language — but it
      // has to be maths that HAPPENED.
      //
      // ⚠️ It was hardcoded as "Sold for X - Y (Platform Fee) = Z Due to
      // you". Under BUYNOW_MARKUP that subtraction is false: the listed price
      // already contains BOTH our commission and the gateway fee, so
      // listingPrice - commission overshoots the payout by the fee every
      // time (R511.97 - R40.50 = R471.47, but the seller is due R450.00).
      // Nothing was taken off them at all — our cut was added to the buyer's
      // price. Say that instead of printing an equation that does not hold.
      const isMarkup = tx.feeModel === FeeModel.BUYNOW_MARKUP;
      const reference = isMarkup
        ? `Your price ${this.formatRand(sellerPayoutRand)} Due to you (listed to the buyer at ${this.formatRand(listingPriceRand)}, fees included in the price)`
        : `Sold for ${this.formatRand(listingPriceRand)} - ${this.formatRand(commissionRand)} (Platform Fee) = ${this.formatRand(sellerPayoutRand)} Due to you`;

      // Resolve Commission Revenue account so Books posts the income
      // to the right ledger row. Cached after first lookup.
      const commissionAccountId = await this.getAccountIdByName(
        'Commission Revenue',
      );
      if (!commissionAccountId) {
        throw new Error(
          'Commission Revenue account not found in Books chart-of-accounts',
        );
      }

      const today = new Date().toISOString().slice(0, 10);

      type CreateInvoiceResp = {
        invoice?: { invoice_id?: string; invoice_number?: string };
        code?: number;
        message?: string;
      };

      // P0.7 — the payment-processing fee GG retains (1.5% EFT handling
      // today; card rate under a gateway) is real revenue but was never
      // documented in Books. When the SELLER absorbs it (passFeeToBuyer
      // false — the default), it is deducted from their payout exactly
      // like the commission, so it belongs on this same invoice as a
      // second line. When the BUYER paid it on top, invoicing the seller
      // would misstate who bore it — excluded here; the accountant picks
      // those up from the reconciliation. Posts to a dedicated
      // "Processing Fee Revenue" account when one exists, else falls
      // back to Commission Revenue.
      const lineItems: Array<{
        name: string;
        description: string;
        rate: number;
        quantity: number;
        account_id: string;
      }> = [
        {
          name: 'Platform Fee',
          description: `${orderRef} — ${tx.listing.title}`,
          rate: commissionRand,
          quantity: 1,
          account_id: commissionAccountId,
        },
      ];
      // ⚠️ OUR PROCESSING REVENUE WAS NEVER BOOKED ON A MARKED-UP SALE.
      // The old condition was `!tx.passFeeToBuyer && processingFee > 0`, and
      // the sell form hardcodes the listing flag TRUE — so on every Buy Now
      // this branch was skipped and the gateway margin we had marked INTO the
      // price went unrecorded. Under the markup model the fee is real revenue
      // recovered from the buyer and belongs on the invoice; under the deduct
      // model it is only ours when the seller carried it.
      if ((isMarkup || !tx.passFeeToBuyer) && tx.processingFee > 0) {
        const processingAccountId =
          (await this.getAccountIdByName('Processing Fee Revenue')) ??
          commissionAccountId;
        lineItems.push({
          name: 'Payment Processing Fee',
          description: `${orderRef} — payment handling`,
          rate: tx.processingFee / 100,
          quantity: 1,
          account_id: processingAccountId,
        });
      }

      const payload = {
        customer_id: contactId,
        reference_number: reference,
        date: today,
        due_date: today,
        line_items: lineItems,
        notes: `${reference}.\nAll Outdoor transaction reference: ${orderRef}`,
        // Skip tax — we're pre-VAT. When VAT-registered this flips
        // to is_inclusive_tax: false + tax_id on each line.
      };

      const resp = await this.request<CreateInvoiceResp>(
        'POST',
        '/invoices',
        payload,
      );

      const invoiceId = resp.invoice?.invoice_id;
      if (!invoiceId) {
        throw new Error(
          `Books invoice create returned no invoice_id: ${resp.message ?? 'unknown'}`,
        );
      }

      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoCommissionInvoiceId: invoiceId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Created commission invoice ${resp.invoice?.invoice_number ?? invoiceId} for tx ${transactionId} (R${commissionRand.toFixed(2)})`,
      );
    } catch (err) {
      await this.markFailed(transactionId, err as Error);
    }
  }

  // DD-2 — Daily Deals first-party Sales Receipt. A house deal is sold BY Gun
  // Galore, so at RELEASED the WHOLE sale is GG revenue (there is no seller
  // commission). Post a paid-at-issue Sales Receipt to the BUYER for the full
  // buyerTotal (mirrors the featured-slot receipt shape). Idempotent on the
  // dedicated zohoDealReceiptId column — never reuse zohoCommissionInvoiceId
  // (a Sales Receipt is a different Books object; markCommissionInvoicePaid
  // would then do a wrong-type /invoices lookup). Never throws.
  //
  // Accountant note: posts ONE gross line = buyerTotal. For a first-party
  // sale the revenue IS what the customer paid GG; the courier cost is a
  // separate expense recorded when GG pays the carrier. The accountant may
  // later choose to split goods vs shipping/handling into separate accounts.
  async createDealSalesReceipt(transactionId: string): Promise<void> {
    if (!this.isEnabled()) return;
    const tx = await this.prisma.transaction.findUnique({
      where: { id: transactionId },
      include: {
        buyer: { select: { id: true, email: true } },
        listing: {
          select: { title: true, referenceNumber: true, isDealListing: true },
        },
      },
    });
    if (!tx) return;
    if (!tx.listing.isDealListing) return; // guard: house deals only
    if (tx.zohoDealReceiptId) return; // idempotent
    if (tx.buyerTotal <= 0) return;

    await this.markPending(transactionId);
    try {
      const contactId = await this.ensureContact(tx.buyer.id, tx.buyer.email);
      if (!contactId) {
        throw new Error('Could not resolve Books contact for buyer');
      }
      const revenueAccountId =
        (await this.getAccountIdByName('Daily Deals Revenue')) ??
        (await this.getAccountIdByName('Commission Revenue'));
      if (!revenueAccountId) {
        throw new Error(
          'No revenue account (Daily Deals Revenue / Commission Revenue) found in Books chart-of-accounts',
        );
      }
      // EFT-paid deals land in FNB; bank account first.
      const depositAccountId =
        (await this.getAccountIdByName('Bank — FNB Business')) ??
        (await this.getAccountIdByName('Bank — Peach Pending'));

      const orderRef =
        tx.listing.referenceNumber ?? tx.id.slice(-8).toUpperCase();
      const totalRand = tx.buyerTotal / 100;
      const today = new Date().toISOString().slice(0, 10);
      const reference = `Daily Deal — ${orderRef} — ${tx.listing.title}`;

      type CreateSalesReceiptResp = {
        salesreceipt?: {
          salesreceipt_id?: string;
          salesreceipt_number?: string;
        };
        message?: string;
      };
      const payload: Record<string, unknown> = {
        customer_id: contactId,
        reference_number: reference,
        date: today,
        line_items: [
          {
            name: 'Daily Deal',
            description: `${orderRef} — ${tx.listing.title}`,
            rate: totalRand,
            quantity: 1,
            account_id: revenueAccountId,
          },
        ],
        payment_mode: 'Other',
        notes: `${reference}.\nAll Outdoor first-party sale — full amount is GG revenue.`,
      };
      if (depositAccountId) {
        payload.deposit_to_account_id = depositAccountId;
      }

      // Operator decision 2026-07-19: Daily Deals buyers receive the FORMAL
      // document — Zoho emails the sales receipt to the buyer contact on
      // creation (?send=true). GG is not VAT-registered, so the org issues
      // non-VAT receipts until registration (no tax config = no VAT line).
      const resp = await this.request<CreateSalesReceiptResp>(
        'POST',
        '/salesreceipts?send=true',
        payload,
      );
      const receiptId = resp.salesreceipt?.salesreceipt_id;
      if (!receiptId) {
        throw new Error(
          `Books deal receipt create returned no id: ${resp.message ?? 'unknown'}`,
        );
      }
      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoDealReceiptId: receiptId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Created Daily Deal sales receipt ${resp.salesreceipt?.salesreceipt_number ?? receiptId} for tx ${transactionId} (R${totalRand.toFixed(2)})`,
      );
    } catch (err) {
      await this.markFailed(transactionId, err as Error);
    }
  }

  // ─── Daily Deals supplier purchase orders (DD-F) ─────────────────

  /**
   * DD-F — raise a Zoho Books PURCHASE ORDER to a house deal's supplier for
   * the units the deal actually sold, so The Courier Guy can collect that
   * stock from the supplier warehouse (JIT supplier fulfilment).
   *
   * A Books PURCHASE ORDER is a NON-POSTING document — it does not hit the
   * chart of accounts — so unlike the sales receipts above there is NO
   * getAccountIdByName lookup here.
   *
   * Idempotent on the dedicated DealPurchaseOrder row (dealId is unique) plus
   * its zohoPurchaseOrderId column: an existing PO that is live (non-CANCELLED)
   * or already carries a Zoho id is left untouched; a CANCELLED row with no
   * Zoho id may be re-raised.
   *
   * The local DealPurchaseOrder row is written BEFORE the Zoho call (and even
   * when Books is OFF) so the operator always has a record; only the API call
   * is gated on isEnabled(). Never throws — a Zoho failure stamps FAILED on
   * the PO row.
   */
  async createDealPurchaseOrder(dealId: string): Promise<void> {
    const deal = await this.prisma.deal.findUnique({
      where: { id: dealId },
      include: {
        listing: { select: { title: true, referenceNumber: true } },
        supplier: true,
        purchaseOrder: true,
      },
    });
    if (!deal) return;

    const existingPo = deal.purchaseOrder;
    const unitCostCents = deal.costPriceCents;

    // Units to order = units actually sold (paid, not refunded / cancelled /
    // rejected) — mirrors the P&L counting filter in deals.service.
    const agg = await this.prisma.transaction.aggregate({
      where: {
        listingId: deal.listingId,
        paidAt: { not: null },
        refundOfId: null,
        paymentStatus: { not: PaymentStatus.REFUNDED },
        rejectedAt: null,
        cancelledByBuyerAt: null,
        manualCancelledAt: null,
      },
      _sum: { quantity: true },
    });
    const unitsSold = agg._sum.quantity ?? 0;

    // #5 — zero-sale deals get a TERMINAL, non-flagged row instead of no row.
    // A killswitch-ended deal has no PO at all (operator decision); a deal that
    // ended with nothing sold gets a CANCELLED/OK row so the radar + retry
    // never churn on it (they key on FAILED, never on this). No supplier order
    // is required — there is nothing to collect.
    if (unitsSold <= 0) {
      await this.prisma.dealPurchaseOrder.upsert({
        where: { dealId },
        create: {
          dealId,
          unitsOrdered: 0,
          unitCostCents,
          totalCents: 0,
          status: 'CANCELLED',
          zohoSyncStatus: 'OK',
          zohoSyncError: 'No units sold — no supplier order required',
        },
        update: {
          unitsOrdered: 0,
          totalCents: 0,
          status: 'CANCELLED',
          zohoSyncStatus: 'OK',
          zohoSyncError: 'No units sold — no supplier order required',
        },
      });
      return;
    }

    // #1 — placement-keyed idempotency. Once a Zoho PO id is stamped the order
    // is really placed, whatever the local status — never place a second one.
    // (The old "CANCELLED escape-hatch" guard was dead code and, worse, blocked
    // a FAILED row from ever retrying; keying on the Zoho id fixes both.)
    if (existingPo?.zohoPurchaseOrderId) return;

    const totalCents = unitsSold * unitCostCents;

    // Write the local PO record first so we hold it even if Books is off or the
    // API call below fails. Leaves zohoSync* untouched on update, so a prior
    // FAILED row stays FAILED until the claim below re-fires it.
    await this.prisma.dealPurchaseOrder.upsert({
      where: { dealId },
      create: {
        dealId,
        unitsOrdered: unitsSold,
        unitCostCents,
        totalCents,
        status: 'DRAFT',
      },
      update: {
        unitsOrdered: unitsSold,
        unitCostCents,
        totalCents,
        status: 'DRAFT',
      },
    });

    // Books off → keep the local DRAFT row and stop; nothing to place.
    if (!this.isEnabled()) return;

    // #2 — atomic placement CLAIM (compare-and-set). Only ONE caller may hold
    // the PENDING claim at a time, so two concurrent triggers can never both
    // POST /purchaseorders (which would double-order from the supplier). A fresh
    // (null), OK, FAILED or SKIPPED row is claimable; a PENDING row is claimable
    // ONLY once it is stale (>15 min — a crash stranded it mid-POST). Written
    // null-safely (explicit null branch) so a brand-new DRAFT row is claimed.
    const staleBefore = new Date(Date.now() - 15 * 60 * 1000);
    const claim = await this.prisma.dealPurchaseOrder.updateMany({
      where: {
        dealId,
        zohoPurchaseOrderId: null,
        OR: [
          { zohoSyncStatus: null },
          { zohoSyncStatus: { in: ['OK', 'FAILED', 'SKIPPED'] } },
          { zohoSyncStatus: 'PENDING', zohoSyncLastAttemptAt: { lt: staleBefore } },
        ],
      },
      data: { zohoSyncStatus: 'PENDING', zohoSyncLastAttemptAt: new Date() },
    });
    // Lost the race (a concurrent caller is placing, or it's already placed) —
    // stand down without POSTing. The winner (or a later retry) completes it.
    if (claim.count === 0) return;

    try {
      const supplier = deal.supplier;
      if (!supplier) {
        throw new Error('Deal has no supplier — cannot raise a purchase order');
      }
      const vendorId = await this.ensureVendor(supplier.id);
      if (!vendorId) {
        throw new Error('Could not resolve Books vendor for supplier');
      }

      const orderRef =
        deal.listing.referenceNumber ?? deal.id.slice(-8).toUpperCase();
      const unitCostRand = unitCostCents / 100;

      type CreatePurchaseOrderResp = {
        purchaseorder?: {
          purchaseorder_id?: string;
          purchaseorder_number?: string;
        };
        code?: number;
        message?: string;
      };
      const resp = await this.request<CreatePurchaseOrderResp>(
        'POST',
        '/purchaseorders',
        {
          vendor_id: vendorId,
          reference_number: orderRef,
          line_items: [
            {
              name: deal.supplierRef ?? deal.listing.title,
              description: `${orderRef} — ${deal.listing.title}`,
              rate: unitCostRand,
              quantity: unitsSold,
            },
          ],
          notes:
            'Collection by The Courier Guy from your warehouse — All Outdoor books the pickup.',
        },
      );

      const poId = resp.purchaseorder?.purchaseorder_id;
      if (!poId) {
        throw new Error(
          `Books purchase-order create returned no id: ${resp.message ?? 'unknown'}`,
        );
      }

      await this.prisma.dealPurchaseOrder.update({
        where: { dealId },
        data: {
          zohoPurchaseOrderId: poId,
          status: 'PLACED',
          placedAt: new Date(),
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Created Books purchase order ${resp.purchaseorder?.purchaseorder_number ?? poId} for deal ${dealId} (${unitsSold} × R${unitCostRand.toFixed(2)})`,
      );

      // DD-F fix — the lifecycle PO triggers (deal ended / sold-out) only call
      // createDealPurchaseOrder, so the supplier email has to fire from HERE or
      // it never fires on the primary flow (the "Place PO" button is the only
      // other caller and it's gone the moment a PO row exists). emailPurchaseOrder
      // is self-guarded: no-op unless the deal_po_email_enabled flag is ON (so
      // this stays inert until the operator flips it), idempotent on emailedAt,
      // and it swallows its own errors — a placed PO is never rolled back by it.
      await this.emailPurchaseOrder(dealId);
    } catch (err) {
      await this.markPoFailed(dealId, err as Error);
    }
  }

  /**
   * DD-F — email the placed Zoho purchase order to the supplier.
   *
   * HARD-gated on the deal_po_email_enabled flag: while the Daily Deals
   * programme is inert this is a no-op so no supplier is ever contacted.
   * Requires the PO to have been placed with Zoho first (zohoPurchaseOrderId
   * set). Idempotent — skips once emailedAt is stamped, so a supplier is never
   * emailed the same PO twice. Never throws.
   */
  async emailPurchaseOrder(dealId: string): Promise<void> {
    if (!this.isEnabled()) return;
    const po = await this.prisma.dealPurchaseOrder.findUnique({
      where: { dealId },
      include: { deal: { include: { supplier: true } } },
    });
    if (!po || !po.zohoPurchaseOrderId) return; // must be PLACED first
    if (po.emailedAt) return; // already emailed — never spam the supplier
    const supplier = po.deal.supplier;
    if (!supplier) return;

    const emailEnabled = await this.settings.get(FLAGS.dealPoEmailEnabled);
    if (!emailEnabled) {
      this.logger.log(
        `Deal PO email skipped for deal ${dealId} — ${FLAGS.dealPoEmailEnabled.key} is off`,
      );
      return;
    }

    try {
      await this.request<{ message?: string }>(
        'POST',
        `/purchaseorders/${po.zohoPurchaseOrderId}/email`,
        { to_mail_ids: [supplier.email] },
      );
      await this.prisma.dealPurchaseOrder.update({
        where: { dealId },
        data: {
          emailedAt: new Date(),
          status: 'EMAILED',
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Emailed purchase order for deal ${dealId} to supplier ${supplier.id} (${supplier.email})`,
      );
    } catch (err) {
      await this.markPoFailed(dealId, err as Error);
    }
  }

  /**
   * DD-F — bounded retry for deal purchase orders that FAILED at placement, or
   * were stranded mid-POST by a crash (a stale PENDING row). Keyed on the
   * DealPurchaseOrder ROW, never on "an ENDED/SOLD_OUT deal with a null PO":
   * killswitch-ended deals intentionally carry no PO, and zero-sale deals now
   * carry a terminal CANCELLED/OK row — neither is a real failure. A row is an
   * actual failure iff it never reached Zoho (zohoPurchaseOrderId still null)
   * AND its last sync FAILED, or it is a PENDING row older than the ~15-min
   * stale window (the CAS in createDealPurchaseOrder re-claims those).
   * createDealPurchaseOrder is idempotent, so a re-fire can only fill the gap.
   * Bounded per run; never throws.
   */
  /**
   * Hourly self-heal for commission invoices that previously had NO
   * automatic retry (only the manual /zoho-retry button): invoices whose
   * last sync FAILED (or stranded PENDING >1h — a crash between
   * markPending and the result). createCommissionInvoice is idempotent
   * (guarded on zohoCommissionInvoiceId), so re-firing a false negative is
   * a no-op. SKIPPED rows are deliberate decisions and are never retried.
   */
  async retryFailedRevenueDocs(limit = 25): Promise<void> {
    if (!this.isEnabled()) return;
    try {
      const staleFloor = new Date(Date.now() - 3_600_000);
      const failedInvoices = await this.prisma.transaction.findMany({
        where: {
          zohoCommissionInvoiceId: null,
          OR: [
            { zohoSyncStatus: 'FAILED' },
            {
              zohoSyncStatus: 'PENDING',
              zohoSyncLastAttemptAt: { lt: staleFloor },
            },
          ],
        },
        select: { id: true },
        take: limit,
      });
      for (const t of failedInvoices) {
        await this.createCommissionInvoice(t.id);
      }

      if (failedInvoices.length) {
        this.logger.log(
          `retryFailedRevenueDocs: re-fired ${failedInvoices.length} commission invoice(s)`,
        );
      }
    } catch (err) {
      this.logger.warn(
        `retryFailedRevenueDocs failed: ${(err as Error).message}`,
      );
    }
  }

  async retryMissingDealPurchaseOrders(limit = 25): Promise<void> {
    if (!this.isEnabled()) return;
    try {
      const staleBefore = new Date(Date.now() - 15 * 60 * 1000);
      const due = await this.prisma.dealPurchaseOrder.findMany({
        where: {
          zohoPurchaseOrderId: null,
          OR: [
            { zohoSyncStatus: 'FAILED' },
            {
              zohoSyncStatus: 'PENDING',
              zohoSyncLastAttemptAt: { lt: staleBefore },
            },
          ],
        },
        orderBy: { updatedAt: 'asc' },
        take: limit,
        select: { dealId: true },
      });
      for (const po of due) {
        await this.createDealPurchaseOrder(po.dealId);
      }
      if (due.length > 0) {
        this.logger.log(
          `retryMissingDealPurchaseOrders: re-fired ${due.length} failed/stale deal PO(s)`,
        );
      }
    } catch (err) {
      this.logger.error(
        `retryMissingDealPurchaseOrders failed: ${(err as Error).message}`,
      );
    }
  }

  private async markPoFailed(dealId: string, err: Error): Promise<void> {
    const message = err.message.slice(0, 1000);
    this.logger.error(
      `Zoho Books purchase-order sync FAILED for deal ${dealId}: ${message}`,
    );
    try {
      await this.prisma.dealPurchaseOrder.update({
        where: { dealId },
        data: {
          zohoSyncStatus: 'FAILED',
          zohoSyncError: message,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
    } catch (writeErr) {
      this.logger.error(
        `Could not write FAILED status to PO for deal ${dealId}: ${(writeErr as Error).message}`,
      );
    }
  }

  /**
   * Records payment against the commission invoice using Client
   * Funds Payable as the source — effectively draining the held
   * funds liability by the commission amount and marking the
   * invoice as Paid in one Books operation.
   *
   * Called after createCommissionInvoice (typically in the same
   * verification-APPROVED hook). Idempotent: skips if
   * zohoCommissionPaymentId already set, or if the invoice ID is
   * not yet set (createCommissionInvoice must run first).
   *
   * Like createCommissionInvoice, never throws — failures are
   * persisted as FAILED status on the transaction.
   */
  async markCommissionInvoicePaid(transactionId: string): Promise<void> {
    if (!this.isEnabled()) return;
    const tx = await this.prisma.transaction.findUnique({
      where: { id: transactionId },
      include: {
        seller: { select: { id: true } },
      },
    });
    if (!tx) return;
    if (!tx.zohoCommissionInvoiceId) return; // invoice must exist first
    if (tx.zohoCommissionPaymentId) return; // already marked paid

    try {
      const sellerContactId = await this.ensureContact(tx.seller.id);
      if (!sellerContactId) {
        throw new Error('Could not resolve seller contact for payment');
      }

      const cfpAccountId = await this.getAccountIdByName(
        'Client Funds Payable',
      );
      if (!cfpAccountId) {
        throw new Error(
          'Client Funds Payable account not found in Books chart-of-accounts',
        );
      }

      // P0.7 (review fix) — settle what the INVOICE actually says, not a
      // recomputation from tx fields. Legacy pre-deploy invoices carry a
      // single commission-only line; recomputing commission+fee here would
      // over-apply, Zoho would reject the payment, and every retry would
      // fail identically (permanent FAILED loop). Reading the live balance
      // is correct for both cohorts and for any future line changes.
      type GetInvoiceResp = {
        invoice?: { balance?: number; total?: number; status?: string };
      };
      const inv = await this.request<GetInvoiceResp>(
        'GET',
        `/invoices/${tx.zohoCommissionInvoiceId}`,
      );
      const invoiceTotalRand = inv.invoice?.balance ?? 0;
      if (invoiceTotalRand <= 0) {
        // Nothing outstanding (already settled in Books, e.g. by hand).
        // Stamp a sentinel so the idempotency guard stops re-running this.
        await this.prisma.transaction.update({
          where: { id: transactionId },
          data: {
            zohoCommissionPaymentId: 'SETTLED_EXTERNALLY',
            zohoSyncStatus: 'OK',
            zohoSyncError: null,
            zohoSyncLastAttemptAt: new Date(),
          },
        });
        this.logger.log(
          `Commission invoice for tx ${transactionId} already has zero balance — stamped settled`,
        );
        return;
      }
      const today = new Date().toISOString().slice(0, 10);
      const orderRef = tx.id.slice(-8).toUpperCase();

      type CreatePaymentResp = {
        payment?: { payment_id?: string };
        code?: number;
        message?: string;
      };
      const payload = {
        customer_id: sellerContactId,
        payment_mode: 'Other',
        amount: invoiceTotalRand,
        date: today,
        reference_number: `Settled from buyer funds — ${orderRef}`,
        // The deposit_to_account is where the money "came from" —
        // in our case from the Client Funds Payable liability, NOT
        // from a real bank account. Books may need this set up as
        // a "Bank" type account in their CoA for this to work; if
        // it errors here we'll know to either reclassify CFP or
        // switch to a manual-journal posting pattern.
        deposit_to_account_id: cfpAccountId,
        invoices: [
          {
            invoice_id: tx.zohoCommissionInvoiceId,
            amount_applied: invoiceTotalRand,
          },
        ],
        description:
          'Commission settled by draining buyer funds held in trust',
      };

      const resp = await this.request<CreatePaymentResp>(
        'POST',
        '/customerpayments',
        payload,
      );

      const paymentId = resp.payment?.payment_id;
      if (!paymentId) {
        throw new Error(
          `Books payment create returned no payment_id: ${resp.message ?? 'unknown'}`,
        );
      }

      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoCommissionPaymentId: paymentId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Marked commission invoice paid for tx ${transactionId} (R${invoiceTotalRand.toFixed(2)})`,
      );
    } catch (err) {
      await this.markFailed(transactionId, err as Error);
    }
  }

  // ─── Status helpers ──────────────────────────────────────────────

  private async markPending(transactionId: string): Promise<void> {
    await this.prisma.transaction.update({
      where: { id: transactionId },
      data: {
        zohoSyncStatus: 'PENDING',
        zohoSyncLastAttemptAt: new Date(),
      },
    });
  }

  private async markSkipped(
    transactionId: string,
    reason: string,
  ): Promise<void> {
    await this.prisma.transaction.update({
      where: { id: transactionId },
      data: {
        zohoSyncStatus: 'SKIPPED',
        zohoSyncError: reason,
        zohoSyncLastAttemptAt: new Date(),
      },
    });
  }

  private async markFailed(
    transactionId: string,
    err: Error,
  ): Promise<void> {
    const message = err.message.slice(0, 1000);
    this.logger.error(
      `Zoho Books sync FAILED for tx ${transactionId}: ${message}`,
    );
    try {
      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoSyncStatus: 'FAILED',
          zohoSyncError: message,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
    } catch (writeErr) {
      this.logger.error(
        `Could not write FAILED status to tx ${transactionId}: ${(writeErr as Error).message}`,
      );
    }
  }

  private formatRand(amount: number): string {
    // R 10,000 / R 1,500.50 / R 0.99 — matches H&G invoice style.
    // Use en-US locale so the thousands separator is a regular comma
    // (ASCII U+002C). Earlier version used en-ZA which gave us a
    // non-breaking space (U+00A0) — Zoho's PDF font doesn't have a
    // glyph for that and renders it as U+FFFD replacement character
    // ("R 10�000" instead of "R 10,000").
    const formatted = amount.toLocaleString('en-US', {
      minimumFractionDigits: amount % 1 === 0 ? 0 : 2,
      maximumFractionDigits: 2,
    });
    return `R ${formatted}`;
  }

  /**
   * Credit Note for refund: reverses the commission invoice when a
   * transaction is refunded by admin.
   *
   * Books semantics:
   *   - Credit Note is a tax document (the inverse of an Invoice)
   *   - Created against the seller (same contact as the original
   *     invoice), with one line item mirroring the commission
   *   - We then APPLY the credit note to the original invoice so
   *     Books shows the invoice as cancelled/refunded
   *
   * Idempotent: skips if zohoCreditNoteId already set.
   *
   * Skipped (with logged reason) if:
   *   - No original commission invoice exists (PRIVATE_ARRANGE
   *     refunds, or refunds of transactions that never reached
   *     verification-approved state)
   *   - Feature flag is off
   *
   * Never throws — failures persist as zohoSyncStatus=FAILED so
   * admin can retry from the dossier.
   */
  async createCommissionCreditNote(
    transactionId: string,
    refundReason?: string,
  ): Promise<void> {
    if (!this.isEnabled()) return;
    const tx = await this.prisma.transaction.findUnique({
      where: { id: transactionId },
      include: {
        seller: { select: { id: true, email: true } },
        listing: {
          select: { title: true, referenceNumber: true, isDealListing: true },
        },
      },
    });
    if (!tx) return;
    if (tx.zohoCreditNoteId) return; // already credited
    // DD-2 — Daily Deals house-deal refund: reverse the deal Sales Receipt
    // with a Credit Note to the BUYER (not a seller commission credit).
    // Refunds normally happen pre-release, when no receipt exists yet →
    // createDealCreditNote no-ops. Return so house rows never hit the
    // commission-credit path below.
    if (tx.listing.isDealListing) {
      await this.createDealCreditNote(transactionId, refundReason);
      return;
    }
    if (!tx.zohoCommissionInvoiceId) {
      await this.markSkipped(
        transactionId,
        'No commission invoice to credit (refund pre-approval or PRIVATE_ARRANGE)',
      );
      return;
    }

    try {
      const contactId = await this.ensureContact(tx.seller.id, tx.seller.email);
      if (!contactId) {
        throw new Error('Could not resolve Books contact for seller');
      }
      const commissionAccountId = await this.getAccountIdByName(
        'Commission Revenue',
      );
      if (!commissionAccountId) {
        throw new Error(
          'Commission Revenue account not found in Books chart-of-accounts',
        );
      }

      const commissionRand = tx.commissionZar / 100;
      const orderRef = tx.listing.referenceNumber ?? tx.id.slice(-8).toUpperCase();
      const reason = (refundReason ?? 'Transaction refunded by admin').slice(0, 200);
      // ⚠️ THE CREDIT NOTE MUST REVERSE WHAT THE INVOICE RAISED. The invoice
      // books a second 'Payment Processing Fee' line whenever the fee was
      // ours to keep — under BUYNOW_MARKUP (recovered from the buyer inside
      // the list price) or when the seller absorbed it. Reversing only the
      // commission would leave that revenue standing against a sale that no
      // longer exists, which is exactly the kind of one-sided entry the
      // partial-refund gap already causes. Same condition, both directions.
      const isMarkup = tx.feeModel === FeeModel.BUYNOW_MARKUP;
      const reversesProcessingFee =
        (isMarkup || !tx.passFeeToBuyer) && tx.processingFee > 0;
      // What the note is actually worth — used both to word the reference and
      // to apply it against the invoice.
      const creditNoteTotalRand =
        commissionRand + (reversesProcessingFee ? tx.processingFee / 100 : 0);
      const reference = reversesProcessingFee
        ? `Refund — ${orderRef} (reversing commission of ${this.formatRand(commissionRand)} and processing fee of ${this.formatRand(tx.processingFee / 100)})`
        : `Refund — ${orderRef} (reversing commission of ${this.formatRand(commissionRand)})`;
      const today = new Date().toISOString().slice(0, 10);

      type CreateCreditNoteResp = {
        creditnote?: { creditnote_id?: string; creditnote_number?: string };
        message?: string;
      };
      const payload = {
        customer_id: contactId,
        reference_number: reference,
        date: today,
        line_items: [
          {
            name: 'Platform Fee — refund',
            description: `${orderRef} — ${tx.listing.title} (${reason})`,
            rate: commissionRand,
            quantity: 1,
            account_id: commissionAccountId,
          },
          ...(reversesProcessingFee
            ? [
                {
                  name: 'Payment Processing Fee — refund',
                  description: `${orderRef} — payment handling (${reason})`,
                  rate: tx.processingFee / 100,
                  quantity: 1,
                  // Falls back to Commission Revenue exactly as the invoice
                  // does, so a missing account cannot strand the reversal.
                  account_id:
                    (await this.getAccountIdByName('Processing Fee Revenue')) ??
                    commissionAccountId,
                },
              ]
            : []),
        ],
        notes: `${reference}.\nAll Outdoor transaction reference: ${orderRef}\nReason: ${reason}`,
      };

      const resp = await this.request<CreateCreditNoteResp>(
        'POST',
        '/creditnotes',
        payload,
      );

      const creditNoteId = resp.creditnote?.creditnote_id;
      if (!creditNoteId) {
        throw new Error(
          `Books credit-note create returned no creditnote_id: ${resp.message ?? 'unknown'}`,
        );
      }

      // Apply the credit note against the original invoice so Books
      // shows the invoice as effectively cancelled — without this,
      // both rows sit independently and the seller's open-balance
      // doesn't zero out.
      try {
        await this.request<{ message?: string }>(
          'POST',
          `/creditnotes/${creditNoteId}/invoices`,
          {
            invoices: [
              {
                invoice_id: tx.zohoCommissionInvoiceId,
                // ⚠️ THE FULL CREDIT-NOTE TOTAL, NOT JUST THE COMMISSION.
                // The note now carries a second 'Payment Processing Fee —
                // refund' line whenever the invoice raised one. Applying only
                // the commission leaves the invoice short by exactly the
                // processing fee, so the seller's open balance never zeroes —
                // which is the one thing this apply call exists to do.
                amount_applied: creditNoteTotalRand,
              },
            ],
          },
        );
      } catch (applyErr) {
        // Non-fatal — the credit note exists, admin can manually
        // apply it from the Books UI if this step failed. Log it
        // but don't reverse the whole operation.
        this.logger.warn(
          `Credit note ${creditNoteId} created but apply-to-invoice failed: ${(applyErr as Error).message}`,
        );
      }

      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoCreditNoteId: creditNoteId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Created refund credit note ${resp.creditnote?.creditnote_number ?? creditNoteId} for tx ${transactionId} (R${commissionRand.toFixed(2)})`,
      );
    } catch (err) {
      await this.markFailed(transactionId, err as Error);
    }
  }

  // DD-2 — Daily Deals house-deal Credit Note. Reverses a deal Sales Receipt
  // when a RELEASED house deal is refunded. If no receipt exists yet (the
  // normal case — refunds happen PRE-release, before revenue is booked),
  // no-op via markSkipped: there is nothing to reverse. Standalone credit note
  // to the BUYER (a Sales Receipt has no invoice to apply against). Idempotent
  // on zohoDealCreditNoteId. Never throws.
  async createDealCreditNote(
    transactionId: string,
    refundReason?: string,
  ): Promise<void> {
    if (!this.isEnabled()) return;
    const tx = await this.prisma.transaction.findUnique({
      where: { id: transactionId },
      include: {
        buyer: { select: { id: true, email: true } },
        listing: {
          select: { title: true, referenceNumber: true, isDealListing: true },
        },
      },
    });
    if (!tx) return;
    if (!tx.listing.isDealListing) return;
    if (tx.zohoDealCreditNoteId) return; // idempotent
    if (!tx.zohoDealReceiptId) {
      // Pre-release refund: no Sales Receipt was ever posted, so there is no
      // revenue to reverse. This is the normal path (refunds happen HELD).
      await this.markSkipped(
        transactionId,
        'No deal sales receipt to credit (refund pre-release)',
      );
      return;
    }
    try {
      const contactId = await this.ensureContact(tx.buyer.id, tx.buyer.email);
      if (!contactId) {
        throw new Error('Could not resolve Books contact for buyer');
      }
      const revenueAccountId =
        (await this.getAccountIdByName('Daily Deals Revenue')) ??
        (await this.getAccountIdByName('Commission Revenue'));
      if (!revenueAccountId) {
        throw new Error('No revenue account found in Books chart-of-accounts');
      }

      const orderRef =
        tx.listing.referenceNumber ?? tx.id.slice(-8).toUpperCase();
      const totalRand = tx.buyerTotal / 100;
      const reason = (refundReason ?? 'Daily Deal refunded').slice(0, 200);
      const today = new Date().toISOString().slice(0, 10);
      const reference = `Daily Deal refund — ${orderRef} (reversing ${this.formatRand(totalRand)})`;

      type CreateCreditNoteResp = {
        creditnote?: { creditnote_id?: string; creditnote_number?: string };
        message?: string;
      };
      const payload = {
        customer_id: contactId,
        reference_number: reference,
        date: today,
        line_items: [
          {
            name: 'Daily Deal — refund',
            description: `${orderRef} — ${tx.listing.title} (${reason})`,
            rate: totalRand,
            quantity: 1,
            account_id: revenueAccountId,
          },
        ],
        notes: `${reference}.\nAll Outdoor transaction reference: ${orderRef}\nReason: ${reason}`,
      };
      const resp = await this.request<CreateCreditNoteResp>(
        'POST',
        '/creditnotes',
        payload,
      );
      const creditNoteId = resp.creditnote?.creditnote_id;
      if (!creditNoteId) {
        throw new Error(
          `Books deal credit-note create returned no id: ${resp.message ?? 'unknown'}`,
        );
      }
      await this.prisma.transaction.update({
        where: { id: transactionId },
        data: {
          zohoDealCreditNoteId: creditNoteId,
          zohoSyncStatus: 'OK',
          zohoSyncError: null,
          zohoSyncLastAttemptAt: new Date(),
        },
      });
      this.logger.log(
        `Created Daily Deal credit note ${resp.creditnote?.creditnote_number ?? creditNoteId} for tx ${transactionId} (R${totalRand.toFixed(2)})`,
      );
    } catch (err) {
      await this.markFailed(transactionId, err as Error);
    }
  }

  // ─── Health check ────────────────────────────────────────────────

  /**
   * Lightweight probe for /admin/health. Pings the /organizations
   * endpoint to confirm auth + connectivity. Used by ZB-11.
   */
  async healthCheck(): Promise<{
    ok: boolean;
    enabled: boolean;
    detail?: string;
  }> {
    if (!this.enabled) {
      return { ok: true, enabled: false, detail: 'disabled by feature flag' };
    }
    if (!this.hasCredentials()) {
      return { ok: false, enabled: true, detail: 'missing credentials' };
    }
    try {
      type OrgsResp = { organizations?: Array<{ organization_id?: string }> };
      const resp = await this.request<OrgsResp>('GET', '/organizations');
      const orgIds = resp.organizations?.map((o) => o.organization_id) ?? [];
      if (!orgIds.includes(this.orgId)) {
        return {
          ok: false,
          enabled: true,
          detail: `org ${this.orgId} not visible to credentials`,
        };
      }
      return { ok: true, enabled: true, detail: 'auth + org access verified' };
    } catch (err) {
      return {
        ok: false,
        enabled: true,
        detail: (err as Error).message,
      };
    }
  }
}
